mybatis/mybatis-3

- pom.xml
slf4j to 1.7.10
mockito to 1.10.19
> Update slf4j and mockito

- src/site/xdoc/sqlmap-xml.xml
> Revert "timeout attribute description"

- src/main/java/org/apache/ibatis/session/defaults/DefaultSqlSession.java
DefaulSqlSession is not thread safe. A mere caution in the respective class.
> Mere caution about DefaultSqlSession

- src/main/java/org/apache/ibatis/datasource/pooled/PooledDataSource.java
* This for example allows you to configure a connection before putting
it in the pool.
> PooledDataSource: allow arbitrary unpooled source.

- src/main/java/org/apache/ibatis/annotations/Flush.java
- src/main/java/org/apache/ibatis/binding/MapperMethod.java
- src/test/java/org/apache/ibatis/binding/BoundAuthorMapper.java
- src/test/java/org/apache/ibatis/binding/FlushTest.java
> #356: Support flush statements via Mapper interface

- src/main/java/org/apache/ibatis/jdbc/ScriptRunner.java
- src/test/java/org/apache/ibatis/jdbc/ScriptChangingDelimiter.sql
- src/test/java/org/apache/ibatis/jdbc/ScriptChangingDelimiterMissingDelimiter.sql
- src/test/java/org/apache/ibatis/jdbc/ScriptRunnerTest.java
declarative changing of delimiter support
using standard SQL comment characters, e.g.:
--/@DELIMITER /
--/@DELIMITER ;
>  mybatis #355 PL/SQL is not fully supported

- src/main/java/org/apache/ibatis/executor/loader/ResultLoaderMap.java
- src/main/java/org/apache/ibatis/executor/loader/cglib/CglibProxyFactory.java
- src/main/java/org/apache/ibatis/executor/loader/javassist/JavassistProxyFactory.java
- src/main/java/org/apache/ibatis/io/DefaultVFS.java
- src/main/java/org/apache/ibatis/io/ResolverUtil.java
- src/main/java/org/apache/ibatis/io/VFS.java
- src/main/java/org/apache/ibatis/logging/LogFactory.java
- src/main/java/org/apache/ibatis/transaction/jdbc/JdbcTransaction.java
> #369: Modify to use the Log#isDebugEnabled()

- src/main/java/org/apache/ibatis/executor/loader/ResultLoaderMap.java
- src/main/java/org/apache/ibatis/executor/loader/cglib/CglibProxyFactory.java
- src/main/java/org/apache/ibatis/executor/loader/javassist/JavassistProxyFactory.java
- src/main/java/org/apache/ibatis/io/DefaultVFS.java
- src/main/java/org/apache/ibatis/io/ResolverUtil.java
- src/main/java/org/apache/ibatis/io/VFS.java
- src/main/java/org/apache/ibatis/logging/LogFactory.java
- src/main/java/org/apache/ibatis/transaction/jdbc/JdbcTransaction.java
(cherry picked from commit 9ceedebbb006cff0380d36de024aafec8b510630)
Thanks for merging into master branch!!
If possible, i want to backport to 3.2.x branch.
Please review #369 .
> [3.2.x] #369: Modify to use the Log#isDebugEnabled()

- src/main/java/org/apache/ibatis/builder/xml/XMLConfigBuilder.java
- src/main/java/org/apache/ibatis/executor/statement/BaseStatementHandler.java
- src/main/java/org/apache/ibatis/session/Configuration.java
- src/test/java/org/apache/ibatis/builder/CustomizedSettingsMapperConfig.xml
- src/test/java/org/apache/ibatis/builder/XmlConfigBuilderTest.java
- src/test/java/org/apache/ibatis/executor/BaseExecutorTest.java
- src/test/java/org/apache/ibatis/executor/ExecutorTestHelper.java
For detail, refer to #376 .
Please review this pull request.
> #376: Support the defaultFetchSize in config.xml

- src/main/java/org/apache/ibatis/builder/xml/XMLConfigBuilder.java
- src/main/java/org/apache/ibatis/executor/statement/BaseStatementHandler.java
- src/main/java/org/apache/ibatis/session/Configuration.java
- src/test/java/org/apache/ibatis/builder/CustomizedSettingsMapperConfig.xml
- src/test/java/org/apache/ibatis/builder/XmlConfigBuilderTest.java
- src/test/java/org/apache/ibatis/executor/BaseExecutorTest.java
- src/test/java/org/apache/ibatis/executor/ExecutorTestHelper.java
I backport to 3.2.x from #377(#376) .
Please review this pull request.
> [3.2.x] #376: Support the defaultFetchSize in config.xml 

- src/site/xdoc/index.xml
Trying to get a little more involved in open source, and so I'm starting small (especially since I'm just starting to get the hang of github)...
Saw a small typo on the MyBatis site, so I thought I'd start with that (kinda hard to mess anything up that way).
> Small typo correction

- src/site/site_zh.xml
- src/site/zh/xdoc/dynamic-sql.xml
- src/site/zh/xdoc/getting-started.xml
- src/site/zh/xdoc/index.xml
- src/site/zh/xdoc/logging.xml
- src/site/zh/xdoc/statement-builders.xml
Translate statement-builders.xml, Update index/getting-started/dynamic sql/logging xmls
> Translate statement-builders.xml, Update index/getting-started/dynamic sql/logging xmls

- src/main/java/org/apache/ibatis/executor/BatchExecutor.java
- src/test/java/org/apache/ibatis/submitted/batch_test/BatchTest.java
- src/test/java/org/apache/ibatis/submitted/batch_test/CreateDB.sql
- src/test/java/org/apache/ibatis/submitted/batch_test/Dept.java
- src/test/java/org/apache/ibatis/submitted/batch_test/Mapper.java
- src/test/java/org/apache/ibatis/submitted/batch_test/Mapper.xml
- src/test/java/org/apache/ibatis/submitted/batch_test/User.java
- src/test/java/org/apache/ibatis/submitted/batch_test/mybatis-config.xml
> fix Issues #322

- src/test/java/org/apache/ibatis/jdbc/ScriptRunnerTest.java
Script runner unit tests hard coded line endings.  This makes it system
dependent.  Fixed to get system line separator thus making it
independent of system run on.
> Correct Flakey Script Runner Unit Tests

- src/main/java/org/apache/ibatis/builder/annotation/MapperAnnotationBuilder.java
> Fix issue #366

- src/site/es/xdoc/configuration.xml
- src/site/ja/xdoc/configuration.xml
- src/site/ko/xdoc/configuration.xml
- src/site/xdoc/configuration.xml
- src/site/zh/xdoc/configuration.xml
I've improve documentation for `proxyFactory`. 
Please check it.
> Change explanation of default proxyFactory in documentation (CGLIB -> JAVASSIST)

- src/site/es/xdoc/java-api.xml
- src/site/ja/xdoc/java-api.xml
- src/site/ko/xdoc/java-api.xml
- src/site/xdoc/java-api.xml
- src/site/zh/xdoc/java-api.xml
I've improve documentation for `SqlSession#flushStatements`. 
Please check it.
**Note:**
* There may be wrong grammars and expressions because English is not good.
* Translation is Japanese only.
> Add explanations for SqlSession#flushStatements and @Flush in documentation

- src/site/zh/xdoc/index.xml
The Relative Path is wrong.<li class="en"><a href="./index.html">English</a></li>,we should use double dot like <li class="en"><a href="../index.html">English</a></li>.
> Modify Relative Path

- src/site/zh/xdoc/sqlmap-xml.xml
The Chinese docs has some English sentences which are not translated.
> Translate some sentences to Chinese

- src/site/zh/xdoc/sqlmap-xml.xml
The translation is wrong in resultMap attribute.
the value of column is the same as the sql,
i change it.
<result property="username" column="user_name"/>
<result property="password" column=hashed_password"/>
> The value of column is wrong in Chinese version

- src/site/zh/xdoc/java-api.xml
Translate one English sentence to Chinese.
> Translation

- src/site/zh/xdoc/index.xml
The path to simplified Chinese getting-started.html is wrong.
> Fix relative path to getting-started.html

- src/main/java/org/apache/ibatis/reflection/wrapper/ObjectWrapper.java
- src/main/java/org/apache/ibatis/type/Alias.java
- src/main/java/org/apache/ibatis/type/MappedJdbcTypes.java
- src/main/java/org/apache/ibatis/type/MappedTypes.java
> Polishing method access modifier of annotation and interface

- src/main/java/org/apache/ibatis/annotations/Flush.java
- src/main/java/org/apache/ibatis/session/Configuration.java
> Add @since in @Flush + Configuration

- src/main/java/org/apache/ibatis/builder/MapperBuilderAssistant.java
- src/main/java/org/apache/ibatis/executor/statement/BaseStatementHandler.java
- src/main/java/org/apache/ibatis/mapping/MappedStatement.java
- src/test/java/org/apache/ibatis/executor/ExecutorTestHelper.java
For details, refer to #503 .
Please review.
> Improve handling of defaultStatementTimeout #503

- src/main/java/org/apache/ibatis/builder/MapperBuilderAssistant.java
I've polished to use fluent style coding on Builder object as possible.
Please review.
Thanks.
> Polishing to use fluent style coding as possible in MapperBuilderAssistant

- src/site/es/xdoc/configuration.xml
- src/site/ja/xdoc/configuration.xml
- src/site/ko/xdoc/configuration.xml
- src/site/xdoc/configuration.xml
- src/site/zh/xdoc/configuration.xml
I've added description for autoMappingUnknownColumnBehavior setting. And translated to Japanese version.
For details, refer to #585.
> Add description for autoMappingUnknownColumnBehavior setting

- src/main/java/org/apache/ibatis/executor/resultset/DefaultResultSetHandler.java
> Fix typo in DefaultResultSetHandler

- src/main/java/org/apache/ibatis/session/AutoMappingUnknownColumnBehavior.java
- src/main/java/org/apache/ibatis/session/Configuration.java
- src/test/java/org/apache/ibatis/session/AutoMappingUnknownColumnBehaviorTest.java
> Fix version 3.3.2 -> 3.4.0 for #585

- src/main/java/org/apache/ibatis/executor/statement/BaseStatementHandler.java
- src/test/java/org/apache/ibatis/executor/statement/BaseStatementHandlerTest.java
Please review improvement for mybatis/spring#115 .
> Improve as calculate a time to live of query mybatis/spring#115

- src/site/es/xdoc/configuration.xml
- src/site/ja/xdoc/configuration.xml
- src/site/ko/xdoc/configuration.xml
- src/site/xdoc/configuration.xml
- src/site/zh/xdoc/configuration.xml
Add documentation for gh-598 .
> Add TypeHandler for Blob/InputStream and Clob/Reader in document

- src/site/es/xdoc/configuration.xml
- src/site/ja/xdoc/configuration.xml
- src/site/ko/xdoc/configuration.xml
- src/site/xdoc/configuration.xml
- src/site/zh/xdoc/configuration.xml
I've modified docs, please review this. mybatis/spring#115
> Modify docs for transaction timeout mybatis/spring#115

- src/site/es/xdoc/configuration.xml
- src/site/ja/xdoc/configuration.xml
- src/site/ko/xdoc/configuration.xml
- src/site/xdoc/configuration.xml
- src/site/zh/xdoc/configuration.xml
I've added note for mybatis-typehandlers-jsr310.
Please review.
#557 #597
> Add note for mybatis-typehandlers-jsr310 in docs

- pom.xml
I've updated to latest SLF4J version.
> Update SLF4J 1.7.18

- src/site/xdoc/configuration.xml
> Add doc for the @MappedJdbcTypes includeNullJdbcType attribute

- pom.xml
I've updated to latest SLF4J version.
> Upgrade to SLF4J 1.7.19

- src/site/es/xdoc/getting-started.xml
- src/site/ja/xdoc/getting-started.xml
- src/site/ko/xdoc/getting-started.xml
- src/site/xdoc/getting-started.xml
- src/site/zh/xdoc/getting-started.xml
I will fix all language doc,
but I can't find "mybatis-x.x.x.jar" in French.
fix #615
> #615 doc: Getting started: add download jar file link.

- src/main/java/org/apache/ibatis/session/SqlSessionFactory.java
> Fix typo in JavaDoc

- src/site/es/xdoc/statement-builders.xml
- src/site/ja/xdoc/statement-builders.xml
- src/site/ko/xdoc/statement-builders.xml
- src/site/xdoc/statement-builders.xml
- src/site/zh/xdoc/statement-builders.xml
I've fixed to use bind variable(`#{..}`) instead of replace variable(`${..}`).
> Fix to use bind variable(#{..}) in statement-builders.xml

- src/site/zh/xdoc/dynamic-sql.xml
Update translation of section foreach in dynamic-sql.xml.
> Update translation of section foreach in dynamic-sql.xml.

- src/main/java/org/apache/ibatis/builder/annotation/ProviderSqlSource.java
- src/test/java/org/apache/ibatis/submitted/sqlprovider/OurSqlBuilder.java
- src/test/java/org/apache/ibatis/submitted/sqlprovider/SqlProviderTest.java
@emacarron
I've fixed a error on your adding test case via #639 .
Please review this fix.
> Fix single named argument at a sql provider method (related with #639)

- src/site/es/xdoc/java-api.xml
- src/site/ja/xdoc/java-api.xml
- src/site/ko/xdoc/java-api.xml
- src/site/xdoc/java-api.xml
- src/site/zh/xdoc/java-api.xml
I've updated doc related with #639 .
Please review.
> Update doc for support multiple arguments at sql provider method (related with #639)

- src/test/java/org/apache/ibatis/type/BaseTypeHandlerTest.java
- src/test/java/org/apache/ibatis/type/BigDecimalTypeHandlerTest.java
- src/test/java/org/apache/ibatis/type/BigIntegerTypeHandlerTest.java
- src/test/java/org/apache/ibatis/type/BlobInputStreamTypeHandlerTest.java
- src/test/java/org/apache/ibatis/type/BlobTypeHandlerTest.java
- src/test/java/org/apache/ibatis/type/BooleanTypeHandlerTest.java
- src/test/java/org/apache/ibatis/type/ByteArrayTypeHandlerTest.java
- src/test/java/org/apache/ibatis/type/ByteTypeHandlerTest.java
- src/test/java/org/apache/ibatis/type/CharacterTypeHandlerTest.java
- src/test/java/org/apache/ibatis/type/ClobReaderTypeHandlerTest.java
- src/test/java/org/apache/ibatis/type/ClobTypeHandlerTest.java
- src/test/java/org/apache/ibatis/type/DateOnlyTypeHandlerTest.java
- src/test/java/org/apache/ibatis/type/DateTypeHandlerTest.java
- src/test/java/org/apache/ibatis/type/DoubleTypeHandlerTest.java
- src/test/java/org/apache/ibatis/type/EnumOrdinalTypeHandlerTest.java
- src/test/java/org/apache/ibatis/type/EnumTypeHandlerTest.java
- src/test/java/org/apache/ibatis/type/FloatTypeHandlerTest.java
- src/test/java/org/apache/ibatis/type/IntegerTypeHandlerTest.java
- src/test/java/org/apache/ibatis/type/LongTypeHandlerTest.java
- src/test/java/org/apache/ibatis/type/NClobTypeHandlerTest.java
- src/test/java/org/apache/ibatis/type/NStringTypeHandlerTest.java
- src/test/java/org/apache/ibatis/type/ObjectTypeHandlerTest.java
- src/test/java/org/apache/ibatis/type/ShortTypeHandlerTest.java
- src/test/java/org/apache/ibatis/type/SqlDateTypeHandlerTest.java
- src/test/java/org/apache/ibatis/type/SqlTimeTypeHandlerTest.java
- src/test/java/org/apache/ibatis/type/SqlTimetampTypeHandlerTest.java
- src/test/java/org/apache/ibatis/type/StringTypeHandlerTest.java
- src/test/java/org/apache/ibatis/type/UnknownTypeHandlerTest.java
I've added test cases for existing type handlers and polishing existing test cases.
Please review.
> Polishing test cases for type handlers

- src/test/java/org/apache/ibatis/type/ArrayTypeHandlerTest.java
- src/test/java/org/apache/ibatis/type/BlobByteObjectArrayTypeHandlerTest.java
- src/test/java/org/apache/ibatis/type/ByteObjectArrayTypeHandlerTest.java
I've added test cases for TypeHandler.
Please review.
> Add test cases for TypeHandlers

- src/test/java/org/apache/ibatis/type/CharacterTypeHandlerTest.java
I've fixed mistake for #647 .
Please review.
> Fix wrong mock

- pom.xml
I've updated to latest version.
Please review.
> Update to ognl 3.1.3

- src/main/java/org/apache/ibatis/binding/MapperMethod.java
- src/main/java/org/apache/ibatis/builder/ParameterExpression.java
- src/main/java/org/apache/ibatis/builder/annotation/MapperAnnotationBuilder.java
- src/main/java/org/apache/ibatis/builder/annotation/ProviderSqlSource.java
- src/main/java/org/apache/ibatis/cache/CacheKey.java
- src/main/java/org/apache/ibatis/datasource/jndi/JndiDataSourceFactory.java
- src/main/java/org/apache/ibatis/executor/BaseExecutor.java
- src/main/java/org/apache/ibatis/executor/keygen/SelectKeyGenerator.java
- src/main/java/org/apache/ibatis/executor/loader/cglib/CglibProxyFactory.java
- src/main/java/org/apache/ibatis/executor/loader/javassist/JavassistProxyFactory.java
- src/main/java/org/apache/ibatis/logging/LogFactory.java
- src/main/java/org/apache/ibatis/mapping/MappedStatement.java
- src/main/java/org/apache/ibatis/mapping/ResultMapping.java
- src/main/java/org/apache/ibatis/type/ByteArrayUtils.java
I've polished some codes.
* Removed explicit boxing and unboxing (it is unnecessary at the JDK 1.5 or newer)
* Removed unnecessary new
* Removed unnecessary `null` initialize at local variable  
* Changed to use foreach style at loop processing
* Fixed typo at method name and local variable name
* Added `final` at immutable field
Please review.
Thanks.
> Polishing some code

- src/site/es/xdoc/configuration.xml
- src/site/ja/xdoc/configuration.xml
- src/site/ko/xdoc/configuration.xml
- src/site/xdoc/configuration.xml
- src/site/zh/xdoc/configuration.xml
I've added description for `safeResultHandlerEnabled` in docs.
Please review.
> Add description for 'safeResultHandlerEnabled'

- src/main/java/org/apache/ibatis/session/Configuration.java
I've polished the `Configuration`.
* Add final for immutable field
* Modify local variable name
Please review.
> Polishing the Configuration

- src/main/java/org/apache/ibatis/builder/annotation/MapperAnnotationBuilder.java
- src/test/java/org/apache/ibatis/submitted/cursor_simple/AnnotationMapper.java
- src/test/java/org/apache/ibatis/submitted/cursor_simple/CursorSimpleTest.java
> Support Cursor on annotation based Mapper interface #661

- src/test/java/org/apache/ibatis/binding/BindingTest.java
- src/test/java/org/apache/ibatis/binding/BoundBlogMapper.java
- src/test/java/org/apache/ibatis/builder/AuthorMapper.xml
- src/test/java/org/apache/ibatis/builder/ParameterExpressionTest.java
- src/test/java/org/apache/ibatis/builder/XmlMapperBuilderTest.java
I've added tests for some class.
* MapperMethod
* MapperRegistry
* BaseBuilder
* MapperBuilderAssistant
* ParameterExpression
I will improve tests for other class at later.
> Improve tests

- src/test/java/org/apache/ibatis/submitted/cache/CacheTest.java
- src/test/java/org/apache/ibatis/submitted/cache/ImportantPersonMapper.java
- src/test/java/org/apache/ibatis/submitted/cache/mybatis-config.xml
- src/test/java/org/apache/ibatis/submitted/sqlprovider/Mapper.java
- src/test/java/org/apache/ibatis/submitted/sqlprovider/OurSqlBuilder.java
- src/test/java/org/apache/ibatis/submitted/sqlprovider/SqlProviderTest.java
> Add tests for MapperAnnotationBuilder

- src/main/java/org/apache/ibatis/cursor/defaults/DefaultCursor.java
- src/test/java/org/apache/ibatis/submitted/complex_column/ComplexColumnTest.java
- src/test/java/org/apache/ibatis/submitted/complex_column/PersonMapper.java
- src/test/java/org/apache/ibatis/submitted/cursor_nested/CursorNestedTest.java
> Upadte license year

- src/main/java/org/apache/ibatis/cursor/defaults/DefaultCursor.java
- src/main/java/org/apache/ibatis/cursor/defaults/package-info.java
- src/main/java/org/apache/ibatis/cursor/package-info.java
- src/test/java/org/apache/ibatis/submitted/cursor_simple/CursorSimpleTest.java
I've polished some codes for cursor feature.
* Remove unused import
* Add `final` for immutable field 
* Change generics parameter type name (`E` -> `T`)
* Remove unnecessary cast
* Add `package-info.java`
* Remove unused class (`CursorException`)
Please review.
> Polishing codes for cursor feature

- pom.xml
- src/test/java/org/apache/ibatis/submitted/batch_keys/BatchKeysTest.java
> Update to HSQLDB 2.3.4

- pom.xml
I've updated to latest version.
Please review.
> Upgrade to CGLIB 3.2.3

- src/main/java/org/apache/ibatis/type/TypeHandlerRegistry.java
I've supported for auto-detecting the `JapaneseDateTypeHandler`.
Please review.
> Support auto-detecting JapaneseDateTypeHandler

- src/main/java/org/apache/ibatis/builder/xml/XMLConfigBuilder.java
- src/test/java/org/apache/ibatis/builder/CustomizedSettingsMapperConfig.xml
Backport of #723
(cherry picked from commit ba0c9fbccb05b6aacf09f0b0dbfe3e1db671929a)
Conflicts:
src/test/java/org/apache/ibatis/builder/CustomizedSettingsMapperConfig.xml
> [backporting for 3.3.x] Read properties first! #723

- src/site/es/xdoc/statement-builders.xml
- src/site/ja/xdoc/statement-builders.xml
- src/site/ko/xdoc/statement-builders.xml
- src/site/xdoc/statement-builders.xml
- src/site/zh/xdoc/statement-builders.xml
Modify doc for #726.
Please review.
> Modify doc for statement builders

- pom.xml
I've update to latest version of ognl.
> Upgrade to ognl 3.1.10

- src/test/java/org/apache/ibatis/submitted/array_binding/ArrayBindingTest.java
- src/test/java/org/apache/ibatis/submitted/array_binding/CreateDB.sql
- src/test/java/org/apache/ibatis/submitted/array_binding/Mapper.java
- src/test/java/org/apache/ibatis/submitted/array_binding/Mapper.xml
- src/test/java/org/apache/ibatis/submitted/array_binding/User.java
- src/test/java/org/apache/ibatis/submitted/array_binding/mybatis-config.xml
> Create test reproducing bound array parameter issue

- src/site/zh/xdoc/configuration.xml
- src/site/zh/xdoc/getting-started.xml
- src/site/zh/xdoc/java-api.xml
the "scope" should translate into "作用域",not "范围".
> correct the Chinese translation of the word "scope" in doc

- src/main/java/org/apache/ibatis/logging/jdbc/BaseJdbcLogger.java
- src/test/java/org/apache/ibatis/logging/jdbc/BaseJdbcLoggerTest.java
Enhances parameter logging for SQL ARRAYs: outputs array contents instead of default toString view.
> Logging of Array parameters #742

- src/site/zh/xdoc/sqlmap-xml.xml
> update  sqlmap-xml.xml(zh-CN)

- src/site/zh/xdoc/configuration.xml
- src/site/zh/xdoc/sqlmap-xml.xml
Complete translation of configuration and sqlmap-xml again...
> Complete translation of configuration and sqlmap-xml

- src/site/zh/xdoc/java-api.xml
> Translate for java-api

- src/main/java/org/apache/ibatis/mapping/MappedStatement.java
- src/main/java/org/apache/ibatis/session/Configuration.java
- src/test/java/org/apache/ibatis/builder/XmlConfigBuilderTest.java
> Fix typo in Configuration.getDefaultScriptingLanguageInstance.

- src/site/xdoc/configuration.xml
- src/site/xdoc/java-api.xml
- src/site/xdoc/sqlmap-xml.xml
> Fixed typos in documentation

- src/test/java/org/apache/ibatis/executor/resultset/DefaultResultSetHandlerTest.java
- src/test/java/org/apache/ibatis/executor/statement/BaseStatementHandlerTest.java
- src/test/java/org/apache/ibatis/type/ByteObjectArrayTypeHandlerTest.java
- src/test/java/org/apache/ibatis/type/CharacterTypeHandlerTest.java
- src/test/java/org/apache/ibatis/type/UnknownTypeHandlerTest.java
I've improved how to use of mock. Please review.
> Improve mock

- pom.xml
- src/site/es/xdoc/statement-builders.xml
- src/site/ja/xdoc/statement-builders.xml
- src/site/ko/xdoc/statement-builders.xml
- src/site/xdoc/statement-builders.xml
- src/site/zh/xdoc/java-api.xml
- src/site/zh/xdoc/statement-builders.xml
I've updated documentation for variable-length arguments.
Please review.
> Note:
> 
> I've updated the clirr-maven-plugin's version to fix a maven site build error(This changes is workaround). For detail, please refer to https://github.com/mybatis/parent/pull/55.
> Update explanation for variable-length arguments

- pom.xml
[OGNL 3.1.11](https://github.com/jkuhnert/ognl#release-notes---version-3111) has been released.
> Update to OGNL 3.1.11

- src/main/java/org/apache/ibatis/mapping/VendorDatabaseIdProvider.java
I've fixed to specify correct logger class. see #803.
> Fix logger in VendorDatabaseIdProvider

- src/main/java/org/apache/ibatis/reflection/TypeParameterResolver.java
> Polishing #807

- pom.xml
Mockito 2.2 has been released.
> Upgrade to Mockito 2.2.2

- src/main/java/org/apache/ibatis/builder/xml/mybatis-3-config.dtd
> Remove the 'property' child element of objectWrapperFactory

- pom.xml
I've updated to latest version.
> Upadte mockito 2.2.15

- src/test/java/org/apache/ibatis/submitted/global_variables/AnnotationMapper.java
- src/test/java/org/apache/ibatis/submitted/global_variables/BaseTest.java
- src/test/java/org/apache/ibatis/submitted/global_variables/CustomCache.java
- src/test/java/org/apache/ibatis/submitted/global_variables/Mapper.xml
- src/test/java/org/apache/ibatis/submitted/global_variables/mybatis-config.xml
I've added assertions related with #816.
> Add assertions for injecting externalized properties to cache properties

- src/test/java/org/apache/ibatis/submitted/immutable_constructor/ImmutablePOJOTest.java
> Update copyright year

- src/test/java/org/apache/ibatis/submitted/cache/CacheTest.java
- src/test/java/org/apache/ibatis/submitted/cache/CustomCache.java
- src/test/java/org/apache/ibatis/submitted/cache/CustomCacheMapper.java
I've added tests for improving a coverage percentage.
> Add tests for injecting property value to cache object

- src/main/java/org/apache/ibatis/builder/InitializingObject.java
- src/main/java/org/apache/ibatis/mapping/CacheBuilder.java
- src/test/java/org/apache/ibatis/mapping/CacheBuilderTest.java
> Support the mechanism for initializing a cache after set all properties

- src/site/es/xdoc/sqlmap-xml.xml
- src/site/ja/xdoc/sqlmap-xml.xml
- src/site/ko/xdoc/sqlmap-xml.xml
- src/site/xdoc/sqlmap-xml.xml
- src/site/zh/xdoc/sqlmap-xml.xml
I've updated the reference doc for gh-816.
> Update docs for gh-816

- src/main/java/org/apache/ibatis/executor/resultset/DefaultResultSetHandler.java
I've fixed the https://github.com/mybatis/mybatis-3/issues/830#issuecomment-262561140.
Hi @harawata , please review.
> Fix to reduce memory usage

- src/site/es/xdoc/configuration.xml
- src/site/ja/xdoc/configuration.xml
- src/site/ko/xdoc/configuration.xml
- src/site/xdoc/configuration.xml
- src/site/zh/xdoc/configuration.xml
> Fix typo for SqlSessionFactoryBuilder in doc

- src/main/java/org/apache/ibatis/parsing/PropertyParser.java
- src/site/es/xdoc/configuration.xml
- src/site/ja/xdoc/configuration.xml
- src/site/ko/xdoc/configuration.xml
- src/site/xdoc/configuration.xml
- src/site/zh/xdoc/configuration.xml
- src/test/java/org/apache/ibatis/parsing/PropertyParserTest.java
- src/test/java/org/apache/ibatis/submitted/global_variables_defaults/AnnotationMapperTest.java
- src/test/java/org/apache/ibatis/submitted/global_variables_defaults/ConfigurationTest.java
- src/test/java/org/apache/ibatis/submitted/global_variables_defaults/CustomizationTest.java
- src/test/java/org/apache/ibatis/submitted/global_variables_defaults/SupportClasses.java
- src/test/java/org/apache/ibatis/submitted/global_variables_defaults/XmlMapperTest$XmlMapper.xml
- src/test/java/org/apache/ibatis/submitted/global_variables_defaults/XmlMapperTest.java
- src/test/java/org/apache/ibatis/submitted/global_variables_defaults/mybatis-config-custom-separator.xml
- src/test/java/org/apache/ibatis/submitted/global_variables_defaults/mybatis-config.xml
I've fixed the gh-852. In this version, this feature is disabled by default for keeping backward compatibility. However I want to change enabling by default at next minor version(3.5.0).
> Allow to specify a default value on placeholder

- src/site/es/xdoc/sqlmap-xml.xml
- src/site/ja/xdoc/sqlmap-xml.xml
- src/site/ko/xdoc/sqlmap-xml.xml
- src/site/xdoc/configuration.xml
- src/site/xdoc/sqlmap-xml.xml
- src/site/zh/xdoc/sqlmap-xml.xml
> Fix typos in reference doc

- src/main/java/org/apache/ibatis/builder/xml/XMLIncludeTransformer.java
- src/main/java/org/apache/ibatis/parsing/GenericTokenParser.java
Fixing a problem reported in https://github.com/mybatis/mybatis-3/issues/743#issuecomment-266013507
> Memory usage optimization when parsing mapper files

- src/test/java/org/apache/ibatis/logging/jdbc/ConnectionLoggerTest.java
- src/test/java/org/apache/ibatis/logging/jdbc/PreparedStatementLoggerTest.java
- src/test/java/org/apache/ibatis/logging/jdbc/StatementLoggerTest.java
> Add unit tests.

- src/main/java/org/apache/ibatis/jdbc/AbstractSQL.java
- src/test/java/org/apache/ibatis/jdbc/SQLTest.java
> Fix for #903

- src/site/zh/xdoc/configuration.xml
> Add Chinese Translation

- src/main/java/org/apache/ibatis/mapping/BoundSql.java
change the word 'form' to 'from'
> update the comment in this javafile

- src/site/xdoc/configuration.xml
- src/site/xdoc/getting-started.xml
This is nowhere near complete on what would need done to fully cleanup all build warnings and fix document overall.  I did this specific work probably a year back and never got motivated enough to finish it off.  Now just trying to get this off my plate of outstanding items to prevent future merge conflicts (if any - it's been rather smooth).
> [pdf] Polishing pdf doc by reducing some warnings during generation

- src/site/zh/xdoc/configuration.xml
- src/site/zh/xdoc/index.xml
> Update chinese documentation for readability

- src/main/java/org/apache/ibatis/builder/xml/XMLIncludeTransformer.java
- src/main/java/org/apache/ibatis/executor/BatchExecutorException.java
- src/main/java/org/apache/ibatis/jdbc/SqlRunner.java
> Modify spelling errors

- pom.xml
> Upgrade to javassist 3.22.0-CR2

- src/main/java/org/apache/ibatis/datasource/pooled/PooledDataSource.java
- src/site/es/xdoc/configuration.xml
- src/site/ja/xdoc/configuration.xml
- src/site/ko/xdoc/configuration.xml
- src/site/xdoc/configuration.xml
- src/site/zh/xdoc/configuration.xml
Hi, I read all code about PooledDataSource and very appreciate the contributors implement this awesome datasource.
I found there have little comments in this file and not easy to understand the logic flow of  `PooledDataSource .popConnection()` for someone who wants to contribute on MyBatis.
So, I add some comments for this time and eliminate a magic number in this file.
Just check what I have modified and wish you will accept this merge request. 
I would like to help more developer to understand the detail of the implementation about Mybatis and improve the quality of this implementation.
Yours, Jason Leaster
> add more comments for PooledDataSource and eliminate magic number

- src/main/java/org/apache/ibatis/executor/keygen/Jdbc3KeyGenerator.java
- src/test/java/org/apache/ibatis/submitted/keygen/Jdbc3KeyGeneratorTest.java
- src/test/java/org/apache/ibatis/submitted/usesjava8/postgres_genkeys/CreateDB.sql
- src/test/java/org/apache/ibatis/submitted/usesjava8/postgres_genkeys/Mapper.java
- src/test/java/org/apache/ibatis/submitted/usesjava8/postgres_genkeys/PostgresGeneratedKeysTest.java
- src/test/java/org/apache/ibatis/submitted/usesjava8/postgres_genkeys/Section.java
- src/test/java/org/apache/ibatis/submitted/usesjava8/postgres_genkeys/User.java
@kazuki43zoo ,
This is the second try. Please review this when you have the time.
Thanks in advance,
Iwao
* #782 
* #902
> Reverted #782 as a workaround for #902 .

- src/site/zh/xdoc/configuration.xml
Translating ```configurationFactory ``` in **configuration.xml**
> Translating configurationFactory in settings

- src/site/ko/xdoc/configuration.xml
- src/site/ko/xdoc/java-api.xml
- src/site/ko/xdoc/sqlmap-xml.xml
- src/site/ko/xdoc/statement-builders.xml
korean documentation translated.
> korean documentation translated

- .travis.yml
- src/main/java/org/apache/ibatis/builder/xml/XMLIncludeTransformer.java
- src/test/java/org/apache/ibatis/submitted/include_property/IncludePropertyTest.java
- src/test/java/org/apache/ibatis/submitted/include_property/Mapper.xml
I have implemented change for https://github.com/mybatis/mybatis-3/issues/1069
> Include SQL fragment replaces placeholders in attributes too

- src/main/java/org/apache/ibatis/binding/MapperMethod.java
- src/main/java/org/apache/ibatis/binding/MapperProxy.java
- src/main/java/org/apache/ibatis/builder/annotation/MapperAnnotationBuilder.java
- src/main/java/org/apache/ibatis/cursor/defaults/DefaultCursor.java
- src/main/java/org/apache/ibatis/datasource/pooled/PooledConnection.java
- src/main/java/org/apache/ibatis/executor/CachingExecutor.java
- src/main/java/org/apache/ibatis/executor/loader/cglib/CglibProxyFactory.java
- src/main/java/org/apache/ibatis/executor/loader/javassist/JavassistProxyFactory.java
- src/main/java/org/apache/ibatis/executor/resultset/DefaultResultSetHandler.java
- src/main/java/org/apache/ibatis/io/ResolverUtil.java
- src/main/java/org/apache/ibatis/type/DateOnlyTypeHandler.java
- src/main/java/org/apache/ibatis/type/DateTypeHandler.java
- src/main/java/org/apache/ibatis/type/TimeOnlyTypeHandler.java
> Fix some PMD reports

- src/main/java/org/apache/ibatis/builder/annotation/ProviderSqlSource.java
- src/test/java/org/apache/ibatis/submitted/sqlprovider/SqlProviderTest.java
Fixes gh-1130
@mybatis/committers 
> Allow calling a static provider method without instantiation

- src/site/zh/xdoc/configuration.xml
- src/site/zh/xdoc/getting-started.xml
- src/site/zh/xdoc/java-api.xml
- src/site/zh/xdoc/sqlmap-xml.xml
> Improve Chinese translation

- src/site/zh/xdoc/configuration.xml
- src/site/zh/xdoc/sqlmap-xml.xml
Fix a small typo for Chinese documentation
> Improve Chinese documentation quality

- src/site/zh/xdoc/logging.xml
Correct translation and delete newlines that can be rendered as spaces by browsers.
> Correct Chinese translation in logging.xml

- src/main/java/org/apache/ibatis/type/BaseTypeHandler.java
> Deprecated the BaseTypeHandler#configuration #1203

- pom.xml
> Upgrade to ognl 3.1.17 #1219

- pom.xml
- src/main/java/org/apache/ibatis/mapping/BoundSql.java
- src/main/java/org/apache/ibatis/reflection/ParamNameResolver.java
> Fix mvn site error after mybatis-parent 31-SNAPSHOT

- src/main/java/org/apache/ibatis/builder/annotation/MapperAnnotationBuilder.java
I've polished internally codes.
> Change the variable scope of annotation sets in MapperAnnotationBuilder

- src/main/java/org/apache/ibatis/cache/decorators/SerializedCache.java
- src/main/java/org/apache/ibatis/datasource/pooled/PooledDataSource.java
- src/main/java/org/apache/ibatis/io/DefaultVFS.java
- src/main/java/org/apache/ibatis/io/Resources.java
- src/main/java/org/apache/ibatis/session/SqlSessionManager.java
* Close an external resource reliably if occurred exception
* Use try-with-resources
> Improve a logic for closing an external resource

- src/main/java/org/apache/ibatis/builder/xml/XMLMapperEntityResolver.java
- src/main/java/org/apache/ibatis/datasource/pooled/PooledConnection.java
- src/main/java/org/apache/ibatis/datasource/pooled/PooledDataSource.java
- src/main/java/org/apache/ibatis/executor/BatchExecutorException.java
- src/main/java/org/apache/ibatis/io/ClassLoaderWrapper.java
- src/main/java/org/apache/ibatis/io/Resources.java
- src/main/java/org/apache/ibatis/jdbc/SqlRunner.java
- src/main/java/org/apache/ibatis/logging/jdbc/ConnectionLogger.java
- src/main/java/org/apache/ibatis/logging/jdbc/PreparedStatementLogger.java
- src/main/java/org/apache/ibatis/logging/jdbc/ResultSetLogger.java
- src/main/java/org/apache/ibatis/logging/jdbc/StatementLogger.java
- src/main/java/org/apache/ibatis/reflection/Reflector.java
Correct document comments, not text comments, are included in the document and highlighted by the IDE.
```
/**
* 
*/
```
instead of
```
/*
*
*/
```
> Fixed some comments

- src/main/java/org/apache/ibatis/datasource/pooled/PooledDataSource.java
- src/main/java/org/apache/ibatis/logging/jdbc/PreparedStatementLogger.java
- src/main/java/org/apache/ibatis/reflection/Reflector.java
> Typo fixes

- src/site/es/xdoc/sqlmap-xml.xml
- src/site/ja/xdoc/sqlmap-xml.xml
- src/site/ko/xdoc/sqlmap-xml.xml
- src/site/xdoc/sqlmap-xml.xml
- src/site/zh/xdoc/sqlmap-xml.xml
hi.
this timeout example is not realistic.
I thought it a milliseconds.
thank you.
> Update timeout config for realistic

- src/test/java/org/apache/ibatis/submitted/associationtest/AssociationTest.java
- src/test/java/org/apache/ibatis/submitted/associationtest/Mapper.java
- src/test/java/org/apache/ibatis/submitted/associationtest/Mapper.xml
> Association javaType property not automatically resolved

- src/main/java/org/apache/ibatis/executor/BaseExecutor.java
I backport for supporting 3.4.x users (user for Java 6 or 7).
WDYT?
> Backport gh-1386 to 3.4.x line 

- src/main/java/org/apache/ibatis/builder/xml/XMLConfigBuilder.java
- src/main/java/org/apache/ibatis/executor/loader/cglib/CglibProxyFactory.java
- src/main/java/org/apache/ibatis/executor/loader/javassist/JavassistProxyFactory.java
- src/main/java/org/apache/ibatis/mapping/VendorDatabaseIdProvider.java
- src/main/java/org/apache/ibatis/session/AutoMappingUnknownColumnBehavior.java
> Fix log initialization timing on some class

- src/main/java/org/apache/ibatis/builder/xml/mybatis-mapper.xsd
See https://github.com/mybatis/mybatis-3/commits/master/src/main/java/org/apache/ibatis/builder/xml/mybatis-3-mapper.dtd
* https://github.com/mybatis/mybatis-3/commit/25a41f8730026a718ad8f3a8d459b834feb2321c#diff-b844a0ed11523635f2a371336a1d7362
* https://github.com/mybatis/mybatis-3/commit/fdf7a9ed402f0f4626510bece72d6c795d5789fa#diff-b844a0ed11523635f2a371336a1d7362
* #1393
> Apply latest changing to XSD file

- README.md
See here: https://blog.versioneye.com/2017/10/19/versioneye-sunset-process/
> versioneye is closed, remove it.

- src/main/java/org/apache/ibatis/datasource/pooled/PooledConnection.java
The clause 'else' is unnecessary
> Remove unnecessary 'else'

- src/site/es/xdoc/sqlmap-xml.xml
- src/site/ja/xdoc/sqlmap-xml.xml
- src/site/ko/xdoc/sqlmap-xml.xml
- src/site/xdoc/sqlmap-xml.xml
- src/site/zh/xdoc/sqlmap-xml.xml
> doc: add usage example of string substitution

- src/main/java/org/apache/ibatis/cursor/Cursor.java
- src/test/java/org/apache/ibatis/submitted/cursor_simple/Mapper.xml
As agreed in [this thread](https://groups.google.com/forum/#!topic/mybatis-user/bCHi1iIR8eY) I have updated tests and comments for cursor.
> Removed unnecessary ordering from cursor tests and updated comments

- .travis.yml
- pom.xml
> Fix build error on JDK 6

- src/main/java/org/apache/ibatis/builder/annotation/MapperAnnotationBuilder.java
- src/main/java/org/apache/ibatis/cache/CacheKey.java
- src/main/java/org/apache/ibatis/logging/jdbc/ResultSetLogger.java
- src/main/java/org/apache/ibatis/reflection/factory/DefaultObjectFactory.java
- src/main/java/org/apache/ibatis/scripting/xmltags/DynamicContext.java
Cleanup code using `StringJoiner`, `Collectors.joining` and `String.join`.
> Change to use the StringJoiner instead of the StringBuilder

- src/site/ko/xdoc/getting-started.xml
> Modified korean document text in getting-started.xml

- src/main/java/org/apache/ibatis/type/BaseTypeHandler.java
- src/main/java/org/apache/ibatis/type/TypeHandler.java
> api documantation for columnLabel parameter

- src/test/java/org/apache/ibatis/io/ResolverUtilTest.java
add unit tests for ResolverUtil.
> add unit tests for ResolverUtil.

- src/main/java/org/apache/ibatis/annotations/CacheNamespace.java
- src/test/java/org/apache/ibatis/io/VFSTest.java
- src/test/java/org/apache/ibatis/parsing/XPathParserTest.java
> [tests] Improve test coverage.

- src/site/es/xdoc/dynamic-sql.xml
- src/site/es/xdoc/java-api.xml
- src/site/ja/xdoc/dynamic-sql.xml
- src/site/ja/xdoc/java-api.xml
- src/site/ko/xdoc/dynamic-sql.xml
- src/site/ko/xdoc/java-api.xml
- src/site/xdoc/dynamic-sql.xml
- src/site/xdoc/java-api.xml
- src/site/zh/xdoc/dynamic-sql.xml
- src/site/zh/xdoc/java-api.xml
* Added <script> functionality for annotated mappers for dynamic SQL.
* Fixed arguments for Arg annotation
> Change in documentation

- src/site/ja/xdoc/logging.xml
Hi, I'm Japanese.
I modified Japanese document in `logging.xml`.
Please merge PR if there is no problem☺️
> fix Japanese document in logging.xml

- src/main/java/org/apache/ibatis/parsing/XNode.java
> remove unnecessary null check

- src/main/java/org/apache/ibatis/parsing/GenericTokenParser.java
- src/main/java/org/apache/ibatis/reflection/Reflector.java
- src/main/java/org/apache/ibatis/reflection/property/PropertyNamer.java
>  Minor changes.

- src/test/java/org/apache/ibatis/submitted/cglib_lazy_error/CglibNPETest.java
This reverts commit 8c370c0e8ec624832454746410ace73b2267413e. (https://github.com/mybatis/mybatis-3/pull/1598#pullrequestreview-261562021)
> Revert "remove redundant code..."

- src/main/java/org/apache/ibatis/builder/BaseBuilder.java
- src/main/java/org/apache/ibatis/builder/annotation/ProviderSqlSource.java
- src/main/java/org/apache/ibatis/builder/xml/XMLConfigBuilder.java
- src/main/java/org/apache/ibatis/datasource/unpooled/UnpooledDataSource.java
- src/main/java/org/apache/ibatis/io/VFS.java
- src/test/java/org/apache/ibatis/builder/XmlMapperBuilderTest.java
- src/test/java/org/apache/ibatis/exceptions/GeneralExceptionsTest.java
Because Class#newInstance was deprecated since JDK 9+.
> Change to Constructor#newInstance from Class#newInstance

- src/test/java/org/apache/ibatis/builder/xsd/XmlConfigBuilderTest.java
Fix a  spelling mistake in testUnit misXmlConfigBuilderTest
> fix spelling mistake in testUnit misXmlConfigBuilderTest

- src/main/java/org/apache/ibatis/binding/MapperProxy.java
<strike>Compiling the project now requires JDK 9 as this fix uses a method introduced in JDK 9.</strike>
This should fix #1636 .
>  Avoid illegal reflective access on default method invocation

- src/main/java/org/apache/ibatis/cache/CacheKey.java
- src/main/java/org/apache/ibatis/cache/NullCacheKey.java
- src/main/java/org/apache/ibatis/io/DefaultVFS.java
- src/main/java/org/apache/ibatis/parsing/XPathParser.java
* Fix all block issues on Bug type
* Fix some critical issues on Bug type
* Fix all block issues on Vulnerability type
> Fix some sonar reports

- src/site/es/xdoc/sqlmap-xml.xml
- src/site/ja/xdoc/sqlmap-xml.xml
- src/site/ko/xdoc/sqlmap-xml.xml
- src/site/zh/xdoc/sqlmap-xml.xml
Update namespace of class Cache from "org.mybatis.cache" to "org.apache.ibatis.cache"
> [doc] Update namespace of class Cache

- src/main/java/org/apache/ibatis/io/VFS.java
I found one line of code to simplify when using IDEA to inspect the code, so I submit a PR here.
> Remove redundant null check in VFSHolder

- pom.xml
- src/main/java/org/apache/ibatis/executor/BatchExecutor.java
- src/main/java/org/apache/ibatis/executor/SimpleExecutor.java
- src/test/java/org/apache/ibatis/submitted/cursor_simple/Mapper.java
- src/test/java/org/apache/ibatis/submitted/cursor_simple/MysqlCursorTest.java
- src/test/java/org/apache/ibatis/testcontainers/MysqlContainer.java
[issue-1654](https://github.com/mybatis/mybatis-3/issues/1654)
> fix queryCusor() fails in streaming mode of MySQL Connector/J (fetchSize=Integer.MIN_VALUE) #1654

- src/main/java/org/apache/ibatis/jdbc/AbstractSQL.java
replace `foreach statement` with `Collections.addAll`
> refactor: simplify three lines code in AbstractSQL.java

- src/main/java/org/apache/ibatis/cache/decorators/ScheduledCache.java
The issue was scanned by SonarQube.
> promote 1000 to long

- src/main/java/org/apache/ibatis/parsing/XNode.java
- src/test/java/org/apache/ibatis/parsing/XPathParserTest.java
Format class XNode toString method, make the sub label retract a 'tab'. eclipse "ctrl+shift+i" to watch the value of variable friendly.
> format XNode toString method.

- src/main/java/org/apache/ibatis/executor/statement/StatementUtil.java
StatementUtil.applyTransactionTimeout's else unnecessary.
> Remove unnecessary code.

- src/main/java/org/apache/ibatis/datasource/unpooled/UnpooledDataSource.java
Getters and setters should be synchronized in pairs
> add the synchronized keyword to getDriver()

- src/main/java/org/apache/ibatis/executor/keygen/SelectKeyGenerator.java
refactor: remove unnecessary code. here keyProperties must not be null.
> refactor: remove unnecessary code.

- src/main/java/org/apache/ibatis/datasource/pooled/PooledConnection.java
> fix issue #1691

- src/main/java/org/apache/ibatis/session/Configuration.java
- src/main/java/org/apache/ibatis/type/TypeHandlerRegistry.java
- src/main/java/org/apache/ibatis/type/UnknownTypeHandler.java
- src/test/java/org/apache/ibatis/submitted/nestedresulthandler_gh1551/CreateDB.sql
- src/test/java/org/apache/ibatis/submitted/nestedresulthandler_gh1551/NestedResultHandlerGh1551Test.java
- src/test/java/org/apache/ibatis/submitted/nestedresulthandler_gh1551/ProductInfo.java
- src/test/java/org/apache/ibatis/submitted/nestedresulthandler_gh1551/ProductMapper.java
- src/test/java/org/apache/ibatis/submitted/nestedresulthandler_gh1551/ProductMapper.xml
- src/test/java/org/apache/ibatis/submitted/nestedresulthandler_gh1551/ProductResp.java
- src/test/java/org/apache/ibatis/submitted/nestedresulthandler_gh1551/ProductSku.java
- src/test/java/org/apache/ibatis/submitted/nestedresulthandler_gh1551/mybatis-config.xml
- src/test/java/org/apache/ibatis/type/UnknownTypeHandlerTest.java
> Change to refers useColumnLabel at UnknownTypeHandler

- src/main/java/org/apache/ibatis/cache/impl/PerpetualCache.java
modifier field to final in PerpetualCache file，and add initialCapacity to the field。
fixes #1713
> modifier field to final

- pom.xml
- src/test/java/org/apache/ibatis/binding/BindingTest.java
- src/test/java/org/apache/ibatis/builder/XmlConfigBuilderTest.java
- src/test/java/org/apache/ibatis/builder/XmlMapperBuilderTest.java
- src/test/java/org/apache/ibatis/mapping/CacheBuilderTest.java
- src/test/java/org/apache/ibatis/reflection/ReflectorTest.java
- src/test/java/org/apache/ibatis/scripting/LanguageDriverRegistryTest.java
- src/test/java/org/apache/ibatis/submitted/cache/CacheTest.java
- src/test/java/org/apache/ibatis/submitted/foreach/ForEachTest.java
- src/test/java/org/apache/ibatis/submitted/keygen/Jdbc3KeyGeneratorTest.java
- src/test/java/org/apache/ibatis/submitted/mapper_extend/MapperExtendTest.java
- src/test/java/org/apache/ibatis/submitted/named_constructor_args/InvalidNamedConstructorArgsTest.java
- src/test/java/org/apache/ibatis/submitted/results_id/IdConflictTest.java
> Bump catch-exception from 1.4.6 to 2.0

- src/main/java/org/apache/ibatis/executor/loader/AbstractSerialStateHolder.java
- src/main/java/org/apache/ibatis/jdbc/ScriptRunner.java
- src/main/java/org/apache/ibatis/mapping/VendorDatabaseIdProvider.java
- src/main/java/org/apache/ibatis/parsing/XNode.java
- src/main/java/org/apache/ibatis/reflection/factory/DefaultObjectFactory.java
- src/main/java/org/apache/ibatis/transaction/managed/ManagedTransactionFactory.java
In java8,new Method[0] is better than new Method[methods.size()],you can learn about this from the below url.
https://shipilev.net/blog/2016/arrays-wisdom-ancients/
> Optimize some code

- src/test/java/org/apache/ibatis/binding/MapperWithOneAndMany.java
Even though test worked, it failed to resolve in eclipse and showed an error.  Adding full path to clear error.
> [test] Fix resolvable error

- src/main/java/org/apache/ibatis/builder/xml/XMLMapperBuilder.java
- src/main/java/org/apache/ibatis/executor/ReuseExecutor.java
- src/main/java/org/apache/ibatis/jdbc/ScriptRunner.java
- src/main/java/org/apache/ibatis/reflection/Reflector.java
- src/test/java/org/apache/ibatis/submitted/blocking_cache/Person.java
- src/test/java/org/apache/ibatis/submitted/cache/Person.java
- src/test/java/org/apache/ibatis/submitted/mapper_type_parameter/BaseMapper.java
I find some code to refine using analysis.
> Refine some code

- src/main/java/org/apache/ibatis/builder/annotation/MapperAnnotationBuilder.java
- src/main/java/org/apache/ibatis/builder/xml/XMLMapperBuilder.java
Partial application of changes from PR #1652
> [cleanup] Simplify code based on PR #1652

- src/test/java/org/apache/ibatis/jdbc/PooledDataSourceTest.java
fixed typos in PooledDataSourceTest
> fixed typo

- .travis.yml
- pom.xml
> Apply mybatis-parent 32-SNAPSHOT for build error using JDK 15 on Travis CI

- src/main/java/org/apache/ibatis/io/DefaultVFS.java
Should fix #1974 .
Also see : https://stackoverflow.com/questions/62756712
If someone knows a way to write a unit test for this, please let me know. ;D
Cc-ing @kazuki43zoo
> Catch InvalidPathException thrown under JPMS

- src/main/java/org/apache/ibatis/annotations/Options.java
Fix typo in Options annotation
> Modify javadoc in Options.java

- src/test/java/org/apache/ibatis/cache/CacheKeyTest.java
- src/test/java/org/apache/ibatis/cache/PerpetualCacheTest.java
- src/test/java/org/apache/ibatis/cache/SerializedCacheTest.java
Hello, I've added few tests on cache package to increase code coverage.
Before: 89% -> After: 90%
> Added tests for cache package

- src/site/zh/xdoc/dynamic-sql.xml
Modify 2 Chinese words translations:
`挑选` -> `精选`
`合宜` -> `方便`
> Modify 2 Chinese words translations in dynamic-sql.xml

- src/test/java/org/apache/ibatis/parsing/XPathParserTest.java
- src/test/java/resources/nodelet_test.xml
Hello again,
Code coverage increased 85% -> 95%
> Added tests for parsing package

- src/test/java/org/apache/ibatis/executor/statement/BaseStatementHandlerTest.java
There are some method what is third party lib is deprecated , I'm migrating . WIP.
> Replace deprecated Mockito.verifyZeroInteractions with verifyNoInteractions

- .github/workflows/ci.yaml
The build will be tested on:
Ubuntu 18.04, Latest Mac OSX and Windows 2016
Using JDK on each operating system:
8, 11, 15 and 16-ea
> Added github actions to test the build

- .github/workflows/ci.yaml
- .github/workflows/sonar.yaml
- .github/workflows/sonatype.yaml
- .mvn/extensions.xml
- .mvn/settings.xml
- pom.xml
- travis/after_success.sh
Note: Sonatype and Sonar will fail until secrets are added.
> Github Actions - Adjust OS usage, sonatype push add, skip license check due to shallow clone, sonar, adjustments to travis

- src/test/java/org/apache/ibatis/reflection/MetaObjectTest.java
delete MetaObjectTest#shouldSetAndGetSelfListItem, it's repetitive.
close #2123
> chore: delete duplicate test case

- src/main/java/org/apache/ibatis/cache/decorators/BlockingCache.java
@harawata  @hazendaz   to be reviewed, thanks
> chore: delete unused import

- src/site/ko/xdoc/getting-started.xml
> Typo correction

- src/site/ko/xdoc/configuration.xml
Translate Configuration XML (defaultSqlProviderType)
English to Korean
> Translate English to Korean (Configuration XML)

- src/main/java/org/apache/ibatis/builder/xml/XMLConfigBuilder.java
> change to try with resources

- src/site/ko/xdoc/configuration.xml
typo correction configuration.xml in korean version especially focusing on spacing
> fix doc typo (typo correction configuration.xml in korean version)

- src/main/java/org/apache/ibatis/jdbc/Null.java
> use final to decorate field in the Null.java

- src/site/es/xdoc/sqlmap-xml.xml
- src/site/ja/xdoc/sqlmap-xml.xml
- src/site/ko/xdoc/sqlmap-xml.xml
- src/site/xdoc/sqlmap-xml.xml
Fixes gh-2056
I applied a workaround.
> Fix broken links on document toc

- src/main/java/org/apache/ibatis/type/TypeHandler.java
- src/main/java/org/apache/ibatis/type/TypeHandlerRegistry.java
Fix wrong spelling "Colunm" in TypeHandler
Fix wrong spelling "regsiterd" in TypeHandlerRegistry
> Fix two typos in TypeHandler and TypeHandlerRegistry

- src/test/java/org/apache/ibatis/type/TypeHandlerRegistryTest.java
Just litte important function name in test case.
> Words correction in TypeHandlerRegistryTest.

- src/main/java/org/apache/ibatis/cache/decorators/BlockingCache.java
- src/main/java/org/apache/ibatis/datasource/pooled/PoolState.java
- src/main/java/org/apache/ibatis/io/DefaultVFS.java
> Correct the spellings in cache module  and io module datasource module.

- src/main/java/org/apache/ibatis/type/BaseTypeHandler.java
- src/test/java/org/apache/ibatis/builder/XmlMapperBuilderTest.java
> Correct the spellings in two places.

- .github/workflows/ci.yaml
> [ci] Drop Java 16 (EOL)

- dependencies.html
fix wrong cglib repository link in dependencies.html.
> fix wrong cglib repository link

- src/main/java/org/apache/ibatis/datasource/pooled/PooledDataSource.java
> set interrupt flag

- src/main/java/org/apache/ibatis/scripting/xmltags/VarDeclSqlNode.java
> Improve readability

- src/site/zh/xdoc/logging.xml
completely translate the `logging.xml` so far.
> update the logging.xml in zh doc

- src/main/java/org/apache/ibatis/datasource/pooled/PooledDataSource.java
synchronized refactor  fair lock
> PooledDataSource : replace synchronized block with ReentrantLock

- src/main/java/org/apache/ibatis/binding/MapperMethod.java
Added a missing single quote in an exception message in MapperMethod.java
> Added a missing single quote in an exception message

- src/site/ko/xdoc/configuration.xml
- src/site/ko/xdoc/dynamic-sql.xml
- src/site/ko/xdoc/sqlmap-xml.xml
Translated the untranslated parts of the following files into Korean.
- configuration.xml
- dynamic-sql.xml
- sqlmap-xml.xml
I will translate the untranslated parts of the remaining files in the future.
Thank you.
> Translate into Korean. (configuration, dynamic-sql, sqlmap-xml)

- src/site/zh/xdoc/configuration.xml
Change the Chinese tranlation for comment 'Register all interfaces in a package as mappers'.
> doc: update Chinese translation for configuration.xml

- .github/workflows/ci.yaml
> Include JDK 21 in CI build

- src/main/java/org/apache/ibatis/reflection/Reflector.java
void or other types are never null
> Removed unnecessary judgments

- src/site/es/xdoc/statement-builders.xml
Misspelled word
puecdes -> puedes
> docs: misspelled word

- src/main/java/org/apache/ibatis/datasource/pooled/PooledDataSource.java
This seems to be a redundant assignment.
closes #2926
> Removed redundant assignments.

- src/main/java/org/apache/ibatis/cache/decorators/FifoCache.java
- src/test/java/org/apache/ibatis/cache/FifoCacheTest.java
solve the unremoved result in keyList #2934
> solve the unremoved result in keyList

- src/main/java/org/apache/ibatis/reflection/MetaClass.java
- src/main/java/org/apache/ibatis/reflection/MetaObject.java
- src/main/java/org/apache/ibatis/reflection/wrapper/BeanWrapper.java
- src/main/java/org/apache/ibatis/scripting/defaults/DefaultParameterHandler.java
- src/main/java/org/apache/ibatis/scripting/xmltags/TrimSqlNode.java
- src/site/es/xdoc/statement-builders.xml
I was lucky enough to read the source code of mybatis, and I changed some places that seemed to be able to be optimized a little bit.
> just minor refine

- src/main/java/org/apache/ibatis/datasource/pooled/PooledDataSource.java
was previously ignored response value
> [ci] Handle wait condition and write log if it fails

- pom.xml
- src/test/java/org/apache/ibatis/submitted/localtime/LocalTimeTest.java
- src/test/java/org/apache/ibatis/submitted/timestamp_with_timezone/TimestampWithTimezoneTypeHandlerTest.java
- src/test/java/org/apache/ibatis/submitted/timezone_edge_case/TimezoneEdgeCaseTest.java
time zones and nano seconds now work.
> Fix hsqldb to latest to clear CVE issues in our tests

- src/site/markdown/java-api.md
- src/site/markdown/logging.md
Hi, I found some typos in the document.
> docs: fix typos in the markdown

- pom.xml
issue with staging not creating in correct place has to do with the url of the project.  Correcting that as it should not point to mybatis org but rather the repo.
> Fix HEAD tag and correct URL for site

- src/main/java/org/apache/ibatis/plugin/Invocation.java
- src/test/java/org/apache/ibatis/plugin/Mapper.java
- src/test/java/org/apache/ibatis/plugin/PluginTest.java
- src/test/resources/org/apache/ibatis/plugin/CreateDB.sql
- src/test/resources/org/apache/ibatis/plugin/mybatis-config.xml
> Prevent `Invocation` from invoking arbitrary method

- src/site/ko/markdown/getting-started.md
This pr fixes typo in korean document. The `도입부` is appropriate meaning for `introduction`.
> Fix korean typo

- src/test/java/org/apache/ibatis/reflection/property/PropertyTokenizerTest.java
Supplement the missing unit test cases for `PropertyTokenizer`.
> Add PropertyTokenizer test

- src/site/es/markdown/index.md
correcting small spelling mistake in spanish index
> Correct spanish translation

- src/site/ko/xdoc/java-api.xml
Translated untranslated parts in file "ko/xdoc/java-api.xml"
> Translate untranslated description at ko/xdoc/java-api.xml to Korean

- src/main/java/org/apache/ibatis/datasource/jndi/JndiDataSourceFactory.java
- src/main/java/org/apache/ibatis/scripting/LanguageDriverRegistry.java
- src/test/java/org/apache/ibatis/autoconstructor/ExtensiveSubject.java
- src/test/java/org/apache/ibatis/builder/XmlConfigBuilderTest.java
- src/test/java/org/apache/ibatis/submitted/camelcase/Camel.java
static naming type was used rather than camel case, fix to be camel case as not static.
> Fix casing

- src/test/java/org/apache/ibatis/testcontainers/MysqlContainer.java
- src/test/java/org/apache/ibatis/testcontainers/PgContainer.java
No-arg constructors are deprecated.
> Pass docker image name to constructors
