src/main/java/org/apache/ibatis/executor/result/DefaultMapResultHandler.java, src/main/java/org/apache/ibatis/executor/result/DefaultResultContext.java, src/main/java/org/apache/ibatis/executor/result/DefaultResultHandler.java, src/main/java/org/apache/ibatis/executor/resultset/DefaultResultSetHandler.java, src/main/java/org/apache/ibatis/session/ResultContext.java, src/main/java/org/apache/ibatis/session/ResultHandler.java, src/main/java/org/apache/ibatis/session/defaults/DefaultSqlSession.java
I think those type should be type aware,
but perhaps make other new type such as "TypedResultHandler" is better?
=> Make ResultHandler and ResultContext to generic type.

src/site/es/xdoc/java-api.xml, src/site/ja/xdoc/java-api.xml, src/site/ko/xdoc/java-api.xml, src/site/xdoc/java-api.xml, src/site/zh/xdoc/java-api.xml
correspond https://github.com/mybatis/mybatis-3/pull/352
=> Update documents of ResultHandler and ResultContext as generic type.

src/main/java/org/apache/ibatis/jdbc/ScriptRunner.java
With this, you can create triggers and stored procedures.
=> Added DELIMITER support in jdbc script runner

src/main/java/org/apache/ibatis/binding/MapperMethod.java, src/main/java/org/apache/ibatis/binding/MapperProxyFactory.java, src/main/java/org/apache/ibatis/binding/MapperRegistry.java
* Elimination of unnecessary loop
* Add final to immutable property
Please review.
=> Polish binding package classes

src/main/java/org/apache/ibatis/builder/xml/XMLIncludeTransformer.java, src/main/java/org/apache/ibatis/builder/xml/mybatis-3-mapper.dtd, src/site/xdoc/sqlmap-xml.xml, src/test/java/org/apache/ibatis/builder/PostMapper.xml, src/test/java/org/apache/ibatis/submitted/includes/CreateDB.sql, src/test/java/org/apache/ibatis/submitted/includes/IncludeTest.java, src/test/java/org/apache/ibatis/submitted/includes/Mapper.xml
This code changes implements static placeholders to be able to parametrize SQL fragments during parsing phase.
=> Issue 652 - Parametrized include

src/main/java/org/apache/ibatis/annotations/Flush.java, src/main/java/org/apache/ibatis/binding/MapperMethod.java, src/test/java/org/apache/ibatis/binding/BoundAuthorMapper.java, src/test/java/org/apache/ibatis/binding/FlushTest.java
(cherry picked from commit 56198b2aec73631b3fc0520405bc5a175c9e8c7a)
Note: Conflicts resolve by manually.
Conflicts:
src/test/java/org/apache/ibatis/binding/BoundAuthorMapper.java
Backport to 3.2.x.
Please review #356 .
=> [3.2.x] #356: Support flush statements via Mapper interface

src/main/java/org/apache/ibatis/jdbc/ScriptRunner.java
fix for using #355 with mybatis-migrations
MigrationReader does  line.replaceFirst("--\\s*//", "-- ");
so we need to be prepared for that
=> mybatis #355 PL/SQL is not fully suppported

src/main/java/org/apache/ibatis/executor/result/ResultMapException.java, src/main/java/org/apache/ibatis/executor/resultset/DefaultResultSetHandler.java, src/main/java/org/apache/ibatis/mapping/ParameterMapping.java, src/main/java/org/apache/ibatis/mapping/ResultMapping.java, src/main/java/org/apache/ibatis/reflection/factory/DefaultObjectFactory.java, src/main/java/org/apache/ibatis/scripting/defaults/DefaultParameterHandler.java, src/main/java/org/apache/ibatis/type/BaseTypeHandler.java, src/test/java/org/apache/ibatis/executor/resultset/DefaultResultSetHandlerTest.java, src/test/java/org/apache/ibatis/reflection/factory/DefaultObjectFactoryTest.java, src/test/java/org/apache/ibatis/reflection/factory/TestClass.java, src/test/java/org/apache/ibatis/scripting/defaults/DefaultParameterHandlerTest.java, src/test/java/org/apache/ibatis/type/UnknownTypeHandlerTest.java
Wrapped some SQL exceptions with more information about where the problem exists.  Too many times I get this exception "java.sql.SQLException: Invalid column name".. I'd end up putting breakpoints in the code to find out what column MyBatis was working on.
This code really makes debugging the issue so easy as all the context is in the exception.
=> Added better error reporting to help debug issues with mapper files

src/main/java/org/apache/ibatis/binding/MapperMethod.java
'mapperInterface' is Class type but the 'name' is String Type
=> Fix warning

src/site/es/xdoc/configuration.xml, src/site/ja/xdoc/configuration.xml, src/site/ko/xdoc/configuration.xml, src/site/xdoc/configuration.xml, src/site/zh/xdoc/configuration.xml
I've improve documentation for `defaultFetchSize`. 
Please check it.
**Note:**
* There may be wrong grammars and expressions because English is not good.
* Translation is Japanese only.
=> Add explanations for defaultFetchSize in documentation

src/main/java/org/apache/ibatis/binding/MapperMethod.java, src/main/java/org/apache/ibatis/cursor/defaults/DefaultCursor.java, src/test/java/org/apache/ibatis/submitted/cursor_nested/CreateDB.sql, src/test/java/org/apache/ibatis/submitted/cursor_nested/Mapper.xml, src/test/java/org/apache/ibatis/submitted/cursor_nested/mybatis-config.xml, src/test/java/org/apache/ibatis/submitted/cursor_simple/CreateDB.sql, src/test/java/org/apache/ibatis/submitted/cursor_simple/Mapper.xml, src/test/java/org/apache/ibatis/submitted/cursor_simple/mybatis-config.xml
* modify to use Cursor.class.isAssignableFrom(Class<?>)
* modfiy to use ExceptionFactory.wrapException(String,Exception)
* modify copyright year
Please review #437 polishing.
=> #437: Polishing some logics and comments

pom.xml
Before merging this in, this needs a slight discussion.  With cobertura being removed and site deploy changing, its important every mybatis module get the updates all at once.  Initially, I'm putting up the parent and mybatis-3.  Once these are approved as go forwards, I'll go through remainder and start merging them all at once.
Check out usage of 'mvn site:deploy' as done to the following to verify this is what is needed.
http://hazendaz.github.io/parent/
http://hazendaz.github.io/mybatis-3/
The above are on my fork.  The real PR will be targetted for mybatis gh-pages.
The steps to perform this are pretty simple.
'mvn site' will continue to build the site out and should be run before a deploy.  This is local only.
'mvn site:deploy' will deploy out to mybatis gh site pages.
In …
=> Remove cobertura and site deploy changes

src/main/java/org/apache/ibatis/binding/MapperMethod.java, src/main/java/org/apache/ibatis/cursor/defaults/DefaultCursor.java, src/test/java/org/apache/ibatis/submitted/cursor_nested/CreateDB.sql, src/test/java/org/apache/ibatis/submitted/cursor_nested/Mapper.xml, src/test/java/org/apache/ibatis/submitted/cursor_nested/mybatis-config.xml, src/test/java/org/apache/ibatis/submitted/cursor_simple/CreateDB.sql, src/test/java/org/apache/ibatis/submitted/cursor_simple/Mapper.xml, src/test/java/org/apache/ibatis/submitted/cursor_simple/mybatis-config.xml
=> Revert "#437: Polishing some logics and comments"

src/main/java/org/apache/ibatis/cursor/Cursor.java, src/main/java/org/apache/ibatis/cursor/CursorException.java, src/main/java/org/apache/ibatis/cursor/defaults/DefaultCursor.java, src/test/java/org/apache/ibatis/submitted/cursor_simple/CursorSimpleTest.java
Thanks to comments in https://github.com/mybatis/mybatis-3/pull/437, I've added some tests to make the implementation more robust.
I still have to work on the RowBound (ObjectBound ?) part. See https://github.com/mybatis/mybatis-3/pull/437#issuecomment-121395680
All feedback or thoughts are much appreciated.
Gullaume
=> Added more tests to enhance reliability of Cursor implementation

src/site/es/xdoc/configuration.xml, src/site/ja/xdoc/configuration.xml, src/site/ko/xdoc/configuration.xml, src/site/xdoc/configuration.xml, src/site/zh/xdoc/configuration.xml
(cherry picked from commit 53f459444b411a3b69d6c8a8d46332667b5a1379)
I've backported to 3.3.x. For details, refer to #436 .
=> [3.3.x] Change explanation of default proxyFactory in documentation (CGLIB -> JAVASSIST)

src/site/es/xdoc/configuration.xml, src/site/ja/xdoc/configuration.xml, src/site/ko/xdoc/configuration.xml, src/site/xdoc/configuration.xml, src/site/zh/xdoc/configuration.xml
(cherry picked from commit f1419125348aabb499602558de20742990285000)
I've backported to 3.3.x. For details, refer to #435 .
=> [3.3.x] Add explanations for defaultFetchSize in documentation

src/site/es/xdoc/java-api.xml, src/site/ja/xdoc/java-api.xml, src/site/ko/xdoc/java-api.xml, src/site/xdoc/java-api.xml, src/site/zh/xdoc/java-api.xml
(cherry picked from commit e556d1c32a3bbd19e0e9e38a51e041a61ca1c5b9)
I've backported to 3.3.x. For details, refer to #434 .
=> [3.3.x] Add explanations for SqlSession#flushStatements and @Flush in documentation

pom.xml
Adds all the missing standard types present in JDBC 4 / Java 6 (java.sql.Types.*) plus the Microsoft SQL Server 2008 DATETIMEOFFSET constant (microsoft.sql.Types.DATETIMEOFFSET). Note that a custom type handler is still required to fully utilize these new types.
If it's not too much trouble, I would love to see this backported into 3.2.x and 3.3.x. Mapper XML and custom TypeHandler implementations that reference the missing standard JDBC constants would then be compatible with all 3 versions. These existing pull requests should make it painless: [#466](https://github.com/mybatis/mybatis-3/pull/466), [#467](https://github.com/mybatis/mybatis-3/pull/467)
=> Add missing standard JDBC types and SQL Server DATETIMEOFFSET type

src/main/java/org/apache/ibatis/annotations/Arg.java, src/main/java/org/apache/ibatis/annotations/Result.java, src/main/java/org/apache/ibatis/annotations/TypeDiscriminator.java, src/main/java/org/apache/ibatis/builder/annotation/MapperAnnotationBuilder.java, src/test/java/org/apache/ibatis/submitted/enumtypehandler_on_annotation/CreateDB.sql, src/test/java/org/apache/ibatis/submitted/enumtypehandler_on_annotation/Employee.java, src/test/java/org/apache/ibatis/submitted/enumtypehandler_on_annotation/EnumTypeHandlerUsingAnnotationTest.java, src/test/java/org/apache/ibatis/submitted/enumtypehandler_on_annotation/Person.java, src/test/java/org/apache/ibatis/submitted/enumtypehandler_on_annotation/PersonMapper.java, src/test/java/org/apache/ibatis/submitted/enumtypehandler_on_annotation/mybatis-config.xml
=> Allow TypeHandler for Enum on annotation configuration #444

src/main/java/org/apache/ibatis/logging/jdbc/BaseJdbcLogger.java
With the reintroduction of the setNString, setNCharacterStream, and
setNClob the BaseJdbcLogger needs to be updated to recognize these and
emit them in the logging stream to be consistent with other character
types.
=> Correct logging of 'N' parameters

pom.xml, src/main/java/org/apache/ibatis/executor/keygen/Jdbc3KeyGenerator.java, src/test/java/org/apache/ibatis/executor/keygen/Country.java, src/test/java/org/apache/ibatis/executor/keygen/CountryMapper.java, src/test/java/org/apache/ibatis/executor/keygen/CountryMapper.xml, src/test/java/org/apache/ibatis/executor/keygen/Jdbc3KeyGeneratorTest.java, src/test/java/org/apache/ibatis/executor/keygen/MapperConfig.xml, src/test/java/org/apache/ibatis/executor/keygen/setupdb.txt
Support insert multiple rows and write-back id.
Multirow inserts
A SQL feature (since SQL-92) is the use of row value constructors to insert multiple rows at a time in a single SQL statement:
INSERT INTO tablename (column-a, [column-b, ...])
VALUES ('value-1a', ['value-1b', ...]),
('value-2a', ['value-2b', ...]),
...
This feature is supported by DB2, SQL Server (since version 10.0 - i.e. 2008), PostgreSQL (since version 8.2), MySQL, sqlite (since version 3.7.11) and H2.
More about insert see here:
http://en.wikipedia.org/wiki/Insert_(SQL)
More details of this pull request see here: #350
=> Support insert multiple rows and write-back id

src/site/ko/xdoc/sqlmap-xml.xml
It did not specify for level of cache. (local cache and 2nd cache)
typo(지원질) is fixed.
=> inappropriate translation

src/main/java/org/apache/ibatis/builder/xml/XMLConfigBuilder.java, src/main/java/org/apache/ibatis/executor/resultset/DefaultResultSetHandler.java, src/main/java/org/apache/ibatis/session/AutoMappingUnknownColumnBehavior.java, src/main/java/org/apache/ibatis/session/Configuration.java, src/test/java/log4j.properties, src/test/java/org/apache/ibatis/builder/CustomizedSettingsMapperConfig.xml, src/test/java/org/apache/ibatis/builder/XmlConfigBuilderTest.java, src/test/java/org/apache/ibatis/session/AutoMappingUnknownColumnBehaviorTest.java
I added a new option for specify the behavior when detects an unknown column (or unknown property type) of automatic mapping target.
Options are as follow:
* NONE : Do nothing (Default) -> Same with current implementation
* WARNING : Output warning log with detail
* FAILING : Fail mapping (throw `SqlSessionException` with detail)
I think this option is useful for detects a type mistake during development.
What do you think ?
=> Add new option for specify the behavior when detects an unknown column of automatic mapping target

src/main/java/org/apache/ibatis/type/BlobInputStreamTypeHandler.java, src/main/java/org/apache/ibatis/type/ClobReaderTypeHandler.java, src/main/java/org/apache/ibatis/type/TypeHandlerRegistry.java, src/test/java/org/apache/ibatis/type/BlobInputStreamTypeHandlerTest.java, src/test/java/org/apache/ibatis/type/BlobInputStreamTypeHandlerTest.sql, src/test/java/org/apache/ibatis/type/ClobReaderTypeHandlerTest.java, src/test/java/org/apache/ibatis/type/ClobReaderTypeHandlerTest.sql, src/test/java/org/apache/ibatis/type/jdbc.properties
I've added type handlers for `java.sql.Blob`/`java.io.InputStream` and `java.sql.Clob`/`java.io.Reader`.
These type handlers require a JDBC driver that implements method supported at JDBC 4.0.
Please review.
=> Support TypeHandler for Blob/InputStream and Clob/Reader using method supported at JDBC 4.0

src/main/java/org/apache/ibatis/executor/BaseExecutor.java, src/main/java/org/apache/ibatis/executor/BatchExecutor.java, src/main/java/org/apache/ibatis/executor/ReuseExecutor.java, src/main/java/org/apache/ibatis/executor/statement/BaseStatementHandler.java, src/main/java/org/apache/ibatis/executor/statement/StatementUtil.java, src/test/java/org/apache/ibatis/executor/statement/BaseStatementHandlerTest.java
I've applied transaction timeout mechanism to `BatchExecutor` and `ReuseExecutor`. (mybatis/spring#115)
Please review.
=> Support transaction timeout on BatchExecutor and ReuseExecutor mybatis/spring#115

src/main/java/org/apache/ibatis/datasource/pooled/PooledDataSource.java
The issue appears in the flowing case:
- if autoCommit = false
- poolPingEnabled = true and poolPingQuery is set
- number of connections in the pool = poolMaximumActiveConnections
- connection state.activeConnections.get(0) is bad, for example database was restarted.
Currently the following is happened:
we are trying to execute sql query (query1) with the new connection getting and have the following:
state.activeConnections.remove(oldestActiveConnection);
if (!oldestActiveConnection.getRealConnection().getAutoCommit()) {
oldestActiveConnection.getRealConnection().rollback();
} 
so the old connection is removed from the pool and we are trying to rollback it. But connection is bad and it throws an exception so method stops execution.   
The issue here: sql query (query1) execution will …
=> Bad connection issue if autoCommit = false

src/main/java/org/apache/ibatis/builder/annotation/ProviderSqlSource.java, src/test/java/org/apache/ibatis/submitted/sqlprovider/Mapper.java, src/test/java/org/apache/ibatis/submitted/sqlprovider/OurSqlBuilder.java, src/test/java/org/apache/ibatis/submitted/sqlprovider/SqlProviderTest.java
I've supported to allow multiple arguments at a SqlProvider method.
* Mapper method
```java
@SelectProvider(type = UserSqlBuilder.class, method = "buildGetUsersByName")
List<User> getUsersByName(
@Param("name") String name,
@Param("orderByColumn") String orderByColumn); // Multiple arguments
```
* SqlProvider method (Current style)
```java
public String buildGetUsersByName(Map<String, Object> params) { // Support Map only
final String name = String.class.cast(params.get("name"));
final String orderByColumn = String.class.cast(params.get("orderByColumn"));
return new SQL(){{
SELECT("*");
FROM("users");
if (name != null) {
WHERE("name like #{param1} || '%'");
}
ORDER_BY(orderByColumn);
}}.toString();
}
```
* SqlProvider method (New style)
```java
public String buildGetUsersByName( …
```
=> Allow multiple arguments at a Sql Provider method

src/main/java/org/apache/ibatis/type/TypeHandlerRegistry.java
I've supported type handlers for mybatis-typehandlers-jsr310 1.0.1.
* `YearTypeHandler`
* `MonthTypeHandler`
See https://github.com/mybatis/typehandlers-jsr310/pull/6.
=> Support typehandlers added by mybatis-typehandlers-jsr310 1.0.1

src/main/java/org/apache/ibatis/builder/xml/XMLConfigBuilder.java, src/main/java/org/apache/ibatis/session/Configuration.java
I've improved setter method on `Configuration`.
In this changes, `logImpl` and `vfsImpl` can export to the `spring-configuration-metadata.json` on `mybatis-spring-boot-autoconfigure`.
Please review.
=> Improve setter method on Configuration

src/main/java/org/apache/ibatis/cursor/defaults/DefaultCursor.java, src/test/java/org/apache/ibatis/submitted/cursor_nested/CursorNestedTest.java, src/test/java/org/apache/ibatis/submitted/cursor_simple/CreateDB.sql, src/test/java/org/apache/ibatis/submitted/cursor_simple/CursorSimpleTest.java
* Removes redundant isClosed() checks. This check is done by fetchNextObjectFromDatabase(). Having redundant checks leads to the bug describe in issue #660.
* Added more tests to check behaviors when using iterator.next() with or without a previous hasNext() call.
=> Fixes #660 : Can not fetch an object from Cursor when a RowBounds is used

src/test/java/org/apache/ibatis/submitted/complex_column/ComplexColumnTest.java, src/test/java/org/apache/ibatis/submitted/complex_column/Person.xml, src/test/java/org/apache/ibatis/submitted/complex_column/PersonMapper.java
I have modified the existing complex column test suite to add a failing test case that uses an association to a mapped statement that uses @Param annotations.  Other than the query being defined in the java interface and using @Param instead of being in the XML the test is the same as the existing scenarios.
=> Failing test case for nested select with @Param attributes

src/test/java/org/apache/ibatis/builder/CachedAuthorMapper.java, src/test/java/org/apache/ibatis/builder/CachedAuthorMapper.xml, src/test/java/org/apache/ibatis/builder/CustomLongTypeHandler.java, src/test/java/org/apache/ibatis/builder/CustomObjectWrapperFactory.java, src/test/java/org/apache/ibatis/builder/CustomStringTypeHandler.java, src/test/java/org/apache/ibatis/builder/CustomizedSettingsMapperConfig.xml, src/test/java/org/apache/ibatis/builder/ExampleObjectFactory.java, src/test/java/org/apache/ibatis/builder/MapperConfig.xml, src/test/java/org/apache/ibatis/builder/PropertiesUrlMapperConfig.xml, src/test/java/org/apache/ibatis/builder/XmlConfigBuilderTest.java, src/test/java/org/apache/ibatis/builder/jdbc.properties, src/test/java/org/apache/ibatis/builder/mapper/CustomMapper.java, src/test/java/org/apache/ibatis/builder/typehandler/CustomIntegerTypeHandler.java, src/test/java/org/apache/ibatis/domain/blog/mappers/NestedBlogMapper.java, src/test/java/org/apache/ibatis/session/SqlSessionTest.java
I've added tests for `XMLConfigBuilder`.
Please review.
=> Improve and add tests for XMLConfigBuilder

src/main/java/org/apache/ibatis/builder/xml/XMLConfigBuilder.java, src/main/java/org/apache/ibatis/builder/xml/mybatis-3-config.dtd, src/test/java/org/apache/ibatis/builder/CustomReflectorFactory.java, src/test/java/org/apache/ibatis/builder/CustomizedSettingsMapperConfig.xml, src/test/java/org/apache/ibatis/builder/XmlConfigBuilderTest.java
I've fixed #675.
Note that element name is changed to `reflectionFactory` from `reflectionFactory`.
Please review.
=> Allow customize a ReflectorFactory using mybatis configuration xml file #675

.gitignore, README.md
Some users have asked for latest so makes sense to make it easy to get to by adding a direct link.  This is done in generic way so we don't need to keep changing it later.
Upon further testing within eclipse, it became obvious that without setting up properties for derby, the root of the project is still used.  So added back gitignores with note as to why.
=> Add link to snapshot on readme and add back some gitignores for IDE junit tests

src/main/java/org/apache/ibatis/jdbc/AbstractSQL.java, src/test/java/org/apache/ibatis/jdbc/SQLTest.java
I've supported variable length argument on `SQL`'s methods.
I think these methods is useful and more safely.
Please review.
=> Allow variable length argument on SQL's methods

pom.xml, src/test/java/org/apache/ibatis/executor/resultset/DefaultResultSetHandlerTest.java, src/test/java/org/apache/ibatis/scripting/defaults/DefaultParameterHandlerTest.java
Please note that the anyString was changed to cast of (String) anyObject as unit tests started failing for both otherwise.  Not entirely sure why but this way it continues working and allows us to be on the maintained version of mockito (perpetual beta).
=> [test] Update mockito to 2.0.87-beta

src/site/es/xdoc/configuration.xml, src/site/ja/xdoc/configuration.xml, src/site/ko/xdoc/configuration.xml, src/site/xdoc/configuration.xml, src/site/zh/xdoc/configuration.xml
fix the defaultScriptingLanguage
from 
> org.apache.ibatis.scripting.xmltags.XMLDynamicLanguageDriver 
to
> org.apache.ibatis.scripting.xmltags.XMLLanguageDriver
the class  org.apache.ibatis.scripting.xmltags.XMLDynamicLanguageDriver  is not exist.
In the Class Configuration, we can set the method setDefaultScriptingLanguage(Class<?> driver)
the setDefaultScriptingLanguage is the class org.apache.ibatis.scripting.xmltags.XMLLanguageDriver.
```java
public void setDefaultScriptingLanguage(Class<?> driver) {                                                                                                                                                                            
if (driver == null) {
driver = XMLLanguageDriver.class;
} …
```
=> update the site doc .

src/main/java/org/apache/ibatis/executor/keygen/Jdbc3KeyGenerator.java, src/test/java/org/apache/ibatis/submitted/keygen/CountryMapper.java, src/test/java/org/apache/ibatis/submitted/keygen/CountryMapper.xml, src/test/java/org/apache/ibatis/submitted/keygen/Jdbc3KeyGeneratorTest.java
I've improved to raise a exception when property that specified at `keyProperty` is not found on `Jdbc3KeyGenerator`. This change is with reference to the implementation of `SelectKeyGenerator`.
Please review.
=> Raise a exception when keyProperty is not found

src/main/java/org/apache/ibatis/jdbc/AbstractSQL.java, src/test/java/org/apache/ibatis/jdbc/SQLTest.java
I've added methods for insert values.
* `INTO_COLUMNS(String... columns)`
* `INTO_VALUES(String... values)`
I wanted to add `COLUMNS(String ... columns)` and `VALUES(String... values)`. However, `VALUES(String... values)` is not compatibility for `VALUES(String columns, String values)`.
Please review.
#726
=> Allow variable length argument on SQL's methods. related with #726

src/main/java/org/apache/ibatis/builder/xml/XMLConfigBuilder.java, src/main/java/org/apache/ibatis/executor/resultset/DefaultResultSetHandler.java, src/main/java/org/apache/ibatis/session/Configuration.java, src/site/es/xdoc/configuration.xml, src/site/ja/xdoc/configuration.xml, src/site/ko/xdoc/configuration.xml, src/site/xdoc/configuration.xml, src/site/zh/xdoc/configuration.xml, src/test/java/org/apache/ibatis/submitted/empty_row/Child.java, src/test/java/org/apache/ibatis/submitted/empty_row/CreateDB.sql, src/test/java/org/apache/ibatis/submitted/empty_row/Mapper.java, src/test/java/org/apache/ibatis/submitted/empty_row/Mapper.xml, src/test/java/org/apache/ibatis/submitted/empty_row/Parent.java, src/test/java/org/apache/ibatis/submitted/empty_row/Pet.java, src/test/java/org/apache/ibatis/submitted/empty_row/ReturnInstanceForEmptyRowTest.java, src/test/java/org/apache/ibatis/submitted/empty_row/mybatis-config.xml
When a query returns a row with all columns being `null` (= an empty row), MyBatis returns `null` by default.
As per users requests, a new configuration option `returnInstanceForEmptyRow` is added to change this behavior.
With this option enabled, MyBatis returns an empty instance instead of `null` for an empty row.
Note that this option also generates an empty instance for nested results (i.e. `<collection />` and `<association />`) to meet a requirement like #420 .
To control this behavior individually, you may have to specify `notNullColumn`.
Please refer to the attached test cases for how it works and test your solutions with the latest 3.4.2-SNAPSHOT.
:small_blue_diamond: The existing option `callSettersOnNulls` is whether to call the property's setter method when the column value is …
=> New setting : return empty instance for an empty row (i.e. every column is NULL)

pom.xml
see https://github.com/jboss-javassist/javassist/commit/0e40ca2a33a9f01dd9ca813ef4b5dea60267fd09
```version 3.21 on October 4, 2016```
- JIRA JASSIST-244, 245, 248, 250, 255, 256, 259, 262.
- javassist.tools.Callback was modified to be Java 1.4 compatible. The parameter type of Callback#result() was changed.
- The algorithm for generating a stack-map table was modified to fix github issue ```#83```.
- A bug of ProxyFactory related to default methods was fixed. It is github issue ```#45```.
=> upgrade javassist version to 3.21.0-GA

src/main/java/org/apache/ibatis/builder/xml/XMLConfigBuilder.java, src/main/java/org/apache/ibatis/session/Configuration.java, src/site/es/xdoc/configuration.xml, src/site/ja/xdoc/configuration.xml, src/site/ko/xdoc/configuration.xml, src/site/xdoc/configuration.xml, src/site/zh/xdoc/configuration.xml, src/test/java/org/apache/ibatis/builder/CustomizedSettingsMapperConfig.xml, src/test/java/org/apache/ibatis/builder/XmlConfigBuilderTest.java
`aggressiveLazyLoading` is not useful in most use cases because setter invocation by MyBatis triggers it.
=> Change the default value of aggressiveLazyLoading to false.

src/main/java/org/apache/ibatis/executor/resultset/DefaultResultSetHandler.java, src/test/java/org/apache/ibatis/submitted/immutable_constructor/CreateDB.sql, src/test/java/org/apache/ibatis/submitted/immutable_constructor/ImmutablePOJO.java, src/test/java/org/apache/ibatis/submitted/immutable_constructor/ImmutablePOJOMapper.xml, src/test/java/org/apache/ibatis/submitted/immutable_constructor/ImmutablePOJOTest.java
I've fixed to set the `foundValues` to `true`, when a result object created by constructor mappings.
#830
=> Fix auto mapping using constructor args

src/main/java/org/apache/ibatis/binding/MapperMethod.java, src/test/java/org/apache/ibatis/submitted/array_result_type/ArrayResultTypeTest.java
=> fixes #555 suport primitive array resultType

src/main/java/org/apache/ibatis/annotations/CacheNamespace.java, src/main/java/org/apache/ibatis/annotations/Property.java, src/main/java/org/apache/ibatis/builder/annotation/MapperAnnotationBuilder.java, src/test/java/org/apache/ibatis/submitted/cache/CacheTest.java, src/test/java/org/apache/ibatis/submitted/cache/CustomCache.java, src/test/java/org/apache/ibatis/submitted/cache/CustomCacheMapper.java, src/test/java/org/apache/ibatis/submitted/cache/mybatis-config.xml, src/test/java/org/apache/ibatis/submitted/global_variables/BaseTest.java
I've allowed to inject property values to a custom cache implementation using annotation driven configuration.
In this changes, we can customize a custom cache implementation as follow:
```java
@CacheNamespace(implementation = CustomCache.class, properties = {
@Property(name = "stringValue", value = "bar")
,@Property(name = "integerValue", value = "99")
,@Property(name = "longValue", value = "9999")
})
public interface CustomCacheMapper {
// ...
}
```
```java
public class CustomCache implements Cache {
// ...
private String stringValue; // inject "bar"
private Integer integerValue; // inject 99
private long longValue; // inject 9999
public CustomCache(String id) {
this.id = id;
}
// setter/getter and implementation methods ..
}
```
And we can use placeholder as follow:
```xml
<properties> …
```
=> Add properties attribute at '@CacheNamespace'

src/site/es/xdoc/java-api.xml, src/site/ja/xdoc/java-api.xml, src/site/ko/xdoc/java-api.xml, src/site/xdoc/java-api.xml, src/site/zh/xdoc/java-api.xml
see title.  (related with #841)
=> Update reference document for '@Property'

src/main/java/org/apache/ibatis/annotations/Arg.java, src/main/java/org/apache/ibatis/annotations/Case.java, src/main/java/org/apache/ibatis/annotations/Many.java, src/main/java/org/apache/ibatis/annotations/One.java, src/main/java/org/apache/ibatis/annotations/Result.java, src/main/java/org/apache/ibatis/plugin/Signature.java, src/site/es/xdoc/java-api.xml, src/site/ja/xdoc/java-api.xml, src/site/ko/xdoc/java-api.xml, src/site/xdoc/java-api.xml, src/site/zh/xdoc/java-api.xml
I've removed  unnecessary target from following annotations.
* `@Arg`
* `@Case`
* `@Result`
* `@One`
* `@Many`
These annotations are used only at annotation attribute. Hence; annotation target should be specified to empty.
=> Remove unnecessary target from some annotations

src/main/java/org/apache/ibatis/annotations/CacheNamespaceRef.java, src/main/java/org/apache/ibatis/builder/annotation/MapperAnnotationBuilder.java, src/test/java/org/apache/ibatis/submitted/cache/CacheTest.java, src/test/java/org/apache/ibatis/submitted/cache/SpecialPersonMapper.java, src/test/java/org/apache/ibatis/submitted/cache/mybatis-config.xml
I've allowed to specify a namespace by name instead of by type.
In this changes, we can share a cache object by name as follow:
```java
Configuration configuration = new Configuration();
// ...
configuration.addCache(new PerpetualCache("masterCache"));
configuration.addMapper(CategoryMapper.class);
configuration.addMapper(ItemMapper.class);
// ...
SqlSessionFactory sqlSessionFactory = new SqlSessionFactoryBuilder().build(configuration);
```
```java
@CacheNamespaceRef(name = "masterCache")
public interface CategoryMapper {
// ...
}
@CacheNamespaceRef(name = "masterCache")
public interface ItemMapper {
// ...
}
```
=> Add name attribute at '@CacheNamespaceRef'

src/main/java/org/apache/ibatis/annotations/CacheNamespaceRef.java, src/site/es/xdoc/java-api.xml, src/site/ja/xdoc/java-api.xml, src/site/ko/xdoc/java-api.xml, src/site/xdoc/java-api.xml, src/site/zh/xdoc/java-api.xml
=> Update reference doc and javadoc for gh-842

src/main/java/org/apache/ibatis/type/TypeHandlerRegistry.java
In some scenarios, need to define a generic typehandler for some custom types, so typehandler can be search in a recursive manner,is very valuable.
=> TypeHandler support the recursive search.

src/main/java/org/apache/ibatis/executor/resultset/DefaultResultSetHandler.java, src/main/java/org/apache/ibatis/mapping/ResultMap.java, src/test/java/org/apache/ibatis/submitted/automapping/AutomappingTest.java, src/test/java/org/apache/ibatis/submitted/automapping/CreateDB.sql, src/test/java/org/apache/ibatis/submitted/automapping/Mapper.java, src/test/java/org/apache/ibatis/submitted/automapping/Mapper.xml, src/test/java/org/apache/ibatis/submitted/automapping/User.java
avoid unexpected automapping when a explicit mapped proerty has the same name as another column
=> avoid unexpected automapping 

src/test/java/org/apache/ibatis/reflection/MetaClassTest.java
Hello,
I open this pull request to specify the lines [174-179](https://github.com/mybatis/mybatis-3/blob/master/src/main/java/org/apache/ibatis/reflection/MetaClass.java#L174) in the ```buildProperty(String, StringBuilder)``` method of ```org.apache.ibatis.reflection.MetaClass```.
```java
String propertyName = reflector.findPropertyName(prop.getName());
if (propertyName != null) {
builder.append(propertyName);
builder.append(".");
MetaClass metaProp = metaClassForProperty(propertyName);
metaProp.buildProperty(prop.getChildren(), builder);
}
```
=> Improve test on MetaClass

pom.xml
fix gh-934
I've fixed report of versioneye.
See https://github.com/jkuhnert/ognl#release-notes---version-3114-3020.
The OGNL 3.2 has been released already, However version 3.2 is required Java 7. (Drop support Java 6)
=> Update to OGNL 3.1.14

src/main/java/org/apache/ibatis/type/TypeHandlerRegistry.java, src/test/java/org/apache/ibatis/type/TypeHandlerRegistryTest.java
It is common for multiple enums to have a common interface along with a corresponding type handler.
Until 3.4.2, to use this type handler, users had to list all the enum implementations in the `@MappedType` or `<typeHandlers />`.
This PR allows users to register the type handler against the common interface.
Please see the attached test case for how it works.
Cc-ing @gaohanghbut @liyuj @yxc023 @charlesluo2014 @Hubbitus @fengdh @Fayou @sskeater @jlkm2010
Thought you guys might be interested.
=> Allow registering a type handler for a common interface of enums.

src/main/java/org/apache/ibatis/type/TypeHandlerRegistry.java, src/test/java/org/apache/ibatis/type/TypeHandlerRegistryTest.java
See gh-947
In current implementation, there is case that can not detect a type handler related with interface when enum implements multiple interface. I've fixed this behavior.
**Note:**
And I've added asserts as follow:
* not found a type handler for interface
* found a type handler at super interface
@harawata Please review this.
=> Support enum that implements multiple interfaces

src/site/zh/xdoc/getting-started.xml
sqlSessionFactory = new SqlSessionFactoryBuilder().build(inputStream);
改为
SqlSessionFactory sqlSessionFactory = new SqlSessionFactoryBuilder().build(inputStream);
=> 补充第49行代码 sqlSessionFactory前面缺少的类型声明

src/site/zh/xdoc/getting-started.xml
也绝不能将 SqlSession 实例的引用放在任何类型的管理作用域中，比如 Serlvet 架构中的 HttpSession。serlvet   改成   servlet
也绝不能将 SqlSession 实例的引用放在任何类型的管理作用域中，比如 Servlet 架构中的 HttpSession。
=> 修正156行中的serlvet为servlet

src/main/java/org/apache/ibatis/builder/xml/XMLConfigBuilder.java, src/main/java/org/apache/ibatis/session/Configuration.java, src/main/java/org/apache/ibatis/type/TypeHandlerRegistry.java, src/site/es/xdoc/configuration.xml, src/site/ja/xdoc/configuration.xml, src/site/ko/xdoc/configuration.xml, src/site/xdoc/configuration.xml, src/site/zh/xdoc/configuration.xml, src/test/java/org/apache/ibatis/builder/CustomizedSettingsMapperConfig.xml, src/test/java/org/apache/ibatis/builder/XmlConfigBuilderTest.java
I've fixed gh-970.
WDYT for this fix ?
=> Allow to customize default typehandler for enum

src/main/java/org/apache/ibatis/type/TypeHandlerRegistry.java, src/test/java/org/apache/ibatis/submitted/enum_interface_type_handler/Color.java, src/test/java/org/apache/ibatis/submitted/enum_interface_type_handler/CreateDB.sql, src/test/java/org/apache/ibatis/submitted/enum_interface_type_handler/EnumInterfaceTypeHandlerTest.java, src/test/java/org/apache/ibatis/submitted/enum_interface_type_handler/HasValue.java, src/test/java/org/apache/ibatis/submitted/enum_interface_type_handler/HasValueEnumTypeHandler.java, src/test/java/org/apache/ibatis/submitted/enum_interface_type_handler/Mapper.java, src/test/java/org/apache/ibatis/submitted/enum_interface_type_handler/User.java, src/test/java/org/apache/ibatis/submitted/enum_interface_type_handler/mybatis-config.xml
PR #947 didn't work as expected. An enum type handler needs to take enum type as constructor argument.
=> Fixes incomplete PR #947.

pom.xml, src/main/java/org/apache/ibatis/reflection/Jdk.java, src/main/java/org/apache/ibatis/type/InstantTypeHandler.java, src/main/java/org/apache/ibatis/type/JapaneseDateTypeHandler.java, src/main/java/org/apache/ibatis/type/Java8TypeHandlersRegistrar.java, src/main/java/org/apache/ibatis/type/LocalDateTimeTypeHandler.java, src/main/java/org/apache/ibatis/type/LocalDateTypeHandler.java, src/main/java/org/apache/ibatis/type/LocalTimeTypeHandler.java, src/main/java/org/apache/ibatis/type/MonthTypeHandler.java, src/main/java/org/apache/ibatis/type/OffsetDateTimeTypeHandler.java, src/main/java/org/apache/ibatis/type/OffsetTimeTypeHandler.java, src/main/java/org/apache/ibatis/type/TypeHandlerRegistry.java, src/main/java/org/apache/ibatis/type/YearMonthTypeHandler.java, src/main/java/org/apache/ibatis/type/YearTypeHandler.java, src/main/java/org/apache/ibatis/type/ZonedDateTimeTypeHandler.java, src/test/java/org/apache/ibatis/type/usesjava8/InstantTypeHandlerTest.java, src/test/java/org/apache/ibatis/type/usesjava8/JapaneseDateTypeHandlerTest.java, src/test/java/org/apache/ibatis/type/usesjava8/Jsr310TypeHandlerRegistryTest.java, src/test/java/org/apache/ibatis/type/usesjava8/LocalDateTimeTypeHandlerTest.java, src/test/java/org/apache/ibatis/type/usesjava8/LocalDateTypeHandlerTest.java, src/test/java/org/apache/ibatis/type/usesjava8/LocalTimeTypeHandlerTest.java, src/test/java/org/apache/ibatis/type/usesjava8/MonthTypeHandlerTest.java, src/test/java/org/apache/ibatis/type/usesjava8/OffsetDateTimeTypeHandlerTest.java, src/test/java/org/apache/ibatis/type/usesjava8/OffsetTimeTypeHandlerTest.java, src/test/java/org/apache/ibatis/type/usesjava8/YearMonthTypeHandlerTest.java, src/test/java/org/apache/ibatis/type/usesjava8/YearTypeHandlerTest.java, src/test/java/org/apache/ibatis/type/usesjava8/ZonedDateTimeTypeHandlerTest.java
[typehandlers-jsr310](https://github.com/mybatis/typehandlers-jsr310) are for standard Java types and they belong to the core in the first place.
We didn't know how to include them in the core without breaking Java 6 compatibility, but we do now.
So I propose to merge them into the core.
It might be a little bit confusing at first, but I cannot think of any serious issue caused by this change.
Any thoughts?
Cc-ing: @emacarron @hazendaz @kazuki43zoo @trohovsky @raupachz
=> Merge typehandlers-jsr310 into the core.

src/main/java/org/apache/ibatis/builder/SqlSourceBuilder.java, src/test/java/org/apache/ibatis/binding/MapperMethodParamTest.java, src/test/java/org/apache/ibatis/binding/paramtest-schema.sql
I've fixed gh-1030.
In current implementation, mybatis use the field type of `ParamMap#size`(`HashMap#size`)  instead of method argument type.
=> Allow long type on size parameter when use multiple '@Param'

src/main/java/org/apache/ibatis/executor/resultset/DefaultResultSetHandler.java
fix   multipleResultsetSets  bug,when ((stmt.getMoreResults() or stmt.getUpdateCount()!=-1)  and  stmt.getResultSet()==null),will stop check the succedent resultsets and the succedent  resultsets will be lost.
=> fix #1035  multipleResultsetSets  bug

src/main/java/org/apache/ibatis/builder/annotation/MapperAnnotationBuilder.java, src/main/java/org/apache/ibatis/builder/annotation/ProviderContext.java, src/main/java/org/apache/ibatis/builder/annotation/ProviderSqlSource.java, src/site/es/xdoc/java-api.xml, src/site/ja/xdoc/java-api.xml, src/site/ko/xdoc/java-api.xml, src/site/xdoc/java-api.xml, src/site/zh/xdoc/java-api.xml, src/test/java/org/apache/ibatis/submitted/sqlprovider/BaseMapper.java, src/test/java/org/apache/ibatis/submitted/sqlprovider/CreateDB.sql, src/test/java/org/apache/ibatis/submitted/sqlprovider/Mapper.java, src/test/java/org/apache/ibatis/submitted/sqlprovider/OurSqlBuilder.java, src/test/java/org/apache/ibatis/submitted/sqlprovider/SqlProviderTest.java
Support accessing following types on sql provider method via ProviderContext .
* Type of mapper interface
* Method of mapper method
Fixes gh-1013
=> Support ProviderContext on sql provider method

src/main/java/org/apache/ibatis/parsing/GenericTokenParser.java
In current implementation, there is case that create unused character array.
I think better that convert to character array when open token found.
Please review.
=> Polish to avoid creating unused character array on GenericTokenParser

src/main/java/org/apache/ibatis/builder/annotation/ProviderSqlSource.java, src/test/java/org/apache/ibatis/submitted/sqlprovider/OurSqlBuilder.java, src/test/java/org/apache/ibatis/submitted/sqlprovider/mybatis-config.xml
=> Allow replacing configuration properties on ProviderSqlSource

src/main/java/org/apache/ibatis/cache/CacheKey.java, src/test/java/org/apache/ibatis/cache/CacheKeyTest.java
Test cases written around this to avoid this serious flaw in the future,
configured origin of scanning asking for transient to be added, added
comment about when this would actually fail serialization, and wrote
test for that as well.
=> [bugfix] Remove invalid marked transient on cacheKey as reported by sonarlint

src/main/java/org/apache/ibatis/io/VFS.java, src/test/java/org/apache/ibatis/io/VFSTest.java
I found that the implementation of singleton in `VFS`  may not be thread-safe.  In multi-thread environment, singleton should also ensure that there will be only one instance created for the caller.
I also add a unit test file for that to improve the correctness of the implementation, please check it.
=> singleton pattern should be thread safe in VFS

src/main/java/org/apache/ibatis/executor/BatchExecutor.java
=> In BatchExecutor, close each statement right after it is executed.

.travis.yml
I suggest using the Ubuntu trusty on Travis CI.
See https://docs.travis-ci.com/user/reference/trusty/#JVM-(Clojure%2C-Groovy%2C-Java%2C-Scala)-images .
I've added openjdk8 instead of oraclejdk7.
=> Support trusty on Travis CI

pom.xml, src/test/java/org/apache/ibatis/submitted/usesjava8/keycolumn/InsertTest.java, src/test/java/org/apache/ibatis/submitted/usesjava8/multiple_resultsets/MultipleResultTest.java, src/test/java/org/apache/ibatis/submitted/usesjava8/postgres_genkeys/PostgresGeneratedKeysTest.java, src/test/java/org/apache/ibatis/submitted/usesjava8/refcursor/RefCursorTest.java
=> Upgrade to postgresql-embedded 2.5

src/main/java/org/apache/ibatis/reflection/factory/DefaultObjectFactory.java, src/main/java/org/apache/ibatis/scripting/xmltags/XMLScriptBuilder.java, src/test/java/org/apache/ibatis/reflection/factory/DefaultObjectFactoryTest.java
https://github.com/mybatis/mybatis-3/blob/master/src/main/java/org/apache/ibatis/scripting/xmltags/XMLScriptBuilder.java
These handlers are thread-safe, so they do not need to be created every time。
Using a global Map instead of local variables
#1148
=> Avoid unnecessary object creation when parsing XML tags.

src/site/es/xdoc/java-api.xml, src/site/es/xdoc/sqlmap-xml.xml, src/site/ja/xdoc/java-api.xml, src/site/ja/xdoc/sqlmap-xml.xml, src/site/ko/xdoc/java-api.xml, src/site/ko/xdoc/sqlmap-xml.xml, src/site/xdoc/java-api.xml, src/site/xdoc/sqlmap-xml.xml, src/site/zh/xdoc/java-api.xml, src/site/zh/xdoc/sqlmap-xml.xml
#1157 Improve the documentation around <cache /> and @Cachenamespace to clarify that Java interfaces do not automatically pick up mapper cache regions.
=> Clarify how the <cache /> tag interacts with the Java API.

src/main/java/org/apache/ibatis/reflection/Reflector.java
Hi,
This pull request allow to workaround the java 9 illegal access warning generated by mybatis.
When mybatis search for existing methods on objects, it goes to the object hierarchy including the top java.lang.Object class.
As there is no point to go to the java.lang.Object class as it didn't contains any getter/setter, a trivial workaround is to skip this class.
I tested this approach and with this patch there is no more illegall access warning on Java 9.
Regards,
Loïc
=> fix(#1156): illegal reflective access on java 9

src/site/zh/xdoc/java-api.xml
Most of them are hard to read propably due to machine translation and some latest draft in English that haven't been translated. I deleted most of the unnecessary spaces because they break characters apart which is somehow unreadable.
=> Correct mistranslated Chinese in Java-API section

src/main/java/org/apache/ibatis/annotations/Options.java, src/main/java/org/apache/ibatis/builder/annotation/MapperAnnotationBuilder.java
Current implementation sets "id" as the default value of `keyProperty`.
But having default value makes it difficult to report helpful errors from Jdbc3KeyGenerator (see #782 and #902).
As it is possible that there are solutions relying on this default value, the target is set to 3.5.0.
=> Unset default value of keyProperty.

.mvn/wrapper/maven-wrapper.properties, .travis.yml, pom.xml, travis/install.sh
I've fixed #1207 .
Notes:
Following two artifacts could not upgrade to the latest version. Please see the xml's comment about reason. I will create new issues to fix it.
* log4j-core #1210 
* ognl #1211 
Thanks.
=> Drop support JDK 6 and 7 at build definitions

pom.xml, src/main/java/org/apache/ibatis/logging/log4j2/Log4j2AbstractLoggerImpl.java
=> Supports log4j 2.6+(2.11)

pom.xml, src/main/java/org/apache/ibatis/scripting/xmltags/OgnlCache.java, src/main/java/org/apache/ibatis/scripting/xmltags/OgnlMemberAccess.java
* Upgrade to ognl 3.2.6
* Add OgnlMemberAccess
* Avoid calling the deprecated method on OgnlCache
I've fixed #1211 
Note: I've applied changes of https://github.com/jkuhnert/ognl/issues/47.
=> Upgrade to ognl 3.2.x #1211

src/main/java/org/apache/ibatis/scripting/xmltags/OgnlCache.java, src/main/java/org/apache/ibatis/scripting/xmltags/OgnlClassResolver.java
=> Support concurrency on the OgnlClassResolver #1216

src/test/java/org/apache/ibatis/jdbc/ScriptRunnerTest.java
I've fixed #1230 on master(for 3.5).
=> Fix to refer the line separator from system property on ScriptRunnerTest #1230

src/main/java/org/apache/ibatis/executor/keygen/Jdbc3KeyGenerator.java, src/test/java/org/apache/ibatis/submitted/keygen/Jdbc3KeyGeneratorTest.java
As #1198 has been merged, we can fix #782 .
Related to #902 #1073.
=> Throw exception when keyProperty is not found.

src/main/java/org/apache/ibatis/annotations/Lang.java, src/main/java/org/apache/ibatis/builder/BaseBuilder.java, src/main/java/org/apache/ibatis/builder/MapperBuilderAssistant.java, src/main/java/org/apache/ibatis/builder/annotation/MapperAnnotationBuilder.java, src/main/java/org/apache/ibatis/builder/xml/XMLStatementBuilder.java, src/main/java/org/apache/ibatis/scripting/LanguageDriverRegistry.java, src/main/java/org/apache/ibatis/session/Configuration.java, src/test/java/org/apache/ibatis/scripting/LanguageDriverRegistryTest.java
I'll propose to support type-safe on `@Lang#value` (attribute for specifying a custom `LanguageDriver`).
WDYT?
=> Support type-safe on @Lang#value

src/main/java/org/apache/ibatis/binding/MapperMethod.java, src/main/java/org/apache/ibatis/binding/MapperProxy.java, src/main/java/org/apache/ibatis/builder/annotation/MapperAnnotationBuilder.java, src/main/java/org/apache/ibatis/mapping/ResultMap.java, src/main/java/org/apache/ibatis/reflection/Jdk.java, src/main/java/org/apache/ibatis/reflection/OptionalUtil.java, src/main/java/org/apache/ibatis/reflection/ParamNameResolver.java, src/main/java/org/apache/ibatis/reflection/ParamNameUtil.java, src/main/java/org/apache/ibatis/type/InstantTypeHandler.java, src/main/java/org/apache/ibatis/type/JapaneseDateTypeHandler.java, src/main/java/org/apache/ibatis/type/LocalDateTimeTypeHandler.java, src/main/java/org/apache/ibatis/type/LocalDateTypeHandler.java, src/main/java/org/apache/ibatis/type/LocalTimeTypeHandler.java, src/main/java/org/apache/ibatis/type/MonthTypeHandler.java, src/main/java/org/apache/ibatis/type/OffsetDateTimeTypeHandler.java, src/main/java/org/apache/ibatis/type/OffsetTimeTypeHandler.java, src/main/java/org/apache/ibatis/type/TypeHandlerRegistry.java, src/main/java/org/apache/ibatis/type/YearMonthTypeHandler.java, src/main/java/org/apache/ibatis/type/YearTypeHandler.java, src/main/java/org/apache/ibatis/type/ZonedDateTimeTypeHandler.java
Related with #1207 
Since 3.5.0, the mybatis will support Java 8+. Hence I've dropped special logics and annotation that indicates using java 8 and 7.
=> Drop special logics and annotation that indicates using java 8 and 7

src/site/es/xdoc/java-api.xml, src/site/ja/xdoc/java-api.xml, src/site/ko/xdoc/java-api.xml, src/site/xdoc/java-api.xml, src/site/zh/xdoc/java-api.xml
From the API documentation it was not clear that it is possible to use `selectCursor` to fetch data.
This PR fixes that omission.
=> Adds mention of selectCursor to java API documentation page.

src/main/java/org/apache/ibatis/executor/ErrorContext.java, src/test/java/org/apache/ibatis/binding/BindingTest.java, src/test/java/org/apache/ibatis/binding/BoundAuthorMapper.java, src/test/java/org/apache/ibatis/binding/BoundAuthorMapper.xml, src/test/java/org/apache/ibatis/executor/ErrorContextTest.java
This makes the error message slightly inaccurate when an error occurs in `<insert />` with `<selectKey order="BEFORE" />`.
=> ErrorContext#store() did not store the outer context correctly.

src/main/java/org/apache/ibatis/annotations/Arg.java, src/main/java/org/apache/ibatis/builder/annotation/MapperAnnotationBuilder.java, src/main/java/org/apache/ibatis/builder/xml/mybatis-3-mapper.dtd, src/main/java/org/apache/ibatis/executor/resultset/DefaultResultSetHandler.java, src/test/java/org/apache/ibatis/submitted/constructor_columnprefix/Article.java, src/test/java/org/apache/ibatis/submitted/constructor_columnprefix/Author.java, src/test/java/org/apache/ibatis/submitted/constructor_columnprefix/ConstructorColumnPrefixTest.java, src/test/java/org/apache/ibatis/submitted/constructor_columnprefix/CreateDB.sql, src/test/java/org/apache/ibatis/submitted/constructor_columnprefix/EntityKey.java, src/test/java/org/apache/ibatis/submitted/constructor_columnprefix/Mapper.java, src/test/java/org/apache/ibatis/submitted/constructor_columnprefix/Mapper.xml, src/test/java/org/apache/ibatis/submitted/constructor_columnprefix/mybatis-config.xml
It's used with `resultMap` (see the attached test).
```xml
<resultMap id="authorRM" type="Author">
<id property="id" column="id" />
<result property="name" column="name" />
</resultMap>
<resultMap id="articleRM" type="Article">
<constructor>
<idArg column="id" javaType="int" />
<arg column="name" javaType="string" />
<arg resultMap="authorRM" columnPrefix="author_" javaType="Author" />
<arg resultMap="authorRM" columnPrefix="coauthor_" javaType="Author" />
</constructor>
</resultMap>
```
This should fix #968 .
@kazuki43zoo , @h3adache ,
Please let me know if there is any concern.
=> Allow specifying `columnPrefix` in constructor mapping.

src/main/java/org/apache/ibatis/cursor/defaults/DefaultCursor.java, src/test/java/org/apache/ibatis/submitted/cursor_simple/CursorSimpleTest.java
Fixes #1297
I've fixed to throws the `IllegalStateException` on `Cursor.iterator` when a `Cursor` is already closed.
WDYT?
=> Add closed check at Cursor.iterator

src/main/java/org/apache/ibatis/reflection/MetaObject.java
in method setValue of MetaObject  ,  when prop.hasNext() already is true ，it is unnecessary to judge  prop.getChildren() != null.
=> avoid an unnecessary judgement

src/main/java/org/apache/ibatis/cursor/defaults/DefaultCursor.java, src/main/java/org/apache/ibatis/executor/resultset/DefaultResultSetHandler.java, src/test/java/org/apache/ibatis/cursor/defaults/DefaultCursorTest.java, src/test/java/org/apache/ibatis/executor/resultset/DefaultResultSetHandlerTest2.java, src/test/java/org/apache/ibatis/submitted/cursor_nested/CursorNestedTest.java, src/test/java/org/apache/ibatis/submitted/cursor_simple/CursorSimpleTest.java
This fixes two issues reported by DB2 users.
- DefaultCursor could invoke method of a closed ResultSet on DB2. #1345
- RowBounds with out-of-range offset causes SQLException on DB2. https://groups.google.com/d/msg/mybatis-user/21UM4I7gm48/CRJShn2iBgAJ
=> Support drivers that close ResultSet automatically when next() returns false.

src/main/java/org/apache/ibatis/reflection/Reflector.java, src/main/java/org/apache/ibatis/reflection/factory/DefaultObjectFactory.java, src/main/java/org/apache/ibatis/reflection/invoker/GetFieldInvoker.java, src/main/java/org/apache/ibatis/reflection/invoker/MethodInvoker.java, src/main/java/org/apache/ibatis/reflection/invoker/SetFieldInvoker.java, src/main/java/org/apache/ibatis/reflection/property/PropertyCopier.java
As a fix for #1156 .
I used retry-on-failure approach as [isAccessible()](https://docs.oracle.com/javase/9/docs/api/java/lang/reflect/AccessibleObject.html#isAccessible--) is useless (always returns `false` on the first call).
It would be appreciated if someone can test this with named modules.
=> Avoid unnecessary `setAccessible()` calls.

src/main/java/org/apache/ibatis/builder/annotation/MapperAnnotationBuilder.java, src/main/java/org/apache/ibatis/session/Configuration.java, src/test/java/org/apache/ibatis/submitted/resolution/CreateDB.sql, src/test/java/org/apache/ibatis/submitted/resolution/User.java, src/test/java/org/apache/ibatis/submitted/resolution/cachereffromxml/CacheRefFromXmlTest.java, src/test/java/org/apache/ibatis/submitted/resolution/cachereffromxml/UserMapper.java, src/test/java/org/apache/ibatis/submitted/resolution/cachereffromxml/UserMapper.xml, src/test/java/org/apache/ibatis/submitted/resolution/cachereffromxml/mybatis-config.xml, src/test/java/org/apache/ibatis/submitted/resolution/cacherefs/CacheRefsTest.java, src/test/java/org/apache/ibatis/submitted/resolution/cacherefs/MapperA.xml, src/test/java/org/apache/ibatis/submitted/resolution/cacherefs/MapperB.java, src/test/java/org/apache/ibatis/submitted/resolution/cacherefs/MapperB.xml, src/test/java/org/apache/ibatis/submitted/resolution/cacherefs/mybatis-config.xml, src/test/java/org/apache/ibatis/submitted/resolution/deepresultmap/DeepResultMapTest.java, src/test/java/org/apache/ibatis/submitted/resolution/deepresultmap/MapperA.java, src/test/java/org/apache/ibatis/submitted/resolution/deepresultmap/MapperA.xml, src/test/java/org/apache/ibatis/submitted/resolution/deepresultmap/MapperB.xml, src/test/java/org/apache/ibatis/submitted/resolution/deepresultmap/MapperC.xml, src/test/java/org/apache/ibatis/submitted/resolution/deepresultmap/MapperD.xml, src/test/java/org/apache/ibatis/submitted/resolution/deepresultmap/mybatis-config.xml, src/test/java/org/apache/ibatis/submitted/resolution/javamethods/JavaMethodsTest.java, src/test/java/org/apache/ibatis/submitted/resolution/javamethods/MapperA.java, src/test/java/org/apache/ibatis/submitted/resolution/javamethods/MapperA.xml, src/test/java/org/apache/ibatis/submitted/resolution/javamethods/MapperB.java, src/test/java/org/apache/ibatis/submitted/resolution/javamethods/MapperC.java, src/test/java/org/apache/ibatis/submitted/resolution/javamethods/mybatis-config.xml
Depending on the order of mappers being parsed, MyBatis cannot resolve mapper elements correctly.
This patch fixes the problems that have been reported and I could find.
=> Improve complex mapper element resolution

pom.xml
While this worked, it was not very intuitive in what it was doing since it checked negative condition.  While upgrading to full junit 5, I noticed that this stopped working like expected.  Travis was fine since I had not pushed there yet but my local simply ran all tests every time.  I was able to track it back to being what appears to be a defect with ~~junit 5~~ surefire not honering the parameter for exclude groups.  So at the very least, for sake of being extremely clear on what we are accomplishing here, I have made this a normal condition check.
For further insight in what runs, using 'mvn help:active-profiles' will show the following locally after this change.
```
The following profiles are active (subject to your own externals):
- jboss (source: external)
- sonar-remote (source: …
```
=> [tests] Rework travis detection for slow running tests for clarity [see notes]

src/main/java/org/apache/ibatis/type/OffsetTimeTypeHandler.java, src/test/java/org/apache/ibatis/submitted/timestamp_with_timezone/Mapper.java, src/test/java/org/apache/ibatis/submitted/timestamp_with_timezone/Record.java, src/test/java/org/apache/ibatis/submitted/timestamp_with_timezone/TimestampWithTimezoneTypeHandlerTest.java, src/test/java/org/apache/ibatis/type/OffsetTimeTypeHandlerTest.java
Related to #1081 and #1368 
Some DBs/drivers support storing and/or retrieving `java.sql.OffsetTime` in/from `TIMESTAMP WITH TIME ZONE` column via `PreparedStatement#setObject()`/`ResultSet#getObject()`.
The program that I used to test: https://gist.github.com/harawata/2d14ece14581089180da4708df0e074f
✅Supported
⚠️ Works, but caution is needed
❌Not supported (or does not work)
<table>
<thead>
<tr>
<th>DB</th>
<th>Driver</th>
<th>Column type</th>
<th>getObject</th>
<th>setObject</th>
</tr>
</thead>
<tbody>
<tr>
<td rowspan="2">HSQLDB 2.4.1</td>
<td rowspan="2">2.4.1</td>
<td>TIMESTAMP(9) WITH TIME ZONE</td>
<td>⚠️[1]</td>
<td>❌</td>
</tr>
<tr>
<td>TIME(9) WITH TIME ZONE</td>
<td>✅</td>
<td>✅</td>
</tr>
<tr>
<td rowspan="2">PostgreSQL 10.6</td>
<td rowspan="2">42.2.5</td>
<td>TIMESTAMP WITH …
=> OffsetTimeTypeHandler should use setObject(), getObject()

src/main/java/org/apache/ibatis/type/ZonedDateTimeTypeHandler.java, src/test/java/org/apache/ibatis/type/ZonedDateTimeTypeHandlerTest.java
Related to #1081
Only Oracle supports ZonedDateTime, I think.
See the JDBC test program for how it works : https://gist.github.com/harawata/2d14ece14581089180da4708df0e074f#file-zoneddatetimetest-java
It might be possible for other DBs to support ZonedDateTime with offset ZoneId, but it does not seem to be useful very much.
=> ZonedDateTimeTypeHandler should use setObject(), getObject()

src/main/java/org/apache/ibatis/io/ExternalResources.java
Eclipse is reporting that usage of 'getChannel' in the try with resources potentially prevents file from being closed.  Modify this so that the suspected memory leak goes away.
=> [ci] Fix suspected memory leak

src/main/java/org/apache/ibatis/builder/xml/XMLMapperBuilder.java, src/test/java/org/apache/ibatis/submitted/stringlist/StringListTest.java
`<collection />` does not have `resultType` attribute. Is it `javaType`?
=> Ambiguous collection type bug fix. Ref #364

src/main/java/org/apache/ibatis/type/TypeHandlerRegistry.java, src/test/java/org/apache/ibatis/submitted/enum_interface_type_handler/EnumInterfaceTypeHandlerTest.java, src/test/java/org/apache/ibatis/submitted/enum_interface_type_handler/XmlMapper.java, src/test/java/org/apache/ibatis/submitted/enum_interface_type_handler/XmlMapper.xml, src/test/java/org/apache/ibatis/submitted/enum_interface_type_handler/mybatis-config.xml, src/test/java/org/apache/ibatis/submitted/enum_with_method/CreateDB.sql, src/test/java/org/apache/ibatis/submitted/enum_with_method/Currency.java, src/test/java/org/apache/ibatis/submitted/enum_with_method/EnumWithMethodTest.java, src/test/java/org/apache/ibatis/submitted/enum_with_method/Mapper.java, src/test/java/org/apache/ibatis/submitted/enum_with_method/Mapper.xml, src/test/java/org/apache/ibatis/submitted/enum_with_method/User.java, src/test/java/org/apache/ibatis/submitted/enum_with_method/mybatis-config.xml
=> Support anonymous enum object that implement method

src/main/java/org/apache/ibatis/type/TypeHandlerRegistry.java
See #1484 .
I cannot test all variations, but the following columns are treated as `LONGVARCHAR` in JDBC and `PreparedStatement#setString()` and `ResultSet#getString()` works fine with them, so `StringTypeHandler` should work as well.
- Oracle : `LONG VARCHAR`
- MySQL : `MEDIUMTEXT`, `LONGTEXT`
- MariaDB : `LONGTEXT`
- SAP ASE : `CHAR(n)`,`VARCHAR(n)` (only when n≥256)
=> Map StringTypeHandler to LONGVARCHAR instead of ClobTypeHandler

src/main/java/org/apache/ibatis/annotations/DeleteProvider.java, src/main/java/org/apache/ibatis/annotations/InsertProvider.java, src/main/java/org/apache/ibatis/annotations/SelectProvider.java, src/main/java/org/apache/ibatis/annotations/UpdateProvider.java, src/main/java/org/apache/ibatis/builder/annotation/ProviderMethodResolver.java, src/main/java/org/apache/ibatis/builder/annotation/ProviderSqlSource.java, src/site/es/xdoc/java-api.xml, src/site/ja/xdoc/java-api.xml, src/site/ko/xdoc/java-api.xml, src/site/xdoc/java-api.xml, src/site/zh/xdoc/java-api.xml, src/test/java/org/apache/ibatis/submitted/sqlprovider/CreateDB.sql, src/test/java/org/apache/ibatis/submitted/sqlprovider/ProviderMethodResolutionTest.java
Fixes gh-1279
I've tried to fix gh-1279. In this change, a developer can omit the `method` attribute on SqlProvider annotation (such as `@SelectProvider`, etc...).
If the `method` attribute was omitted, the MyBatis try to resolve a target method as follow:
* If specified type is implements `ProviderMethodResolver` added by this PR, the MyBatis use a method that returned by it
* If cannot resolve by `ProviderMethodResolver`(= not implement or it was returned  `null`), the MyBatis will search a `resolveSql` method(= reserved fallback method) from specified type.
If cannot resolve a target method by above processing, the MyBatis throw a `BuilderException`.
**NOTE:**
For this change, I add the `ProviderMethodResolver` interface and default implementation. In default implementation, it return …
=> Allow omit a 'method' attribute on SqlProvider annotation

src/main/java/org/apache/ibatis/builder/annotation/ProviderContext.java, src/main/java/org/apache/ibatis/builder/annotation/ProviderSqlSource.java, src/site/es/xdoc/java-api.xml, src/site/ja/xdoc/java-api.xml, src/site/ko/xdoc/java-api.xml, src/site/xdoc/java-api.xml, src/site/zh/xdoc/java-api.xml, src/test/java/org/apache/ibatis/submitted/sqlprovider/SqlProviderTest.java, src/test/java/org/apache/ibatis/submitted/sqlprovider/mybatis-config.xml
I've supportted the `databaseId` at `ProviderContext`.
In this change, developers can support an SQL for multiple database using provider method.
This is equivalent to `_databaseId` of special variable for XML based mapper.
WDYT?
=> Support databaseId at ProviderContext

src/main/java/org/apache/ibatis/type/LocalDateTimeTypeHandler.java, src/main/java/org/apache/ibatis/type/LocalDateTypeHandler.java, src/main/java/org/apache/ibatis/type/LocalTimeTypeHandler.java, src/test/java/org/apache/ibatis/submitted/localtime/CreateDB.sql, src/test/java/org/apache/ibatis/submitted/localtime/LocalTimeTest.java, src/test/java/org/apache/ibatis/submitted/localtime/Mapper.java, src/test/java/org/apache/ibatis/submitted/localtime/Record.java, src/test/java/org/apache/ibatis/submitted/localtime/mybatis-config.xml, src/test/java/org/apache/ibatis/submitted/timezone_edge_case/CreateDB.sql, src/test/java/org/apache/ibatis/submitted/timezone_edge_case/Mapper.java, src/test/java/org/apache/ibatis/submitted/timezone_edge_case/Record.java, src/test/java/org/apache/ibatis/submitted/timezone_edge_case/TimezoneEdgeCaseTest.java, src/test/java/org/apache/ibatis/submitted/timezone_edge_case/mybatis-config.xml, src/test/java/org/apache/ibatis/type/LocalDateTimeTypeHandlerTest.java, src/test/java/org/apache/ibatis/type/LocalDateTypeHandlerTest.java, src/test/java/org/apache/ibatis/type/LocalTimeTypeHandlerTest.java
The follows other recent commits for OffsetDateTime & ZonedDateTime to defer to the driver’s JDBC 4.2 support for JSR 310 objects.
=> JDBC 4.2 for LocalTime, LocalDate & LocalDateTime

src/site/es/xdoc/java-api.xml, src/site/ja/xdoc/java-api.xml, src/site/ko/xdoc/java-api.xml, src/site/xdoc/java-api.xml, src/site/zh/xdoc/java-api.xml
While reading the "Java API" section, there were two things caught my attention:
1. There's a missing space in a signature of `openSession`:
```java
SqlSession openSession(ExecutorType execType,TransactionIsolationLevel level)
```
2. The ordering of "Statement Execution Methods" seems a little bit weird:
```
Introducing select methods without parameters
Introducing select method with cursor
An example of select method with cursor
Introducing return value of insert, update and delete methods
Method signatures of select methods without parameters (as well as insert, update and delete methods)
```
The last example is too far from its introduction, so I reordered them:
```
Introducing select methods without parameters
Introducing return value of insert, update and delete methods
Method …
```
=> Fix and improvement for docs

.travis.yml, pom.xml, src/test/java/org/apache/ibatis/submitted/cursor_simple/PostgresCursorTest.java, src/test/java/org/apache/ibatis/submitted/keycolumn/CreateDB.sql, src/test/java/org/apache/ibatis/submitted/keycolumn/InsertTest.java, src/test/java/org/apache/ibatis/submitted/multiple_resultsets/CreateDB.sql, src/test/java/org/apache/ibatis/submitted/multiple_resultsets/MultipleResultTest.java, src/test/java/org/apache/ibatis/submitted/postgres_genkeys/CreateDB.sql, src/test/java/org/apache/ibatis/submitted/postgres_genkeys/PostgresGeneratedKeysTest.java, src/test/java/org/apache/ibatis/submitted/refcursor/CreateDB.sql, src/test/java/org/apache/ibatis/submitted/refcursor/RefCursorTest.java, src/test/java/org/apache/ibatis/testcontainers/PgContainer.java, src/test/java/org/apache/ibatis/type/SqlxmlTypeHandlerTest.java, src/test/java/org/apache/ibatis/type/SqlxmlTypeHandlerTest.sql
postgresql-embedded is [no longer actively maintained](https://github.com/yandex-qatools/postgresql-embedded#note-this-project-is-not-being-actively-maintained-anymore) and it is recommended to migrate to [Testcontainers](https://www.testcontainers.org).
The tests that require PostgreSQL are still excluded from maven test by default.
To run them, execute `mvn verify -D"env.TRAVIS"`.
When running the tests in Eclipse on macOS Mojave, I got an error (the tests still passed, though).
> Cannot run program "docker-credential-osxkeychain": error=2, No such file or directory
<details>
<summary>Full stack trace</summary>
```
ERROR [main] - Could not start process:
java.io.IOException: Cannot run program "docker-credential-osxkeychain": error=2, No such file or directory
at …
```
=> Replace postgresql-embedded with Testcontainers

.editorconfig
See [here](https://editorconfig.org/) for usage.
=> Add `.editorconfig` to maintain consistent coding styles

src/main/java/org/apache/ibatis/datasource/pooled/PooledDataSource.java, src/main/java/org/apache/ibatis/datasource/unpooled/UnpooledDataSource.java, src/site/es/xdoc/configuration.xml, src/site/ja/xdoc/configuration.xml, src/site/ko/xdoc/configuration.xml, src/site/xdoc/configuration.xml, src/site/zh/xdoc/configuration.xml, src/test/java/org/apache/ibatis/datasource/unpooled/NetworkTimeoutTest.java
Fixes #1527 .
As it calls `java.sql.Connection#setNetworkTimeout()` internally, setting this property requires a driver supporting JDBC 4.1.
=> Add 'defaultNetworkTimeout' to PooledDataSource and UnpooledDataSource

src/test/java/org/apache/ibatis/executor/loader/CglibProxyTest.java, src/test/java/org/apache/ibatis/executor/loader/JavassistProxyTest.java, src/test/java/org/apache/ibatis/executor/loader/SerializableProxyTest.java
Issue reported via research project by Anthony Peruma questioning usage of constructor.  This has been modified to use beforeAll annotation and made static.
=> [tests] Replace constructor in proxy test with static before all

src/main/java/org/apache/ibatis/scripting/xmltags/DynamicContext.java, src/test/java/org/apache/ibatis/submitted/dynsql/DynSqlMapper.java, src/test/java/org/apache/ibatis/submitted/dynsql/DynSqlMapper.xml, src/test/java/org/apache/ibatis/submitted/dynsql/DynSqlTest.java
Fixes gh-1486
I've allowed to access a parameter object(value object) using any variable name on OGNL expression  such as same with bind variable name. 
In this change, it allow specify as follow:
```java
public interface DemoMapper {
List<String> selectNameByCategory(Integer category);
}
``` 
```xml
<mapper namespace="...">
<select id="selectNameByCategory" resultType="string">
SELECT name FROM products
<if test="category != null">
WHERE id = #{category}
</if>
</select>
</mapper>
```
**NOTE:**
In version 3.5.0, `#{category}`(in bind variable) is valid but `category != null`(in OGNL expression) is invalid.
=> Allow any variable name on ognl expression when specify single value object as parameter object

src/main/java/org/apache/ibatis/jdbc/AbstractSQL.java, src/site/es/xdoc/statement-builders.xml, src/site/ja/xdoc/statement-builders.xml, src/site/ko/xdoc/statement-builders.xml, src/site/xdoc/statement-builders.xml, src/site/zh/xdoc/statement-builders.xml, src/test/java/org/apache/ibatis/jdbc/SQLTest.java
=> Support LIMIT and OFFSET on SQL class

.travis.yml
I will suggest to replace to use the `openjdk11` instead of `oraclejdk11` on Travis CI.
This PR will fix build error (https://travis-ci.community/t/cannot-install-oracle-jdk-11/3892).
=> Replace to openjdk11 from oraclejdk11

src/main/java/org/apache/ibatis/type/TypeHandlerRegistry.java
I've modified the code to not call the reflection feature.
=> Avoid registration of built-in typehandler using reflection

src/main/java/org/apache/ibatis/cache/Cache.java, src/main/java/org/apache/ibatis/cache/decorators/BlockingCache.java, src/main/java/org/apache/ibatis/cache/decorators/FifoCache.java, src/main/java/org/apache/ibatis/cache/decorators/LoggingCache.java, src/main/java/org/apache/ibatis/cache/decorators/LruCache.java, src/main/java/org/apache/ibatis/cache/decorators/ScheduledCache.java, src/main/java/org/apache/ibatis/cache/decorators/SerializedCache.java, src/main/java/org/apache/ibatis/cache/decorators/SoftCache.java, src/main/java/org/apache/ibatis/cache/decorators/SynchronizedCache.java, src/main/java/org/apache/ibatis/cache/decorators/TransactionalCache.java, src/main/java/org/apache/ibatis/cache/decorators/WeakCache.java, src/main/java/org/apache/ibatis/cache/impl/PerpetualCache.java, src/main/java/org/apache/ibatis/executor/loader/ProxyFactory.java, src/main/java/org/apache/ibatis/executor/loader/cglib/CglibProxyFactory.java, src/main/java/org/apache/ibatis/executor/loader/javassist/JavassistProxyFactory.java, src/main/java/org/apache/ibatis/mapping/DatabaseIdProvider.java, src/main/java/org/apache/ibatis/plugin/Interceptor.java, src/main/java/org/apache/ibatis/reflection/factory/DefaultObjectFactory.java, src/main/java/org/apache/ibatis/reflection/factory/ObjectFactory.java, src/main/java/org/apache/ibatis/transaction/TransactionFactory.java, src/main/java/org/apache/ibatis/transaction/jdbc/JdbcTransactionFactory.java, src/site/es/xdoc/configuration.xml, src/site/ja/xdoc/configuration.xml, src/site/ko/xdoc/configuration.xml, src/site/xdoc/configuration.xml, src/site/zh/xdoc/configuration.xml, src/test/java/org/apache/ibatis/plugin/PluginTest.java, src/test/java/org/apache/ibatis/submitted/custom_collection_handling/CustomObjectFactory.java
I will propose to support default method on following interface method:
* `Cache#getReadWriteLock`
* ~~`DataSourceFactory#setProperties`~~
* ~~`KeyGenerator#processBefore`~~
* ~~`KeyGenerator#processAfter`~~
* `ProxyFactory#setProperties`
* `DatabaseIdProvider#setProperties`
* `Interceptor#plugin`
* `Interceptor#setProperties`
* `ObjectFactory#setProperties`
* ~~`Transaction#getTimeout`~~
* `TransactionFactory#setProperties`
As apply this changes, source code becomes a little slim.
Adding as follows: (2018-04-11)
* ~~`SqlSession#*`~~
* ~~`SqlSessionFactory#*`~~
Fix conflict as follows: (2018-06-23)
* ~~`DefaultSqlSession`~~
WDYT?
=> Support default method

src/main/java/org/apache/ibatis/annotations/DeleteProvider.java, src/main/java/org/apache/ibatis/annotations/InsertProvider.java, src/main/java/org/apache/ibatis/annotations/SelectProvider.java, src/main/java/org/apache/ibatis/annotations/UpdateProvider.java, src/main/java/org/apache/ibatis/builder/annotation/ProviderSqlSource.java, src/site/es/xdoc/java-api.xml, src/site/ja/xdoc/java-api.xml, src/site/ko/xdoc/java-api.xml, src/site/xdoc/java-api.xml, src/site/zh/xdoc/java-api.xml, src/test/java/org/apache/ibatis/submitted/sqlprovider/ProviderMethodResolutionTest.java, src/test/java/org/apache/ibatis/submitted/sqlprovider/SqlProviderTest.java
I propose to support the `value` attributes on provider annotations(such as `@InsertProvider`). In this change, developer can omit the `type` attribute as follow:
```java
// @InsertProvider(type = InsertSqlProvider.class)  // until 3.5.1
@InsertProvider(InsertSqlProvider.class)
void insert(Name name);
```
The`type` attribute can use the alias for `value` attribute. This change related with gh-1279. The gh-1279 allow to omit `method` attribute, therefore this change is effective.
WDYT?
=> Add value attribute on provider annotations

src/main/java/org/apache/ibatis/builder/annotation/ProviderSqlSource.java, src/test/java/org/apache/ibatis/submitted/sqlprovider/Mapper.java, src/test/java/org/apache/ibatis/submitted/sqlprovider/OurSqlBuilder.java, src/test/java/org/apache/ibatis/submitted/sqlprovider/SqlProviderTest.java
Current implementation cannot use primitive type on SQL provider method. For details, see gh-1595. 
I've fixed gh-1595 using based on solution that suggested by @harawata (See https://github.com/mybatis/mybatis-3/pull/1595#issuecomment-509443667), however I've changed some implementations from suggested implementation by @harawata  for keeping backward compatibility with 3.5.1 as follows:
* target type for `instanceof` (`ParamMap` -> `Map`) 
* support to use together with `ProviderContext` and `Map`
@harawata WDYT?
=>  Support to assign single primitive parameter on SQL provider method

src/main/java/org/apache/ibatis/builder/annotation/ProviderSqlSource.java, src/test/java/org/apache/ibatis/submitted/sqlprovider/SqlProviderTest.java
I've fixed backward compatibility with 3.5.1 by gh-1604.
* Allow to specify the `ProviderContext` at any position together with `Map` parameter as follow:
```java
public String provideSql(Map<String, Object> parameters, ProviderContext context) { // Work fine on gh-1604
// ...
}
public String provideSql(ProviderContext context, Map<String, Object> parameters) { // Broken by gh-1604
// ...
}
``` 
* Allow to specify the actual class(e.g. `ParamMap`) instead of interface(`Map`) as follow:
```java
public String provideSql(ParamMap<Object> parameters) { // Broken by gh-1604
// ...
}
```
=> Fix broken backward compatibility by gh-1604

src/main/java/org/apache/ibatis/builder/annotation/ProviderSqlSource.java, src/test/java/org/apache/ibatis/submitted/sqlprovider/SqlProviderTest.java
The motivation for this change is to resolve issues that prevent GraalVM support. See gh-1552
I want to resolve issues that prevent GraalVM support on step by step.
WDYT?
=> Add constructor that pass an Annotation type instead of Object on ProviderSqlSource

src/main/java/org/apache/ibatis/builder/xml/XMLIncludeTransformer.java, src/test/java/org/apache/ibatis/submitted/include_property/Mapper.xml
=> Support variable substitution in CDATA of included `<sql />`

src/main/java/org/apache/ibatis/builder/annotation/ProviderSqlSource.java, src/test/java/org/apache/ibatis/submitted/sqlprovider/SqlProviderTest.java
=> Prevent infinite loop when throw Exception that hold cause from provider method

src/main/java/org/apache/ibatis/binding/MapperProxy.java
The constructor 
`java.lang.invoke.MethodHandles.Lookup.Lookup(Class<?>, int)`
was replaced with
`java.lang.invoke.MethodHandles.Lookup.Lookup(Class<?>, Class<?>, int)`
https://hg.openjdk.java.net/jdk/jdk/rev/f557f260b787?revcount=1000
https://bugs.openjdk.java.net/browse/JDK-8173978
https://mail.openjdk.java.net/pipermail/core-libs-dev/2019-July/061132.html
=> Updated default method invocation to support JDK 14+8

.travis.yml
openjdk-ea now points to 14, it seems.
=> Add openjdk13 to .travis.yml

src/main/java/org/apache/ibatis/reflection/Reflector.java, src/main/java/org/apache/ibatis/reflection/invoker/AmbiguousMethodInvoker.java, src/test/java/org/apache/ibatis/reflection/ReflectorTest.java
Lower impact fix for #1201 ,
Unlike #1335 , this version throws exception only when the ambiguous setter/getter is actually invoked.
=> Ambiguous setters/getters should throw exception only when they are invoked

src/test/java/org/apache/ibatis/autoconstructor/AutoConstructorMapper.java, src/test/java/org/apache/ibatis/autoconstructor/AutoConstructorTest.java
In interface org.apache.ibatis.autoconstructor.AutoConstructorMapper: method getExtensiveSubject should be renamed to getExtensiveSubjects
=> name conventions: getExtensiveSubject to getExtensiveSubjects

src/main/java/org/apache/ibatis/cursor/defaults/DefaultCursor.java, src/test/java/org/apache/ibatis/submitted/cursor_simple/CursorSimpleTest.java, src/test/java/org/apache/ibatis/submitted/cursor_simple/Mapper.java
This should fix #1653 
Cc-ing @gdarmont ,
Please let me know if you noticed any potential issue (even after I merged this PR).
Thanks!
=> Prevent null element from stopping cursor iteration

.travis.yml
Fix build error on latest travis CI env.
See https://travis-ci.org/mybatis/mybatis-3/builds/594954100
=> Replace to openjdk8

src/main/java/org/apache/ibatis/executor/keygen/Jdbc3KeyGenerator.java, src/main/java/org/apache/ibatis/reflection/ParamNameResolver.java, src/test/java/org/apache/ibatis/submitted/keygen/CountryMapper.java, src/test/java/org/apache/ibatis/submitted/keygen/CountryMapper.xml, src/test/java/org/apache/ibatis/submitted/keygen/Jdbc3KeyGeneratorTest.java, src/test/java/org/apache/ibatis/submitted/keygen/NpeCountry.java
When detecting single parameter case, it now checks parameter name instead of equality of the parameter objects.
This should fix gh-1719.
A caveat : when there is only one parameter and its name is 'param2' (for whatever reason), `keyProperty` must include the parameter name i.e. `keyProperty="param2.xx"`.
=> Avoid invoking equals/hashCode when assigning generated keys

src/main/java/org/apache/ibatis/binding/MapperProxy.java, src/main/java/org/apache/ibatis/binding/MapperProxyFactory.java, src/test/java/org/apache/ibatis/binding/BindingTest.java
A fix for #1754 .
I decided to use the same cache for both default and non-default methods.
To achieve it, a new package private interface `MapperMethodInvoker` is added.
There is a method `MapperProxyFactory#getMethodCache()` which exposes the cache [1], so users who use this method might be affected by this change.
[1] I think this getter and `getMapperInterface()` were added only for this [test](https://github.com/mybatis/mybatis-3/blob/67a1c4ea57/src/test/java/org/apache/ibatis/binding/BindingTest.java#L541). Related commits: 0c3c272c50fd84c5000c0ae8fc798b58daf5439a a5a5d9690e92294720e5fdd8ed1d930af5f2cd3c
@kazuki43zoo ,
Could you review this when you have time, please?
=> Reuse MethodHandle for default methods

src/main/java/org/apache/ibatis/reflection/ParamNameResolver.java
* Optimize the code inline 122 of `ParamNameResolver.java`. The method `String.valueOf` is unnecessary and can be deleted.
=> refactor: optimize the code in ParamNameResolver.java

src/main/java/org/apache/ibatis/jdbc/ScriptRunner.java, src/main/java/org/apache/ibatis/jdbc/SqlRunner.java
Because the Runners are not responsible to close the connection.
=> made closeConnection in the Runner classes deprecated

src/main/java/org/apache/ibatis/builder/xml/XMLMapperBuilder.java, src/main/java/org/apache/ibatis/parsing/XNode.java, src/test/java/org/apache/ibatis/submitted/orphan_result_maps/Blog.java, src/test/java/org/apache/ibatis/submitted/orphan_result_maps/NestedCollectionMapper.java, src/test/java/org/apache/ibatis/submitted/orphan_result_maps/NestedCollectionMapper.xml, src/test/java/org/apache/ibatis/submitted/orphan_result_maps/OrphanResultMapTest.java, src/test/java/org/apache/ibatis/submitted/orphan_result_maps/Post.java, src/test/java/org/apache/ibatis/submitted/orphan_result_maps/SeparateCollectionMapper.java, src/test/java/org/apache/ibatis/submitted/orphan_result_maps/SeparateCollectionMapper.xml
When referencing id of another `resultMap` in association/collection, unessesery ResultMap is created and stored in configuration. For example:
1. When using nested collection:
```xml 
<resultMap id="BlogResultMap" type="Blog">
<constructor>
<idArg column="blog_id" name="id"/>
<arg column="blog_title" name="title"/>
</constructor>
<collection property="posts" ofType="Post">
<constructor>
<idArg column="post_id" name="id"/>
<arg column="post_body" name="body"/>
</constructor>
</collection>
</resultMap>
```
Two ResultMaps are added to configuration:
- `BlogResultMap` based on provided id of resultMap
- `mapper_resultMap[BlogResultMap]_collection[posts]` for nested unnamed resultMap
This works as expected so far.
2. When referencing collection by id (different approach to map same result): …
=> Avoid creating unused result map when parsing collection/association

src/main/java/org/apache/ibatis/scripting/xmltags/OgnlMemberAccess.java, src/test/java/org/apache/ibatis/scripting/xmltags/OgnlCacheTest.java
Once a field is made accessible, we keep it accessible.
Flipping accessible flag causes a race condition.
Possibly related to #1648 .
=> Avoid flipping accessible flag in OgnlMemberAccess

src/main/java/org/apache/ibatis/jdbc/ScriptRunner.java
String#replace does not use a regular expression for the replacement on Java 9+ and is therefore faster.
=> Use String#replace instead of String#replaceAll.

src/test/java/org/apache/ibatis/reflection/ReflectorTest.java
`reflector.getSetterType` in `ReflectorTest` can return `String`, `Integer`, and `boolean` these three type. However the test `assertTrue` includes two types. So, the test can fail when `reflector.getSetterType` return `boolean`.
This PR proposes to add test a condition so that the test is deterministic.
=> Make tests more stable by adding a test condition

src/main/java/org/apache/ibatis/executor/ErrorContext.java
Use ThreadLocal.withInitial to lazy lazily init ThreadLocal.
This makes the code more concise, and is no different from the original code logic.
Hope to consider merging this PR.
=> Use ThreadLocal.withInitial to lazily init ThreadLocal

src/main/java/org/apache/ibatis/reflection/ParamNameResolver.java, src/main/java/org/apache/ibatis/session/defaults/DefaultSqlSession.java, src/test/java/org/apache/ibatis/submitted/param_name_resolve/ActualParamNameTest.java, src/test/java/org/apache/ibatis/submitted/param_name_resolve/CreateDB.sql, src/test/java/org/apache/ibatis/submitted/param_name_resolve/NoActualParamNameTest.java, src/test/java/org/apache/ibatis/submitted/param_name_resolve/mybatis-config.xml
Fixes gh-1237
I've made available access to a single collection and array as bind parameter using actual parameter name.
=> Allow using actual argument name as bind parameter on a single collection

src/test/java/org/apache/ibatis/submitted/cachenamespaceref_exception/BusinessDao.java, src/test/java/org/apache/ibatis/submitted/cachenamespaceref_exception/CacheNamespaceRefTest.java, src/test/java/org/apache/ibatis/submitted/cachenamespaceref_exception/CreateDB.sql, src/test/java/org/apache/ibatis/submitted/cachenamespaceref_exception/Mapper.java, src/test/java/org/apache/ibatis/submitted/cachenamespaceref_exception/Mapper.xml, src/test/java/org/apache/ibatis/submitted/cachenamespaceref_exception/User.java, src/test/java/org/apache/ibatis/submitted/cachenamespaceref_exception/mybatis-config.xml
When mapper annotated with @CacheNamespaceRef is parsed before the one where the refered cache is defined, an unreasonable IllegalArgumentException is throw.I debuged and found that this is because when parse the mapper with unresolvedCacheRef,the method is add to incompleteMethods to resolve it later, but the default resultMap is already added to Configuration.resultMaps by MapperAnnotationBuilder.applyResultMap,when resolve the incompleteMethod later, it try to add the same resultMap,this causes IllegalArgumentException.
I think this maybe a bug and create this unit test to reproduce it.
=> unit test for cachenamespaceref

src/site/zh/xdoc/sqlmap-xml.xml
There seems to be a redundant Chinese character '的' which was deleted by me.(shown in the following pic)
Search "的的" [here](https://mybatis.org/mybatis-3/zh/sqlmap-xml.html), and you will see it. (shown in the following pic)
=> remove a redundant Chinese character '的'

src/main/java/org/apache/ibatis/binding/MapperProxy.java
https://bugs.openjdk.java.net/browse/JDK-8161372
Should be reverted once the fix is backported or MyBatis drops Java 8 support.
Should fix #1929
=> A temporary workaround for Java 8 specific ConcurrentHashMap issue JDK-8161372

src/main/java/org/apache/ibatis/builder/annotation/ProviderSqlSource.java, src/main/java/org/apache/ibatis/builder/xml/XMLConfigBuilder.java, src/main/java/org/apache/ibatis/session/Configuration.java, src/site/es/xdoc/configuration.xml, src/site/es/xdoc/java-api.xml, src/site/ja/xdoc/configuration.xml, src/site/ja/xdoc/java-api.xml, src/site/ko/xdoc/configuration.xml, src/site/ko/xdoc/java-api.xml, src/site/xdoc/configuration.xml, src/site/xdoc/java-api.xml, src/site/zh/xdoc/configuration.xml, src/site/zh/xdoc/java-api.xml, src/test/java/org/apache/ibatis/builder/CustomizedSettingsMapperConfig.xml, src/test/java/org/apache/ibatis/builder/XmlConfigBuilderTest.java, src/test/java/org/apache/ibatis/submitted/sqlprovider/SqlProviderTest.java
I propose to support a global configuration for applying sql provider type when omit `type` attribute on sql provider annotation(such as `@SelectProvider`, etc).
We has been supported the mechanism that use a shared sql provider class on all mapper methods, however developer need to specify explicitly the type on all mapper methods as follow:
**mapper methods (on current version):**
```java
public interface MyMapper {
@SelectProvider(SharedSqlProvider.class)
String select(int id);
@UpdateProvider(SharedSqlProvider.class)
void insert(String name);
@UpdateProvider(SharedSqlProvider.class)
void update(int id, String name);
@DeleteProvider(SharedSqlProvider.class)
void delete(int id);
}
```
There is case that  I feel it's redundant. As this changes, developer can be omit the type attribute on …
=> Support global configuration for applying sql provider type when omit on annotation

src/main/java/org/apache/ibatis/session/TransactionIsolationLevel.java
Sql Server supports a non-standard transaction isolation level called "SNAPSHOT" whose JDBC value is 0x1000 (4096). The new enum value adds support for this isolation level.
The name "SQL_SERVER_SNAPSHOT" was chosen to reflect the fact that it is unique to SQL Server to avoid confusion. See #1969
=> Added SQL_SERVER_SNAPSHOT value to TransactionIsolationLevel enum

src/main/java/org/apache/ibatis/io/DefaultVFS.java
The method getPackagePath exists in two classes, one is in DefaultVFS.java, the other one is in ResolverUtil.java. And they are identical. Delete that in DefaultVFS.java.
=> Optimization code

src/site/es/xdoc/logging.xml, src/site/ja/xdoc/logging.xml, src/site/ko/xdoc/logging.xml, src/site/xdoc/logging.xml, src/site/zh/xdoc/logging.xml
the link in logging.xml document for [JDK Logging API](http://java.sun.com/j2se/1.4.1/docs/guide/util/logging/) is no long available, change it to [https://docs.oracle.com/javase/8/docs/technotes/guides/logging/overview.html](https://docs.oracle.com/javase/8/docs/technotes/guides/logging/overview.html)
=> Update link to Java Logging documentation

src/main/java/org/apache/ibatis/parsing/GenericTokenParser.java
Before `while (start > -1) `,   existing judgment  `if (start == -1)`, so I suggest to adjust `while do` to `do while`,which can reduce redundant judgment.
=> Minor optimization for GenericTokenParser

src/main/java/org/apache/ibatis/io/ClassLoaderWrapper.java
when Class.forName() can not find class, will throw ClassNotFoundException install of null object
=> Remove unnecessary null check in ClassLoaderWrapper

src/main/java/org/apache/ibatis/cache/decorators/BlockingCache.java
=> Fix possible OutOfMemoryError in BlockingCache

.travis.yml, pom.xml
JaCoCo 0.8.6 is released.
@hazendaz ,
We should do this, right?
=> Revert workarounds for JaCoCo issue with JDK 15

src/main/java/org/apache/ibatis/scripting/xmltags/OgnlCache.java, src/main/java/org/apache/ibatis/session/Configuration.java, src/test/java/org/apache/ibatis/datasource/unpooled/UnpooledDataSourceTest.java, src/test/java/org/apache/ibatis/executor/resultset/DefaultResultSetHandlerTest.java, src/test/java/org/apache/ibatis/submitted/refid_resolution/ExternalRefidResolutionTest.java, src/test/java/org/apache/ibatis/submitted/serializecircular/SerializeCircularTest.java
=> Rewrite URLs referencing archived issues

src/main/java/org/apache/ibatis/cache/decorators/SerializedCache.java, src/main/java/org/apache/ibatis/executor/loader/AbstractSerialStateHolder.java, src/main/java/org/apache/ibatis/io/SerialFilterChecker.java
We have received another security vulnerability report caused by object stream deserialization.
When all of the following conditions are met, the attacker can trigger RCE (remote code execution).
1) the user enabled the built-in 2nd level cache [1]
2) the user did not setup JEP-290 filter
3) the attacker found a way to modify entries of the private `Map` field i.e. `org.apache.ibatis.cache.impl.PerpetualCache.cache` and a valid cache key
We thank clanceyzzz of JD Sprite Team for reporting the issue!
Once this PR gets merged, MyBatis outputs WARN level log message when deserializing object.
> As you are using functionality that deserializes object streams, it is recommended to define the JEP-290 serial filter. Please refer to https://docs.oracle.com/pls/topic/lookup?ctx=javase15&id=GUID-829 …
=> Output warning when deserializing object stream

src/main/java/org/apache/ibatis/cache/decorators/WeakCache.java
Just like SoftCache, getObject() or clear() function in WeakCache need synchronized.
Because LinkedList is not synchronized， and a structural modification is any operation that adds or deletes one or more elements in .
=> Prevent errors when accessing the cache concurrently

src/main/java/org/apache/ibatis/builder/xml/XMLConfigBuilder.java
In the context of parsing mybatis-config.xml -> environments element；if the environment was found, just break out of the loop
=> mybatis-config.xml parseConfiguration - The environment is already specified. Just break out of the loop

src/site/zh/xdoc/java-api.xml
fix doc typo in "Java Api" section for zh version.
Detail as following:
change "获取映射器示例和管理事务" to "获取映射器实例和管理事务"
=> Fix doc typo

src/main/java/org/apache/ibatis/binding/MapperProxy.java, src/main/java/org/apache/ibatis/cache/TransactionalCacheManager.java, src/main/java/org/apache/ibatis/executor/keygen/Jdbc3KeyGenerator.java, src/main/java/org/apache/ibatis/executor/resultset/DefaultResultSetHandler.java, src/main/java/org/apache/ibatis/plugin/Plugin.java, src/main/java/org/apache/ibatis/reflection/DefaultReflectorFactory.java, src/main/java/org/apache/ibatis/reflection/Reflector.java, src/main/java/org/apache/ibatis/scripting/LanguageDriverRegistry.java, src/main/java/org/apache/ibatis/util/MapUtil.java
This is a workaround for [JDK-8161372](https://bugs.openjdk.java.net/browse/JDK-8161372).
Related to ...
- https://github.com/mybatis/mybatis-3/issues/1929
- https://groups.google.com/g/mybatis-user/c/iBTN98c0dP4/m/H6IJS-LzAQAJ
We should drop this workaround once we drop Java 8 support (or the fix is backported).
=> Prevent thread from being blocked by JDK-8 ConcurrentHashMap#computeIfAbsent()

src/main/java/org/apache/ibatis/builder/SqlSourceBuilder.java
it's much better to use final decorate field in ParameterMappingTokenHandler class
=> it's better to use final decorate field in ParameterMappingTokenHandler class

src/main/java/org/apache/ibatis/reflection/SystemMetaObject.java
Closes: https://github.com/quarkiverse/quarkus-mybatis/issues/10
=> forObject is expecting an Object not its Class

src/main/java/org/apache/ibatis/type/TypeHandlerRegistry.java
=> Avoid unnecessary `ConcurrentHashMap#put()` calls in `TypeHandlerRegistry`

src/main/java/org/apache/ibatis/reflection/Reflector.java
Add an attribute 'allMethods' to cache all methods,reduce repetitive operations
=> Remove redundant call to Reflector#getClassMethods()

src/main/java/org/apache/ibatis/util/MapUtil.java
MapUtil#computeIfAbsent Object repeated creation #2339
=> Fix MapUtil#computeIfAbsent Object repeated creation

.github/workflows/ci.yaml, src/test/java/org/apache/ibatis/builder/XmlConfigBuilderTest.java, src/test/java/org/apache/ibatis/executor/loader/CglibProxyTest.java, src/test/java/org/apache/ibatis/submitted/lazy_properties/LazyPropertiesTest.java, src/test/java/org/apache/ibatis/submitted/lazyload_proxyfactory_comparison/CglibLazyTest.java, src/test/java/org/apache/ibatis/submitted/ognl_enum/EnumWithOgnlTest.java, src/test/java/org/apache/ibatis/submitted/ognlstatic/OgnlStaticTest.java
Some tests that require  `--illegal-access=permit` are skipped on 17 and 18-ea (the option was removed in 17 GA).
I added a new tag `@Tag("RequireIllegalAccess")` to those tests.
Regarding CGLIB, this issue tracks the 17/18 support, I think : https://github.com/cglib/cglib/issues/191
I changed the `distribution` because AdoptOpenJDK is [moved to Eclipse Adoptium](https://blog.adoptopenjdk.net/2021/08/goodbye-adoptopenjdk-hello-adoptium/) and 18-ea is (was?) only available in zulu.
=> [ci] Java 17 GA and 18-ea

src/main/java/org/apache/ibatis/type/CharacterTypeHandler.java, src/test/java/org/apache/ibatis/type/CharacterTypeHandlerTest.java
this is a basic error, the condition statement miss the [String !=""] condition in if(...);
in this case, i execute the select sql statement, and the resultType include a property -- Character type, when the DataBase return a "", Mybatis will throw a Exception: index out of range, becasue the array's length is 0 in the statement -- "return columnValue.charAt(0);"
=> CharacterTypeHandler#getNullableResult() throws StringIndexOutOfBoundsException

pom.xml, src/main/java/org/apache/ibatis/logging/LogFactory.java, src/main/java/org/apache/ibatis/logging/log4j/Log4jImpl.java, src/main/java/org/apache/ibatis/logging/log4j/package-info.java, src/site/es/xdoc/configuration.xml, src/site/es/xdoc/logging.xml, src/site/ja/xdoc/configuration.xml, src/site/ja/xdoc/logging.xml, src/site/ko/xdoc/configuration.xml, src/site/ko/xdoc/logging.xml, src/site/xdoc/configuration.xml, src/site/xdoc/logging.xml, src/site/zh/xdoc/configuration.xml, src/site/zh/xdoc/logging.xml, src/test/java/log4j.properties, src/test/java/logback-test.xml, src/test/java/org/apache/ibatis/logging/LogFactoryTest.java, src/test/java/org/apache/ibatis/session/AutoMappingUnknownColumnBehaviorTest.java
I've fixed #1223 .
* Add `@deprecated` at modules for log4j 1.x
* Change SLF4J binding library to the logback(implements SLF4J directly) from slf4j-log4j12 on test
* Add deprecated mark
* Change example to SLF4(logback) based instead of Log4J
* Add examples for Log4j 2.x and JDK logging
* Keep example for Log4j 1.x
=> Deprecated Log4J 1.x #1223

src/main/java/org/apache/ibatis/builder/xml/XMLConfigBuilder.java, src/main/java/org/apache/ibatis/builder/xml/mybatis-3-mapper.dtd, src/main/java/org/apache/ibatis/builder/xml/mybatis-mapper.xsd, src/main/java/org/apache/ibatis/scripting/xmltags/ExpressionEvaluator.java, src/main/java/org/apache/ibatis/scripting/xmltags/ForEachSqlNode.java, src/main/java/org/apache/ibatis/scripting/xmltags/XMLScriptBuilder.java, src/main/java/org/apache/ibatis/session/Configuration.java, src/site/es/xdoc/configuration.xml, src/site/es/xdoc/dynamic-sql.xml, src/site/ja/xdoc/configuration.xml, src/site/ja/xdoc/dynamic-sql.xml, src/site/ko/xdoc/configuration.xml, src/site/ko/xdoc/dynamic-sql.xml, src/site/xdoc/configuration.xml, src/site/xdoc/dynamic-sql.xml, src/site/zh/xdoc/configuration.xml, src/site/zh/xdoc/dynamic-sql.xml, src/test/java/org/apache/ibatis/builder/CustomizedSettingsMapperConfig.xml, src/test/java/org/apache/ibatis/builder/XmlConfigBuilderTest.java, src/test/java/org/apache/ibatis/submitted/foreach/ForEachTest.java, src/test/java/org/apache/ibatis/submitted/foreach/Mapper.java, src/test/java/org/apache/ibatis/submitted/foreach/Mapper.xml
I will propose to support new option for allowing `null` value on `collection` attribute of `foreach` tag.
In this change, a developer can omit the `if` tag as follow:
* current version
```xml
<if test="friendList != null"> 
<foreach item="item" collection="friendList" open="id in (" separator="," close=")">
#{item.id}
</foreach>
</if>
```
* new version
```xml
<foreach item="item" collection="friendList" nullable="true" open="id in (" separator="," close=")">
#{item.id}
</foreach>
```
Also, a developer can change the default `nullable` value when the `nullable` attribute is omitted using global configuration as follow:
* global configuration
XML configuration (`mybatis-config.xml`):
```xml
<settings>
<setting name="nullableOnForEach" value="true"/>
</settings>
```
or 
Java …
=> Add option for allowing null value on foreach tag

src/test/java/org/apache/ibatis/type/BooleanTypeHandlerTest.java
We are investigating mock objects in test suites over different benchmarks, and we believe this one is missing the @Test annotation.
=> Add @Test annotation to shouldGetResultNullFromCallableStatement() in BooleanTypeHandlerTest

src/site/es/xdoc/dynamic-sql.xml, src/site/ja/xdoc/dynamic-sql.xml, src/site/xdoc/dynamic-sql.xml, src/site/zh/xdoc/dynamic-sql.xml
The behavior of set tags was changed via #21
=> Update the expression of set tags in Dynamic SQL document.

src/main/java/org/apache/ibatis/jdbc/SqlBuilder.java
The deprecated class should add `@Deprecated` annotation
=> add deprecated annotation

src/site/xdoc/getting-started.xml
This paragraph describes not using XML as a configuration file. So the single word "XML" refers to a configuration file, not a mapper in the context. So when we talk about using XML mappers, we should be explicit.
=> Eliminating ambiguity of "XML"

src/main/java/org/apache/ibatis/builder/xml/XMLConfigBuilder.java, src/main/java/org/apache/ibatis/executor/resultset/DefaultResultSetHandler.java, src/main/java/org/apache/ibatis/session/Configuration.java, src/site/es/xdoc/configuration.xml, src/site/ja/xdoc/configuration.xml, src/site/ko/xdoc/configuration.xml, src/site/xdoc/configuration.xml, src/site/zh/xdoc/configuration.xml, src/test/java/org/apache/ibatis/builder/CustomizedSettingsMapperConfig.xml, src/test/java/org/apache/ibatis/builder/XmlConfigBuilderTest.java, src/test/java/org/apache/ibatis/builder/xsd/CustomizedSettingsMapperConfig.xml, src/test/java/org/apache/ibatis/builder/xsd/XmlConfigBuilderTest.java, src/test/java/org/apache/ibatis/submitted/arg_name_baesd_constructor_automapping/ArgNameBasedConstructorAutoMappingTest.java, src/test/java/org/apache/ibatis/submitted/arg_name_baesd_constructor_automapping/CreateDB.sql, src/test/java/org/apache/ibatis/submitted/arg_name_baesd_constructor_automapping/Mapper.java, src/test/java/org/apache/ibatis/submitted/arg_name_baesd_constructor_automapping/Mapper.xml, src/test/java/org/apache/ibatis/submitted/arg_name_baesd_constructor_automapping/Task.java, src/test/java/org/apache/ibatis/submitted/arg_name_baesd_constructor_automapping/User.java, src/test/java/org/apache/ibatis/submitted/arg_name_baesd_constructor_automapping/User2.java, src/test/java/org/apache/ibatis/submitted/arg_name_baesd_constructor_automapping/mybatis-config.xml
An attempt at fixing #2192 
- A new option `argNameBasedConstructorAutoMapping` is added.
- When enabled, MyBatis searches a column that matches the constructor argument name.
Compared to the current (=column order based) constructor auto-mapping, name-based auto-mapping is more lenient.
- The column order is irrelevant.
- The number of columns can be greater than the number of arguments (but cannot be less).
- The columns used in constructor auto-mapping are not used in property mapping. This prevents unintuitive behavior like #2207 .
Cc: @h3adache
=> Argument name based constructor auto-mapping

LICENSE_HEADER, src/site/xdoc/getting-started.xml
next parent will use LICENSE_HEADER as more appropriate naming for the license header.  The older file will be removed then.
=> Fix utf-8 bom and add future representation for license header

src/site/es/xdoc/configuration.xml, src/site/ja/xdoc/configuration.xml, src/site/ko/xdoc/configuration.xml, src/site/xdoc/configuration.xml, src/site/zh/xdoc/configuration.xml
except english doc, in other language docs，ExampleObjectFactory class, create method has  args type error。the pr is trying to fix it。
=> fix the configuration.xml doc

src/site/zh/xdoc/getting-started.xml
**Polish the document**.
Details:
1. It's strange to use "建造器“ to describe the "builder" in programming. "建造" matches "buildings". maybe it better to be replaced with "构建".
2. Obviously in other parts of the document we will still refer to the "mapping" content so it will be more friendly to the reader to highlight the order of precedence in Chinese.
3. Remove the redundant subject "你".
4. Remove the redundant verb "认为".
5. In Chinese, we use "地" to modify the verb instead of "的".
6. sync with #2531.
=> Update the zh-CN getting-started doc 

src/main/java/org/apache/ibatis/session/SqlSessionManager.java
`set(null)` to remove the value might keep the reference to this pointer in the map, which can cause memory leak in some scenarios. Using remove is safer to avoid this issue.
#2509
=> [ISSUE #2509]Fix memory leak

src/main/java/org/apache/ibatis/session/SqlSessionFactoryBuilder.java
=> avoid generating NullPointerException while closing IO

src/main/java/org/apache/ibatis/type/TypeAliasRegistry.java, src/test/java/org/apache/ibatis/type/TypeAliasRegistryTest.java
=> [ISSSUE #2546]Register char

src/site/zh/xdoc/configuration.xml
1. add some translations for the new feature in 3.5.9 and 3.5.10.
2. reference the [ja-doc](https://github.com/mybatis/mybatis-3/blob/17292b49ccf9721991bb4841b891879b7f4ada37/src/site/ja/xdoc/configuration.xml#L1746)， the "facility" should be translated to ”功能“, not "设施".
=> update the configuration.xml in zh doc

src/main/java/org/apache/ibatis/builder/xml/mybatis-3-mapper.dtd, src/main/java/org/apache/ibatis/builder/xml/mybatis-mapper.xsd
=> Constructor id arguments don't need to be listed first

src/site/zh/xdoc/java-api.xml
My fault.
There are still non-translated scripts. now it is completed.
=> update java-api.xml in zh doc

src/site/es/xdoc/configuration.xml, src/site/ja/xdoc/configuration.xml, src/site/ko/xdoc/configuration.xml, src/site/xdoc/configuration.xml, src/site/zh/xdoc/configuration.xml
Follow #2551 
Update document for typeAliases
=> [Doc] Update document

ISSUE_TEMPLATE.md
I reviewed the history of commits. I found that the Chinese tips are mainly for users in Mainland China. If not, I will revert the PR.
I do sth. as follows:
1. unify the characters to Simplified Chinese.
2. add some translations to improve readability.
=> polish the tips in issue template

src/main/java/org/apache/ibatis/session/Configuration.java
The first line already has a default value
protected ExecutorType defaultExecutorType = ExecutorType.SIMPLE;
=> Remove redundant null check in Configuration#newExecutor()

.github/workflows/ci.yaml
https://github.com/oracle-actions/setup-java
We still have to use zulu for versions < 18
=> Adopt oracle-actions/setup-java

pom.xml, src/test/java/org/apache/ibatis/parsing/GenericTokenParserTest.java
**Problem:**
A test method with many individual assertions stops being executed on the first failed assertion, which prevents the remaining ones' execution. In the refactored methods, the difference between the assertions lies in different arguments only.
**Solution:**
Parameterized tests make it possible to run a test multiple times, with different arguments, as individual and independent tests. This way, we were able to make 2 original tests become 24 independent ones. In this refactoring, no original assertion parameter was changed.
**Additional change:**
Maven dependency concerning the JUnit params library was also added.
=> Improvement: multiple-assertions unit tests into parameterized ones

src/main/java/org/apache/ibatis/io/DefaultVFS.java, src/test/java/org/apache/ibatis/io/ExternalResourcesTest.java
unfortunately if > jdk 16 uses with current project needs, the detection can be a bit off.  So this is not entirely ideal until we are on higher jdks and stop using static for searching when we already have it.  For now this is better.
=> [modernize] Use standard charsets

src/main/java/org/apache/ibatis/executor/resultset/DefaultResultSetHandler.java, src/test/java/org/apache/ibatis/submitted/empty_row/ImmutableParent.java, src/test/java/org/apache/ibatis/submitted/empty_row/Mapper.java, src/test/java/org/apache/ibatis/submitted/empty_row/ReturnInstanceForEmptyRowTest.java
=> returnInstanceForEmptyRow should work for constructor auto-mapping

src/main/java/org/apache/ibatis/mapping/BoundSql.java
For now its not possible to copy BoundSql to another BoundSql without using reflection.
Goal is to modify sql on the fly. This class inserts "SET LOCAL SCHEMA..." to the beginning of sql.
Absence of getter for "additionalParameters" field makes us use reflection. If we not set additionalParameters, dynamic sql features like <foreach collection....  would't work.
```java
import lombok.extern.slf4j.Slf4j;
import org.apache.ibatis.executor.Executor;
import org.apache.ibatis.mapping.BoundSql;
import org.apache.ibatis.mapping.MappedStatement;
import org.apache.ibatis.mapping.SqlSource;
import org.apache.ibatis.plugin.Interceptor;
import org.apache.ibatis.plugin.Intercepts;
import org.apache.ibatis.plugin.Invocation;
import org.apache.ibatis.plugin.Plugin;
import …
```
=> added getter for additionalParameters

src/main/java/org/apache/ibatis/builder/xml/XMLConfigBuilder.java, src/test/java/org/apache/ibatis/builder/XmlConfigBuilderTest.java
Supported via the InputStream/Reader constructors
Default constructors will keep using a new configuration
=> Enable ability to provide custom configuration to XMLConfigBuilder

src/main/java/org/apache/ibatis/session/Configuration.java
In projects using the Spring framework, we often use `@PostConstruct` to perform some operations after bean initialization. In some scenarios, we will create asynchronous thread to perform some time-consuming SQL operations to avoid blocking the application startup process. We observed that the use of mappers in asynchronous thread may broken due to the `resize` of the underlying `StrictMap` of `mappedStatements`.
Example code for using `@PostConstruct` with asynchronous thread, [MybatisRaceConditionApplication.java](https://github.com/tianshuang/mybatis-race-condition/blob/main/src/main/java/me/tianshuang/MybatisRaceConditionApplication.java#L19-L45):
```java
@Autowired
private Mapper1 mapper1;
private volatile boolean applicationReady;
@PostConstruct
public void raceConditionTest() { …
```
=> Fix a race condition caused by other threads calling mapper methods while mappedStatements are being constructed

src/main/java/org/apache/ibatis/io/DefaultVFS.java
Under JPMS (Java Platform Module System), `ClassLoader#getResources()` could throw `FileSystemException` it seems.
Should fix #2598
=> Adding mapper could fail under JPMS

src/main/java/org/apache/ibatis/annotations/Select.java, src/main/java/org/apache/ibatis/annotations/SelectProvider.java, src/main/java/org/apache/ibatis/builder/MapperBuilderAssistant.java, src/main/java/org/apache/ibatis/builder/annotation/MapperAnnotationBuilder.java, src/main/java/org/apache/ibatis/builder/xml/XMLStatementBuilder.java, src/main/java/org/apache/ibatis/mapping/MappedStatement.java, src/main/java/org/apache/ibatis/session/defaults/DefaultSqlSession.java, src/main/resources/org/apache/ibatis/builder/xml/mybatis-3-mapper.dtd, src/site/es/xdoc/java-api.xml, src/site/es/xdoc/sqlmap-xml.xml, src/site/ja/xdoc/java-api.xml, src/site/ja/xdoc/sqlmap-xml.xml, src/site/ko/xdoc/java-api.xml, src/site/ko/xdoc/sqlmap-xml.xml, src/site/xdoc/java-api.xml, src/site/xdoc/sqlmap-xml.xml, src/site/zh/xdoc/java-api.xml, src/site/zh/xdoc/sqlmap-xml.xml, src/test/java/org/apache/ibatis/submitted/dirty_select/DirtySelectTest.java, src/test/java/org/apache/ibatis/submitted/dirty_select/Mapper.java, src/test/java/org/apache/ibatis/submitted/dirty_select/User.java, src/test/resources/org/apache/ibatis/submitted/dirty_select/CreateDB.sql, src/test/resources/org/apache/ibatis/submitted/dirty_select/Mapper.xml
Some DBs support returning result set from INSERT/UPDATE/DELETE statements. e.g.
- PostgreSQL has `RETURNING`
- MS SQL Server has `OUTPUT`
By using `@Select`, `@SelectProvider` or `<select />`, it is possible to retrieve data from those statements.
The problem is that calling `SqlSession#commit()` or `SqlSession#rollback()`does not work as expected because MyBatis assumes SELECT does not affect DB data [1].
By setting `affectData=true`, users can indicate that the SELECT statement affects DB data.
Related to:
- #1189
- #2156 
- #2363 
- https://groups.google.com/g/mybatis-user/c/1Wn-0IyUi-Q/m/2MUAL4nFBwAJ
Notes:
- The use of `@Select`, `@SelectProvider`, `<select />` might look unintuitive, but changing the INSERT/UPDATE/DELETE behavior requires bigger change. The characteristic of these …
=> Add `affectData` attribute to `@Select`, `@SelectProvider` and `<select />`

src/test/java/org/apache/ibatis/io/ExternalResourcesTest.java
few modernization issues detected with parent 37 snapshot.
=> [ci] Cleanup charset usage

src/main/java/org/apache/ibatis/builder/MapperBuilderAssistant.java, src/main/java/org/apache/ibatis/builder/annotation/MapperAnnotationBuilder.java, src/main/java/org/apache/ibatis/builder/xml/XMLStatementBuilder.java, src/main/java/org/apache/ibatis/executor/resultset/DefaultResultSetHandler.java, src/test/java/org/apache/ibatis/submitted/no_result_type_map/Mapper.java, src/test/java/org/apache/ibatis/submitted/no_result_type_map/NoResultTypeMapTest.java, src/test/java/org/apache/ibatis/submitted/no_result_type_map/ParentMapper.java, src/test/java/org/apache/ibatis/submitted/no_result_type_map/User.java, src/test/resources/org/apache/ibatis/submitted/no_result_type_map/CreateDB.sql, src/test/resources/org/apache/ibatis/submitted/no_result_type_map/Mapper.xml, src/test/resources/org/apache/ibatis/submitted/no_result_type_map/mybatis-config.xml
In our work time it's is possible to write a error resultType in mapper.xml. I think we can resolve resultType by namespce and id in mapper.xml, then we can avoid this error
=> Use method signature to resolve `resultType` of `<select>`

pom.xml
some of our tests need the legacy style support that mockito made available.  We should look at those in longer term to get on fact that inline is now the default as per mockito we will likely have other issues.
note: This will fix @harawata attempt at adding jdk 21.
=> [pom] Add mockito subclass support

src/main/java/org/apache/ibatis/builder/MapperBuilderAssistant.java, src/main/java/org/apache/ibatis/mapping/ResultMap.java, src/test/java/org/apache/ibatis/submitted/record_type/RecordTypeMapper.java, src/test/java/org/apache/ibatis/submitted/record_type/RecordTypeTest.java
Should fix #2803
Also added more info to the error message. Related to #2787
=> Search readable property when resolving constructor arg type by name

src/test/java/org/apache/ibatis/executor/BaseExecutorTest.java, src/test/java/org/apache/ibatis/executor/ExecutorTestHelper.java
IMAGES section does not match with discriminator,
thus the query result is forwarded to "defaultResultMap" instead of "postResultMap".
The "defaultResultMap" maps "id" column to "id" key in HashMap.
The "postResultMap" maps "id" column to "ID" key in HashMap, this is because by default MyBatis converts the column name to uppercase when using a HashMap as the result type in a result map.
To clarify this consequence, I updated test code.
=> Update test code to clarify the consequence

src/test/java/org/apache/ibatis/datasource/pooled/PooledDataSourceTest.java
I wrote several unit tests for PooledDataSource. 
If program tries to get a connection beyond the number of dataSource.getPoolMaximumActiveConnections, it should be blocked.
The Popped Connection should be not equal to previously closed connection. When closing a connection, it should generate new connection and stash away it to idleConnections in PoolState.
When closing a connection, the number of idle connection in idleConnections in PoolState increases by one, but not beyond dataSource.setPoolMaximumIdleConnections
It is the test extending test 1. If program tries to get a connection beyond the number of dataSource.getPoolMaximumActiveConnections, program is blocked. But If time passes beyond dataSource.getPoolMaximumCheckoutTime, a connection should be available.
forceCloseAll should …
=> Add Unit Test for PooledDataSource

.github/workflows/ci.yaml, README.md, pom.xml
=> [tests] Rework test process and document it dropping use of prioer profile for straight property usage

src/test/java/org/apache/ibatis/datasource/pooled/PooledDataSourceTest.java
I committed PooledDataSourceTest.java a few days ago (1640f1a).
In this commit, I added CountDownLatch to make sure the execution order I intended.
Execution Order I intended
1. Close the connection. (-> new connection is opened and it is saved in the list of Idle connection)
2. Get the new connection (-> get the idle connection it saved above)
3. See they are not equal. (-> closed connection != idle connection)
Thank you :)
=> Use CountDownLatch to coordinate the execution order

src/site/zh/xdoc/sqlmap-xml.xml
The original English doc for `parameterType` is:
> This attribute is optional because MyBatis can calculate the TypeHandler to use out of the actual parameter passed to the statement.
I think the original meaning is that the "actual parameter passed to the statement" makes "MyBatis calculates the TypeHandler to use" happen.
However, the Chinese translated version:
> MyBatis 可以通过类型处理器（TypeHandler）推断出具体传入语句的参数
**is a inversion of cause and effect**, which means that "MyBatis can infer the actual parameter passed to the statement" BY MEANS OF "its TypeHandler".
This is confusing and misleading.
The correct translation I believe should be:
> MyBatis 可以根据语句中实际传入的参数计算出应该使用的类型处理器（TypeHandler）
=> fix Chinese translation error for `parameterType`

src/main/java/org/apache/ibatis/session/Configuration.java
Optimize the loop, use xxMap.values()  instead of xxMap().entrySet().
=> Optimize the loop of resultMaps in Configuration

src/main/java/org/apache/ibatis/builder/MapperBuilderAssistant.java, src/main/java/org/apache/ibatis/mapping/ResultMap.java, src/site/es/xdoc/sqlmap-xml.xml, src/site/ja/xdoc/sqlmap-xml.xml, src/site/ko/xdoc/sqlmap-xml.xml, src/site/xdoc/sqlmap-xml.xml, src/site/zh/xdoc/sqlmap-xml.xml, src/test/java/org/apache/ibatis/submitted/record_type/RecordTypeMapper.java, src/test/java/org/apache/ibatis/submitted/record_type/RecordTypeTest.java, src/test/java/org/apache/ibatis/submitted/unmatched_prop_type/UnmatchedPropTypeMapper.java, src/test/java/org/apache/ibatis/submitted/unmatched_prop_type/UnmatchedPropTypeTest.java, src/test/java/org/apache/ibatis/submitted/unmatched_prop_type/User.java, src/test/resources/org/apache/ibatis/submitted/unmatched_prop_type/CreateDB.sql, src/test/resources/org/apache/ibatis/submitted/unmatched_prop_type/mybatis-config.xml
#2804 which was supposed to be a fix for #2803 caused a regression ( https://github.com/mybatis/mybatis-3/pull/2804#issuecomment-1450483900 , #2834 ).
This PR reverts #2804 and updates docs and error message for clarity.
=> gh-2834 result map regression

src/main/java/org/apache/ibatis/executor/resultset/DefaultResultSetHandler.java, src/main/java/org/apache/ibatis/jdbc/ScriptRunner.java
It's a common mistake, but optimizing the condition breaks the contract. The code must check the results of `getMoreResults()` AND `getUpdateCount()`.
Here is an excerpt from the [javadoc](https://docs.oracle.com/en/java/javase/17/docs/api/java.sql/java/sql/Statement.html#getMoreResults()).
> There are no more results when the following is true:
> 
>    // stmt is a Statement object
>    ((stmt.getMoreResults() == false) && (stmt.getUpdateCount() == -1))
We have received several PRs with the same mistake.
e.g. #1095
Added a stronger comment.
=> Undo invalid code optimization

.github/workflows/ci.yaml
=> Drop jdk 19 on CI

src/main/java/org/apache/ibatis/executor/resultset/DefaultResultSetHandler.java, src/test/java/org/apache/ibatis/submitted/discriminator/Contract.java, src/test/java/org/apache/ibatis/submitted/discriminator/DiscriminatorTest.java, src/test/java/org/apache/ibatis/submitted/discriminator/Mapper.java, src/test/resources/org/apache/ibatis/submitted/discriminator/CreateDB.sql, src/test/resources/org/apache/ibatis/submitted/discriminator/Mapper.xml
Currently, discriminator is not correctly evaluated in a result map that is referenced from a constructor mapping.
Reported in https://stackoverflow.com/q/76177553/1261766
=> Support result map with discriminator in constructor mapping

src/main/java/org/apache/ibatis/scripting/defaults/DefaultParameterHandler.java, src/test/java/org/apache/ibatis/scripting/defaults/DefaultParameterHandlerTest.java
When invoke `DefaultParameterHandler#setParameters` to get parameter's property values using MetaObject, `parameterMappings` will create the same `MetaObject` multiple times during traversal. I think this can be avoided in order to reduce object creation.
=> optimize DefaultParameterHandler create same MeteObject multiple times

src/main/java/org/apache/ibatis/executor/BaseExecutor.java, src/test/java/org/apache/ibatis/executor/BaseExecutorTest.java, src/test/java/org/apache/ibatis/scripting/defaults/DefaultParameterHandlerTest.java
Last time I submitted an optimization for the DefaultParameterHandler (#2946 ), but I'm sorry, I missed one more point. Its logic is the same as the DefaultParameterHandler, so I try refactored it.
=> optimize when get parameter property value create same MeteObject multiple times

src/main/java/org/apache/ibatis/type/TypeHandlerRegistry.java, src/test/java/org/apache/ibatis/scripting/defaults/DefaultParameterHandlerTest.java, src/test/java/org/apache/ibatis/submitted/enum_with_method/EnumWithMethodTest.java, src/test/java/org/apache/ibatis/submitted/enum_with_method/Mood.java, src/test/java/org/apache/ibatis/submitted/enum_with_method/MoodTypeTypeHandler.java, src/test/resources/org/apache/ibatis/submitted/enum_with_method/CreateDB.sql, src/test/resources/org/apache/ibatis/submitted/enum_with_method/Mapper.xml, src/test/resources/org/apache/ibatis/submitted/enum_with_method/mybatis-config.xml
=> Registered type handler should be used for anonymous enum

src/main/java/org/apache/ibatis/builder/BaseBuilder.java, src/main/java/org/apache/ibatis/builder/xml/XMLConfigBuilder.java
1. I think the author AVE! handles the code at the beginning of settingsAsProperties very well, which can make the code hierarchy look less and more elegant. So I made a little tweak to XMLConfigBuilder's parsing code.
2. Unify the name of the parent XNode called context.
3. Keep the code style in BaseBuilder consistent with Maves to make it look more elegant.
=> Optimize the code of the xml configuration file parsing process

.github/workflows/ci.yaml, pom.xml
not doing this will have impact due to our java 16+ switching to require java 16.
=> [pom] Rework 'derby' and allow java 11 again

src/main/java/org/apache/ibatis/executor/resultset/DefaultResultSetHandler.java, src/main/java/org/apache/ibatis/executor/resultset/ResultSetWrapper.java
If the number of columns is very large, this is quite a performance hit, due to O(n) runtime.
=> Fix performance of mappedColumnNames.contains

pom.xml
#3028  NoClassDefFoundExceptions on Java 11 with OSGi
On Java 11 using Karaf with Felix when enhancing classes users need access to:
* org.apache.ibatis.executor.loader.WriteReplaceInterface
* org.apache.ibatis.javassist.util.proxy.ProxyObject
In the current build the `bnd-maven-plugin` is executed before shading thus the Javassist classes don't exist and aren't exported. In my local build bnd passed with this addition and I was able to use the SNAPSHOT bundle in my application successfully
=> #3028 Add shaded javassist package to osgi.export

src/site/zh/xdoc/sqlmap-xml.xml
`As an irregular case, some databases allow INSERT, UPDATE or DELETE statement to return result set (e.g. <code>RETURNING</code> clause of PostgreSQL and MariaDB or <code>OUTPUT</code> clause of MS SQL Server). This type of statement must be written as <code><![CDATA[<select>]]></code> to map the returned data.` 
`在一些特殊情况下，一些数据库允许INSERT、UPDATE或DELETE语句返回结果集（例如：PostgreSQL和MariaDB数据库的<code>RETURNING</code>子句，或者是MS SQL Server的<code>OUTPUT</code>子句）。这种类型的语句必须使用<code><![CDATA[<select>]]></code>，用于映射返回的数据。`
=> docs: Translated into Chinese

src/main/java/org/apache/ibatis/jdbc/AbstractSQL.java, src/test/java/org/apache/ibatis/jdbc/SQLTest.java
I propose to add following new method for generating dynamic sql on SQL.
* `applyIf` (similar `<if>` element in XML language driver)
* `applyForEach` (similar `<foreach>` element in XML language driver)
In this change, the developer can write dynamic sql using with fluent style as follow:
**applyIf**
```java
// Generate following SQL if b and c is null
// UPDATE test SET a=#{a} WHERE (id=#{id})
String sqlString = new SQL()
.UPDATE("test")
.applyIf(bean::hasA, sql -> sql.SET("a=#{a}"))
.applyIf(bean::hasB, sql -> sql.SET("b=#{b}"))
.applyIf(bean::hasC, sql -> sql.SET("c=#{c}"))
.WHERE("id=#{id}")
.toString();
```
**applyForEach**
```java
// Generate following SQL if beans has two element
// INSERT INTO test (a, b, c) VALUES (#{list[0].a}, #{list[0].b}, #{list[0].c}), (#{list[1].a}, …
```
=> Add support method for generating dynamic sql on SQL class

src/main/java/org/apache/ibatis/mapping/VendorDatabaseIdProvider.java, src/test/java/org/apache/ibatis/mapping/VendorDatabaseIdProviderTest.java
As reported in #3040, swallowing the `SQLException` could cause runtime errors because 1) no statement is picked up or 2) statement without `databaseId` is incorrectly chosen.
I don't think `getDatabasename()` throws other exceptions than `SQLException`, but I'll make further adjustment if I'm wrong.
=> `VendorDatabaseIdProvider` should throw exception if DB error occurs

pom.xml
=> [pom] Make sure source package picks up our shaded artifacts to help users in IDEs - fixes #3045

src/main/java/org/apache/ibatis/reflection/MetaObject.java, src/main/java/org/apache/ibatis/reflection/wrapper/BaseWrapper.java, src/main/java/org/apache/ibatis/reflection/wrapper/BeanWrapper.java, src/main/java/org/apache/ibatis/reflection/wrapper/MapWrapper.java, src/test/java/org/apache/ibatis/reflection/wrapper/BeanWrapperTest.java, src/test/java/org/apache/ibatis/reflection/wrapper/MapWrapperTest.java
Also, users can now extend the built-in `MapWrapper` to write a custom one.
Should fix #13 #2298 #3062
=> Allow custom map wrapper to handle keys with dots or brackets

pom.xml
newer jdks (ie 21 for example) are noting undefined usage will be blocked in the future, defining the used annotation processor as a result.
=> [pom] Define byte buddy agent for compiler and surefire

src/main/java/org/apache/ibatis/executor/resultset/DefaultResultSetHandler.java
`java.lang.reflect.Constructor.getParameterTypes` method clones objects
```java
public Class<?>[] getParameterTypes() {
return parameterTypes.clone();
}
```
this change will reduce not necessary memory allocations.
=> fix: DefaultResultSetHandler memory waste #3113

src/test/java/org/apache/ibatis/submitted/blocking_cache/BlockingCacheTest.java
This test has been failing sporadically on some CI runners. 
- Use more modern approach to shut down thread pool, `awaitTermination` (prevent infinite loop in case of failure)
- Use assertJ so we can get the reason it failed if it does
- Change to `greaterThanOrEqualTo` as this test is successful if the calls blocked on each other and we know that with (500ms * 2)
=> fix: Fix flaky test (testBlockingCache) on master/pr's

src/main/java/org/apache/ibatis/executor/keygen/SelectKeyGenerator.java
This pull request suggests using isEmpty() instead of length().
- **Readability:** The isEmpty() method clearly conveys the intention of checking if the collection is empty. Therefore, it makes it easier for developers to understand the code.
- **Intended Behavior:** The isEmpty() method is designed to check if a collection is empty. This aligns better with the developer's intention and makes the code more expressive.
- **Common Convention:** In the Java collection framework, it's common to use the isEmpty() method to check if a collection is empty. Following this common convention helps maintain consistency in the codebase.
In conclusion, using the isEmpty() method improves code readability and aligns better with the intended behavior. It also adheres to the common convention in the Java …
=> Use isEmpty() instead of length()

src/main/java/org/apache/ibatis/executor/loader/ResultLoaderMap.java, src/main/java/org/apache/ibatis/executor/loader/javassist/JavassistProxyFactory.java
In Java, it is recommended to use `isEmpty()` instead of comparing the `size()` of a collection object with 0.
- Added isEmpty() method to the ResultLoaderMap object
=> Recommend using isEmpty() instead of size().

src/main/java/org/apache/ibatis/reflection/TypeParameterResolver.java, src/test/java/org/apache/ibatis/reflection/TypeParameterResolverTest.java
**Unit Test Code**
```java
@Test
void testReturn_LV1Map() throws Exception {
Class<?> clazz = Level1Mapper.class;
Method method = clazz.getMethod("selectMap");
Type result = TypeParameterResolver.resolveReturnType(method, clazz);
assertTrue(result instanceof ParameterizedType);
ParameterizedType paramType = (ParameterizedType) result;
assertEquals(Map.class, paramType.getRawType());
assertEquals(2, paramType.getActualTypeArguments().length);
assertEquals(String.class, paramType.getActualTypeArguments()[0]);
assertEquals(Object.class, paramType.getActualTypeArguments()[1]);
}
```
**Expected** :class java.lang.Object
**Actual**: F
=> Fix scanSuperTypes function to return Object Class instead of generic types

src/main/java/org/apache/ibatis/session/defaults/DefaultSqlSession.java, src/main/java/org/apache/ibatis/session/defaults/DefaultSqlSessionFactory.java, src/test/java/org/apache/ibatis/session/defaults/ExtendedSqlSession.java, src/test/java/org/apache/ibatis/session/defaults/ExtendedSqlSessionFactory.java, src/test/java/org/apache/ibatis/session/defaults/ExtendedSqlSessionFactoryBuilder.java, src/test/java/org/apache/ibatis/session/defaults/ExtendedSqlSessionFactoryTest.java
Hi Maintainers! 
While extending `SqlSessionFactoryBuilder` allows users to _fully_ customise their implementations of `SqlSessionFactory` and `SqlSession`, the drawback is that you cannot use the safe defaults MyBatis provides anymore, which leaves two options:
* Duplicate (copy/paste) `DefaultSqlSession` and `DefaultSqlSessionFactory`, the drawbacks here are that you do not get upstream updates anymore and have to compare and update these files every release.
* Use reflection, the drawbacks here are that this is quite dirty and suffers from the same problems mentioned above.
I added a minimal test case which shows a structure  that would allow the use of the defaults while providing important extension points.
Additionally, allow subclasses of `DefaultSqlSession` to call …
=> feat: allow `DefaultSqlSessionFactory` to provide a custom `SqlSession`

src/site/es/markdown/index.md, src/site/es/markdown/logging.md, src/site/es/resources/css/site.css, src/site/fr/resources/css/site.css, src/site/ja/markdown/index.md, src/site/ja/markdown/logging.md, src/site/ja/resources/css/site.css, src/site/ko/markdown/getting-started.md, src/site/ko/markdown/index.md, src/site/ko/markdown/logging.md, src/site/ko/resources/css/site.css, src/site/markdown/configuration.md, src/site/markdown/dynamic-sql.md, src/site/markdown/getting-started.md, src/site/markdown/index.md, src/site/markdown/java-api.md, src/site/markdown/logging.md, src/site/markdown/sqlmap-xml.md, src/site/markdown/statement-builders.md, src/site/resources/css/site.css, src/site/zh_CN/markdown/getting-started.md, src/site/zh_CN/markdown/index.md, src/site/zh_CN/markdown/logging.md, src/site/zh_CN/resources/css/site.css
As report in
https://github.com/mybatis/mybatis-3/issues/3186
AFAIK, a newest maven version cause blank site.
>Markdown conflict with Velocity on ## syntax:
Since ## denotes a [single line comment](https://velocity.apache.org/engine/2.3/vtl-reference.html#single-line-comments) in Velocity, Markdown headers using this syntax are suppressed from generated content.
You can use [unparsed content syntax](https://velocity.apache.org/engine/2.3/vtl-reference.html#unparsed-content) #[[##]]# or [escape tool](https://velocity.apache.org/tools/3.1/apidocs/org/apache/velocity/tools/generic/EscapeTool.html) like ${esc.h}${esc.h}.
[More detail maven-site-plugin](https://maven.apache.org/plugins/maven-site-plugin/examples/creating-content.html)
But I found the another way.
If markdown file does not …
=> Display online english guide

src/test/java/org/apache/ibatis/executor/ErrorContextTest.java
Fix for https://github.com/mybatis/mybatis-3/issues/3203
=> Added Assertions into ErrorContextTest

src/test/java/org/apache/ibatis/reflection/property/PropertyCopierTest.java, src/test/java/org/apache/ibatis/reflection/property/SourceBeanCopierData.java, src/test/java/org/apache/ibatis/reflection/property/SourceBeanTestClass.java
When I read the PropertyCopier class in the reflection package, I wanted to test, but there was no test class, so I added the corresponding test class
=> Added PropertyCopier test case

src/main/java/org/apache/ibatis/io/VFS.java
Hi, I have found the method `org.apache.ibatis.io.VFS#getMethod`  which log message contains repeat param. 
```java
protected static Method getMethod(Class<?> clazz, String methodName, Class<?>... parameterTypes) {
...
try {
...
} catch (SecurityException e) {
...
} catch (NoSuchMethodException e) {
// repeat methodName in log message
log.error("Method not found " + clazz.getName() + "." + methodName + "." + methodName + ".  Cause: " + e);
return null;
}
}
```
If you run the unit class `org.apache.ibatis.io.VFSTest#getNotExistMethod`,  the console will show the log message.
```java
Method not found org.apache.ibatis.io.VFS.listXxx.listXxx.
```
=> remove repeat param from log message

src/main/java/org/apache/ibatis/io/DefaultVFS.java
Fixes [https://github.com/mybatis/mybatis-3/security/code-scanning/7](https://github.com/mybatis/mybatis-3/security/code-scanning/7)
To fix the problem, we need to ensure that the paths extracted from the JAR entries are validated to prevent directory traversal attacks. This can be done by normalizing the paths and ensuring they remain within the intended directory.
1. **Normalize the path**: Convert the path to its canonical form to resolve any `..` sequences.
2. **Check the path**: Ensure that the normalized path starts with the intended base directory path.
We will implement these changes in the `listResources` method where the JAR entries are processed.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> Fix code scanning alert no. 7: Arbitrary file access during archive extraction ("Zip Slip")

src/main/java/org/apache/ibatis/type/BlobTypeHandler.java, src/main/java/org/apache/ibatis/type/CharacterTypeHandler.java, src/main/java/org/apache/ibatis/type/DateOnlyTypeHandler.java, src/main/java/org/apache/ibatis/type/DateTypeHandler.java, src/main/java/org/apache/ibatis/type/TimeOnlyTypeHandler.java, src/main/java/org/apache/ibatis/type/YearMonthTypeHandler.java
Hi, I have found some code can be encapsulation to method level for resue.
=> encapsulation code to method level for reuse

src/main/java/org/apache/ibatis/parsing/XPathParser.java
Fixes [https://github.com/mybatis/mybatis-3/security/code-scanning/6](https://github.com/mybatis/mybatis-3/security/code-scanning/6)
To fix the problem, we need to disable the parsing of DTDs and external entities in the `DocumentBuilderFactory`. This can be done by setting specific features on the `DocumentBuilderFactory` instance. The changes should be made in the `createDocument` method of the `XPathParser` class.
1. Disable DTDs by setting the feature `http://apache.org/xml/features/disallow-doctype-decl` to `true`.
2. Disable external general entities by setting the feature `http://xml.org/sax/features/external-general-entities` to `false`.
3. Disable external parameter entities by setting the feature `http://xml.org/sax/features/external-parameter-entities` to `false`.
_Suggested …
=> Fix code scanning alert no. 6: Resolving XML external entity in user-controlled data

src/test/java/org/apache/ibatis/scripting/xmltags/ChooseSqlNodeTest.java, src/test/java/org/apache/ibatis/scripting/xmltags/ForEachSqlNodeTest.java, src/test/java/org/apache/ibatis/scripting/xmltags/IfSqlNodeTest.java, src/test/java/org/apache/ibatis/scripting/xmltags/MixedSqlNodeTest.java, src/test/java/org/apache/ibatis/scripting/xmltags/SetSqlNodeTest.java, src/test/java/org/apache/ibatis/scripting/xmltags/SqlNodeTest.java, src/test/java/org/apache/ibatis/scripting/xmltags/StaticTextSqlNodeTest.java, src/test/java/org/apache/ibatis/scripting/xmltags/TextSqlNodeTest.java, src/test/java/org/apache/ibatis/scripting/xmltags/TrimSqlNodeTest.java, src/test/java/org/apache/ibatis/scripting/xmltags/VarDeclSqlNodeTest.java, src/test/java/org/apache/ibatis/scripting/xmltags/WhereSqlNodeTest.java
Supplement the missing unit test cases for `SqlNode`.
=> Add sqlnode test

src/test/java/org/apache/ibatis/reflection/wrapper/BeanWrapperUnitTest.java, src/test/java/org/apache/ibatis/reflection/wrapper/CollectionWrapperUnitTest.java, src/test/java/org/apache/ibatis/reflection/wrapper/MapWrapperUnitTest.java, src/test/java/org/apache/ibatis/reflection/wrapper/ObjectWrapperBaseTest.java
Supplement the missing unit test cases for `ObjectWrapper`.
The already exists test class `BeanWrapperTest` is to test `MetaObject`, but not `BeanWrapper`.
=> Add ObjectWrapper test

src/main/java/org/apache/ibatis/mapping/VendorDatabaseIdProvider.java, src/test/java/org/apache/ibatis/mapping/VendorDatabaseIdProviderTest.java, src/test/java/org/apache/ibatis/submitted/databaseid_productname/DatabaseIdProductNameTest.java, src/test/java/org/apache/ibatis/submitted/databaseid_productname/Mapper.java, src/test/resources/org/apache/ibatis/submitted/databaseid_productname/mybatis-config.xml
`XMLConfigBuilder#databaseIdProviderElement()` sets an empty `Properties` rather than `null`.
fixes #3296
=> `VendorDatabaseIdProvider#getDatabaseId()` should return product name when properties is empty

src/main/java/org/apache/ibatis/type/NClobTypeHandler.java, src/test/java/org/apache/ibatis/type/NClobTypeHandlerTest.java
Hello, I encountered the same issue as #3287. I noticed that no one has fixed it yet, so I have submitted this PR in the hope of resolving the issue.
=> Update NClobTypeHandler to use methods for national character set

.github/workflows/site.yaml
We want to deploy the site when we release new version, however, with the current 'if' condition, the 'site' action does not run on the target commit.
The commit message of a release starts with "[maven-release-plugin] prepare release".
=> [GHA] 'site' should run on 'prepare release' commit

src/site/markdown/index.md
https://groups.google.com/g/mybatis-user/c/cISgXjIdbYA/m/2I7-sAeDAAAJ
=> Links to SNS accounts by Alejandro Duarte

src/main/java/org/apache/ibatis/executor/resultset/DefaultResultSetHandler.java, src/test/java/org/apache/ibatis/submitted/column_order_based_constructor_automapping/ColumnOrderBasedConstructorAutomappingTest.java, src/test/java/org/apache/ibatis/submitted/column_order_based_constructor_automapping/Mapper.java, src/test/java/org/apache/ibatis/submitted/column_order_based_constructor_automapping/UserConstructorEqualsResultSet.java, src/test/java/org/apache/ibatis/submitted/column_order_based_constructor_automapping/UserConstructorGreaterThanResultSet.java, src/test/java/org/apache/ibatis/submitted/column_order_based_constructor_automapping/UserConstructorLessThanResultSet.java, src/test/java/org/apache/ibatis/submitted/column_order_based_constructor_automapping/UserNoArgsConstructor.java, src/test/resources/org/apache/ibatis/submitted/column_order_based_constructor_automapping/CreateDB.sql, src/test/resources/org/apache/ibatis/submitted/column_order_based_constructor_automapping/Mapper.xml, src/test/resources/org/apache/ibatis/submitted/column_order_based_constructor_automapping/mybatis-config.xml
Hi, I have noticed that some people, when using `Lombok`, only have one constructor with all parameters due to the use of `@Data` and `@Builder` annotations. If the class property of the resultType does not match the query result, an `IndexOutOfBoundsException` exception will be thrown.
I have had several colleagues who have encountered this issue and spent some time troubleshooting it. Although it is indeed the user's problem, I think perhaps we should optimize the prompt to clearly indicate that this is the cause of the constructor, so that users can quickly find the problem when they encounter it.
Abnormal example: https://github.com/luozongle01/mybatis_index_out_of_bounds
</br>
>The following is the abnormal prompt after the problem occurs
</br>
</br>
>The following is the modified …
=> Throw helpful error instead of IndexOutOfBoundsException when there are not enough columns for constructor auto-mapping

src/main/java/org/apache/ibatis/type/DateOnlyTypeHandler.java
https://github.com/mybatis/mybatis-3/issues/3332
Fixing the change in return type of DateOnlyTypeHandler introduced [here](https://github.com/mybatis/mybatis-3/pull/3247/files#diff-3100284b93f6e47f7e09229bac897dc14edbb2e162002f24e804113f49d8b6a6L47)
=> DateOnlyTypeHandler should return java.util.Date

pom.xml
- Dropped old contributors list as not valid place to store that these days.  The user list there is mostly unrecognized contributors from long ago.  Since we have used git for ~10 years if not more, no reason to store such data as the commit history shows all that.  Also believe history was exported for google code so it should also have that information per commit.
- Remove the pre java 16 profile as we require java 17+
- Drop derby version in java16+ as we require 17 and the default is already set for java17+
- Add some adjustments (also added to parent for 49 release) that allow us to release this without messing with extra flags.
Upon this build will effectively build java 8 compliant code without thinking about it.
=> Various cleanup to help with maintenance / release process

src/test/java/org/apache/ibatis/builder/XmlConfigBuilderTest.java, src/test/java/org/apache/ibatis/executor/ExecutorTestHelper.java, src/test/java/org/apache/ibatis/jdbc/SQLTest.java, src/test/java/org/apache/ibatis/jdbc/ScriptRunnerTest.java, src/test/java/org/apache/ibatis/jdbc/SelectBuilderTest.java, src/test/java/org/apache/ibatis/jdbc/SqlBuilderTest.java, src/test/java/org/apache/ibatis/parsing/XNodeTest.java, src/test/java/org/apache/ibatis/submitted/arg_name_based_constructor_automapping/ArgNameBasedConstructorAutoMappingTest.java, src/test/java/org/apache/ibatis/submitted/complex_column/PersonMapper.java, src/test/java/org/apache/ibatis/submitted/keygen/Jdbc3KeyGeneratorTest.java, src/test/java/org/apache/ibatis/submitted/no_result_type_map/NoResultTypeMapTest.java, src/test/java/org/apache/ibatis/testcontainers/MysqlContainer.java
Also added testcontainers annotations.
=> Add text blocks in test code

.github/workflows/ci.yaml, README.md, pom.xml
Simplifies CI setup to use a profile to adjust the tag runner without having it do so for every OS known.  Rather only does it for ubuntu where required.  The pom then does the rest.  This ensures we are not blasting away argline when newer jdks need that set with information only available from within the pom for byte buddy.  There is also a setting for memory used on windows that seems to matter if removed on my local.  It didn't seem to matter on remote but it was being removed previously.  So now that is set.
=> Cleanup CI GHA an cleanup docs on test case ran

src/main/java/org/apache/ibatis/scripting/xmltags/XMLScriptBuilder.java, src/test/java/org/apache/ibatis/scripting/xmltags/XMLScriptBuilderTest.java
When parsing XML, since nested nodes have line breaks by default, these nodes should not be parsed as text nodes and added, which will cause unnecessary heap space to be occupied.
The test project reduces the creation of this node, and the space occupied by this node is reduced from 1625KB to 748KB
=> Ignore empty text node when parsing XML nodes

src/main/java/org/apache/ibatis/scripting/xmltags/ExpressionEvaluator.java, src/main/java/org/apache/ibatis/scripting/xmltags/ForEachSqlNode.java, src/main/java/org/apache/ibatis/scripting/xmltags/IfSqlNode.java
#3338 
Reduce the number of ExpressionEvaluator instances created by ForEachSqlNode and IfSqlNode
=> Sharing ExpressionEvaluator instances 

src/site/zh_CN/xdoc/sqlmap-xml.xml
Hi, when I was looking at the mybatis Chinese documentation to learn mybatis, I found that the description of `affectData` was not translated into Chinese.
=> Update the Chinese language documentation for affectData configuration

src/main/java/org/apache/ibatis/reflection/TypeParameterResolver.java
Importing changes made in [harawata/typeparameterresolver](https://github.com/harawata/typeparameterresolver)
=> TypeParameterResolver : refactoring, improvements

src/main/java/org/apache/ibatis/executor/loader/ResultLoaderMap.java, src/main/java/org/apache/ibatis/scripting/xmltags/OgnlMemberAccess.java, src/test/java/org/apache/ibatis/submitted/custom_collection_handling/CustomObjectFactory.java
=> Replace deprecated `isAccessible()` with `canAccess()`

src/test/java/org/apache/ibatis/type/DateOnlyTypeHandlerTest.java, src/test/java/org/apache/ibatis/type/DateTypeHandlerTest.java, src/test/java/org/apache/ibatis/type/TimeOnlyTypeHandlerTest.java
=> Avoid java.sql.Date vs. java.util.Date mixup

pom.xml, src/main/java/org/apache/ibatis/executor/resultset/DefaultResultSetHandler.java, src/test/java/org/apache/ibatis/executor/resultset/DefaultResultSetHandlerTest.java, src/test/java/org/apache/ibatis/submitted/oracle_implicit_cursor/Author.java, src/test/java/org/apache/ibatis/submitted/oracle_implicit_cursor/Book.java, src/test/java/org/apache/ibatis/submitted/oracle_implicit_cursor/Mapper.java, src/test/java/org/apache/ibatis/submitted/oracle_implicit_cursor/OracleImplicitCursorTest.java, src/test/java/org/apache/ibatis/testcontainers/OracleTestContainer.java, src/test/resources/org/apache/ibatis/submitted/oracle_implicit_cursor/CreateDB.sql, src/test/resources/org/apache/ibatis/submitted/oracle_implicit_cursor/Mapper.xml
- **Failing test involving Oracle's multiple result sets**
- **Handle multiple result sets (implicit cursor) with Oracle driver**
=> oracle implicit cursor workaround

hooks/pre-commit.sh, pom.xml
I have noticed that there are commits (on master) that need to fix formatting and imports occasionally, this is due to authors not having run a `mvn clean install` on their PR's, even though the builds are successful.
This will help keep master consistent in that it would run a `format` & `sort` before commit, even though it makes the commit _slightly_ slower (on my machine 2 seconds), I believe the tradeoff is worth it.
=> feat: ensure code is formatted and imports are sorted before commit

src/main/java/org/apache/ibatis/binding/MapperMethodInvoker.java, src/main/java/org/apache/ibatis/binding/MapperProxy.java, src/main/java/org/apache/ibatis/binding/MapperProxyFactory.java, src/test/java/org/apache/ibatis/binding/BindingTest.java
https://github.com/mybatis/mybatis-3/issues/3414
=> Update MapperMethodInvoker to public

src/main/java/org/apache/ibatis/scripting/xmltags/XMLScriptBuilder.java
In the memory analysis, it was found that there were some blank nodes in mybatis,
Some are line breaks followed by blank strings, which are considered as blank nodes. However, the space occupied by these nodes is meaningless, and it is possible to cache these blank nodes during parsing and only retain one instance
example:
```xml
<script>
select * from user
<where>
<if test="1==1">and id = 1</if>
<if test="1==1">and id > 0</if>
</where>
</script>
```
For example, when parsing the sample script, four line break tags will be created. This is just a simple example, and we will use more dynamic tags in the project.
This modification will not change the original script content.
=> Reuse `SqlNode` instance created for virtually empty text node

src/site/ja/xdoc/dynamic-sql.xml
I found a sentence which was not translated in Japanese, so I fixed it.
=> Update dynamic-sql.xml (Japanese translation)

src/main/java/org/apache/ibatis/scripting/xmltags/TrimSqlNode.java, src/test/java/org/apache/ibatis/builder/xml/dynamic/DynamicSqlSourceTest.java, src/test/java/org/apache/ibatis/scripting/xmltags/XMLScriptBuilderTest.java
This was the [key difference](https://github.com/mybatis/mybatis-3/pull/3349#issuecomment-2567497103) that broke #3349 .
=> `TrimSqlNode` should add an extra space when concatenating its contents like `MixedSqlNode` does

src/site/ko/markdown/index.md
=> Change the options with difference languages in ko doc

src/test/java/org/apache/ibatis/plugin/PluginTest.java, src/test/java/org/apache/ibatis/submitted/choosewhen/ChooseWhenMapper.java, src/test/java/org/apache/ibatis/submitted/choosewhen/ChooseWhenTest.java, src/test/java/org/apache/ibatis/submitted/choosewhen/User.java, src/test/java/org/apache/ibatis/submitted/optional_on_mapper_method/OptionalOnMapperMethodTest.java, src/test/java/org/apache/ibatis/submitted/overwritingproperties/FooMapperTest.java, src/test/resources/org/apache/ibatis/submitted/choosewhen/ChooseWhenMapper.xml, src/test/resources/org/apache/ibatis/submitted/choosewhen/CreateDB.sql, src/test/resources/org/apache/ibatis/submitted/choosewhen/mybatis-config.xml
This PR adds a unit test to ensure that `<choose>` with `<when>` conditions correctly falls back to `<otherwise>` when a parameter is missing or null.
While MyBatis already appears to handle OGNL evaluation with missing parameters gracefully, there wasn't an explicit test to guarantee this behavior.
By adding this test, we can be more confident that:
- When `name` is not provided, the `when` condition fails safely.
- The `otherwise` clause executes as expected, producing `AND status = 'ACTIVE'`.
- Added `ChooseWhenTest` under `submitted.choosewhen` to verify this edge case.
- Uses H2 in-memory database and `CreateDB.sql` for test setup.
I wanted to provide a clear test case that proves `<choose>` properly falls back to `<otherwise>`.  
This improves test coverage and helps ensure future …
=> Add test to validate <choose> tag's <otherwise> fallback when parameter is null

src/main/java/org/apache/ibatis/reflection/TypeParameterResolver.java, src/test/java/org/apache/ibatis/reflection/TypeParameterResolverTest.java, src/test/java/org/apache/ibatis/reflection/typeparam/Level0Mapper.java
optimize TypeParameterResolver
1. The correct ownerType has been identified
2. canonicalize type (In the original implementation, there would be a mix of JDK implementations such as sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl ...)
3. optimized toString()
4. when the specific generic is not declared, erase to the most appropriate upper bound
```java
class A<T extends Serializable> {
public T foo(T t) {
return t;
}
}
class B<T extends Number> extends A<T> {}
class C<T extends Integer> extends B<T> {}
Method m = A.class.getMethod("foo", Serializable.class);
// In old code, it's Object.class. Actually, Integer
System.out.println(TypeParameterResolver.resolveReturnType(m, C.class)); 
````
=> optimize TypeParameterResolver
